import {createGame,applyGameAction,addBotToGame,advanceBots,hasBot,tickGame} from '../../../shared/games.js';
const ok=(c,m)=>{if(!c)throw new Error(m)};
const timed=(name,fn)=>{const t=performance.now();const r=fn();console.log(name,Math.round(performance.now()-t)+'ms');return r};
let g=createGame('gomoku');applyGameAction(g,'u1',{type:'join',seat:0});addBotToGame(g,1);applyGameAction(g,'u1',{type:'ready'});timed('gomoku AI',()=>advanceBots(g));ok(g.board.flat().filter(Boolean).length===1,'gomoku black bot moved first');applyGameAction(g,'u1',{type:'place',x:7,y:8});ok(g.board.flat().filter(Boolean).length===2,'gomoku white replied');
let x=createGame('xiangqi');applyGameAction(x,'u1',{type:'join'});addBotToGame(x,1);applyGameAction(x,'u1',{type:'ready'});applyGameAction(x,'u1',{type:'move',x1:0,y1:6,x2:0,y2:5});timed('xiangqi AI',()=>advanceBots(x));ok(x.turn===0||x.winner,'xiangqi bot moved');
// Xiangqi undo: selection/UI depends on stable state; human-human requires approval, AI rolls back both plies.
let xu=createGame('xiangqi');applyGameAction(xu,'a',{type:'join',seat:0});applyGameAction(xu,'b',{type:'join',seat:1});applyGameAction(xu,'a',{type:'ready'});applyGameAction(xu,'b',{type:'ready'});const xuInitial=JSON.stringify(xu.board);applyGameAction(xu,'a',{type:'move',x1:0,y1:6,x2:0,y2:5});applyGameAction(xu,'a',{type:'undo_request'});ok(xu.undoRequest?.to===1,'xiangqi undo request');applyGameAction(xu,'b',{type:'undo_accept'});ok(JSON.stringify(xu.board)===xuInitial&&xu.turn===0&&xu.started,'xiangqi approved undo restores move');ok(Date.now()-xu.turnStartedAt<1000,'xiangqi undo restarts turn clock');
let xua=createGame('xiangqi');applyGameAction(xua,'a',{type:'join',seat:0});addBotToGame(xua,1);applyGameAction(xua,'a',{type:'ready'});const xuaInitial=JSON.stringify(xua.board);applyGameAction(xua,'a',{type:'move',x1:0,y1:6,x2:0,y2:5});advanceBots(xua);applyGameAction(xua,'a',{type:'undo_request'});ok(JSON.stringify(xua.board)===xuaInitial&&xua.turn===0&&xua.started,'xiangqi AI undo rolls back both plies');
let c=createGame('chess');applyGameAction(c,'u1',{type:'join'});addBotToGame(c,1);applyGameAction(c,'u1',{type:'ready'});applyGameAction(c,'u1',{type:'move',x1:4,y1:6,x2:4,y2:4});timed('chess AI',()=>advanceBots(c));ok(c.turn===0||c.winner||c.result,'chess bot moved');
// Western chess: Fool's Mate must end on checkmate, without king capture.
let cm=createGame('chess');cm.players=['w','b'];cm.ready=[true,true];cm.started=true;
for(const [u,a] of [['w',{type:'move',x1:5,y1:6,x2:5,y2:5}],['b',{type:'move',x1:4,y1:1,x2:4,y2:3}],['w',{type:'move',x1:6,y1:6,x2:6,y2:4}],['b',{type:'move',x1:3,y1:0,x2:7,y2:4}]])applyGameAction(cm,u,a);
ok(cm.winner==='b'&&cm.result==='checkmate'&&!cm.started,'chess checkmate result');ok(cm.board[7][4]==='wk','white king must remain on board');
// Xiangqi: construct a forced mate. Red rook moves to (4,1); black general has no legal escape/capture.
let xm=createGame('xiangqi');xm.board=Array.from({length:10},()=>Array(9).fill(null));xm.players=['r','b'];xm.ready=[true,true];xm.started=true;xm.turn=0;xm.board[9][4]='K';xm.board[0][4]='k';xm.board[1][3]='R';xm.board[1][5]='R';xm.board[2][4]='R';
applyGameAction(xm,'r',{type:'move',x1:4,y1:2,x2:4,y2:1});
ok(xm.winner==='r'&&xm.result==='checkmate'&&!xm.started,'xiangqi checkmate result');ok(xm.board[0][4]==='k','black general must remain on board');
let f=createGame('gomoku');applyGameAction(f,'u1',{type:'join',seat:0});applyGameAction(f,'u2',{type:'join',seat:1});applyGameAction(f,'u1',{type:'ready'});applyGameAction(f,'u2',{type:'ready'});ok(f.started,'human board start');let ignored=false;try{applyGameAction(f,'u2',{type:'focus_forfeit'})}catch{ignored=true}ok(ignored&&f.started&&!f.winner,'focus forfeit removed');
let tf=createGame('gomoku');tf.players=['t1','t2'];tf.ready=[true,true];tf.started=true;tf.turn=0;tf.timeBanks=[5,200000];tf.turnStartedAt=Date.now()-10020;tickGame(tf,Date.now());ok(tf.winner==='t2'&&tf.result==='time_forfeit','board bank timeout');
let b=createGame('blackjack');applyGameAction(b,'u1',{type:'join',seat:0});applyGameAction(b,'u2',{type:'join',seat:1});applyGameAction(b,'u1',{type:'ready'});let threw=false;try{applyGameAction(b,'u1',{type:'start'})}catch{threw=true}ok(threw,'blackjack all ready');applyGameAction(b,'u2',{type:'ready'});applyGameAction(b,'u1',{type:'start'});ok(['insurance','playing','result'].includes(b.phase),'blackjack start');
let bp=createGame('blackjack');applyGameAction(bp,'u1',{type:'join',seat:0});addBotToGame(bp,1);applyGameAction(bp,'u1',{type:'ready'});applyGameAction(bp,'u1',{type:'start'});ok(bp.practice&&hasBot(bp),'blackjack practice');
let p=createGame('poker');applyGameAction(p,'u1',{type:'join',seat:0,chips:1000});applyGameAction(p,'u2',{type:'join',seat:1,chips:1000});ok(p.seats[0].chips===1000,'poker fixed wallet chips');applyGameAction(p,'u1',{type:'ready'});threw=false;try{applyGameAction(p,'u1',{type:'start'})}catch{threw=true}ok(threw,'poker all ready');applyGameAction(p,'u2',{type:'ready'});applyGameAction(p,'u1',{type:'start'});ok(p.phase==='preflop','poker start');
// Poker raise regression: a typed large raise is accepted as the requested raise amount, not reset/coerced to minRaise.
applyGameAction(p,'u1',{type:'raise',amount:500});ok(p.currentBet===520&&p.seats[0].roundBet===520&&p.seats[0].chips===480,'poker +500 raise');
// Short all-in must not reopen betting to a player who already acted.
let ps=createGame('poker');applyGameAction(ps,'u1',{type:'join',seat:0,chips:1000});applyGameAction(ps,'u2',{type:'join',seat:1,chips:150});applyGameAction(ps,'u3',{type:'join',seat:2,chips:1000});for(const u of ['u1','u2','u3'])applyGameAction(ps,u,{type:'ready'});applyGameAction(ps,'u1',{type:'start'});applyGameAction(ps,'u1',{type:'raise',amount:100});applyGameAction(ps,'u2',{type:'allin'});ok(ps.currentBet===150&&ps.shortRaiseActive,'poker short all-in detected');applyGameAction(ps,'u3',{type:'call'});let shortBlocked=false;try{applyGameAction(ps,'u1',{type:'raise',amount:100})}catch{shortBlocked=true}ok(shortBlocked,'poker short all-in does not reopen raise');
// Main/side pots: 100/200/300 all-ins create 300 main + 200 side + 100 side.
let pots=createGame('poker');applyGameAction(pots,'u1',{type:'join',seat:0,chips:100});applyGameAction(pots,'u2',{type:'join',seat:1,chips:200});applyGameAction(pots,'u3',{type:'join',seat:2,chips:300});for(const u of ['u1','u2','u3'])applyGameAction(pots,u,{type:'ready'});applyGameAction(pots,'u1',{type:'start'});applyGameAction(pots,'u1',{type:'allin'});applyGameAction(pots,'u2',{type:'allin'});applyGameAction(pots,'u3',{type:'allin'});ok(pots.phase==='run_choice','poker all-in enters run choice');for(const u of ['u1','u2','u3'])applyGameAction(pots,u,{type:'run_board',count:1});ok(pots.phase==='result'&&pots.boardRuns.length===1,'poker all-in runs board once');ok(pots.potBreakdown.map(x=>x.amount).join(',')==='300,200,100','poker side pots');
let pp=createGame('poker');applyGameAction(pp,'u1',{type:'join',seat:0,chips:1000});addBotToGame(pp,1);ok(pp.seats[1].chips===2000,'poker bot uses default 2000 stack');applyGameAction(pp,'u1',{type:'ready'});applyGameAction(pp,'u1',{type:'start'});ok(pp.practice&&hasBot(pp),'poker practice');
console.log('ALL GAME TESTS PASS');
