import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {ROOM_DEFS,ROOM_MAP,roomInitialState,createGame,applyGameAction,publicGameState,addBotToGame,removeBotFromGame,advanceBots,hasBot,isBotId,tickGame} from './shared/games.js';
import {createMusicService} from './server/music_service.js';
import {DEFAULT_ECONOMY,DEFAULT_GAME_CHIP_RULES,boundedInt,normalizeEconomy,migrateEconomyV029} from './server/economy.js';
import {createRankingService} from './server/rankings.js';
import {createLeaderboardHttp} from './server/leaderboard_http.js';
import {createHttpSecurity} from './server/http_security.js';
import {createDeviceIdentity} from './server/device_identity.js';
import {createUserMergeService} from './server/user_merge.js';
import {createDeviceProfile} from './server/device_profile.js';
import {createChatService} from './server/chat_service.js';
import {voiceIceServersFromEnv} from './server/voice_config.js';
import {syncReleaseNotes} from './server/release_notes.js';
import {createRuntimeDiagnostics} from './server/runtime_diagnostics.js';
import {createNetworkSync} from './server/network_sync.js';
import {createWsTransport} from './server/ws_transport.js';
import {createRoomChangeHub} from './server/room_change_hub.js';
import {createActionReceipts} from './server/action_receipts.js';
import {createWsSessionAuth} from './server/ws_session_auth.js';
import {createHttpRoomTransport} from './server/http_room_transport.js';
import {createStaticService} from './server/static_service.js';
import {unreadySeatDelayMs,disconnectedSeatDelayMs,resultCleanupDelayMs} from './server/game_lifecycle.js';
import {createProgressionService,ensureProgressionUser,publicProgressionExtras} from './server/progression.js';
import {createLeisureService} from './server/leisure_service.js';
import {createChatState as CCS} from './server/chat_state.js';
import {applyReleaseReward as ARR} from './server/release_rewards.js';
import {openBrowser} from './server/open_browser.js';
import {socialPayload} from './server/social_helpers.js';
import {validateRoomMessage,directLoopbackOnly} from './server/input_validation.js';
import {createMusicHttpRoutes} from './server/music_http_routes.js';
const __filename=fileURLToPath(import.meta.url),ROOT=path.dirname(__filename),PUBLIC=path.join(ROOT,'public');
try{if(typeof process.loadEnvFile==='function'&&fs.existsSync(path.join(ROOT,'.dev.vars')))process.loadEnvFile(path.join(ROOT,'.dev.vars'))}catch(e){console.warn('[WARN] .dev.vars:',e.message)}
const APP='SlimeLounge',VERSION='0.4.3',HOST='0.0.0.0',PORT=Number(process.env.PORT||8090);
const CHIP_TIME_ZONE=process.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai',TRUST_PROXY=process.env.SLIMELOUNGE_TRUST_PROXY!=='0',TRUSTED_PROXY_IPS=String(process.env.SLIMELOUNGE_TRUSTED_PROXY_IPS||''),COOKIE_SECURE=process.env.SLIMELOUNGE_COOKIE_SECURE==='1',PUBLIC_ORIGIN=String(process.env.SLIMELOUNGE_PUBLIC_ORIGIN||'').trim().replace(/\/$/,'');
const rateBuckets=new Map();
const {requestIp,requestIpInfo,applySecurityHeaders,rateLimit,rateLimitSubject,sameOriginWs,json,body,contentType,canonicalRedirectTarget}=createHttpSecurity({trustProxy:TRUST_PROXY,publicOrigin:PUBLIC_ORIGIN,rateBuckets,trustedProxyIps:TRUSTED_PROXY_IPS});
const diagnostics=createRuntimeDiagnostics({requestIpInfo,version:VERSION,trustProxy:TRUST_PROXY});
const DATA_DIR=process.env.SLIMELOUNGE_DATA_DIR||(process.platform==='win32'?path.join(process.env.LOCALAPPDATA||process.env.APPDATA||os.homedir(),'SlimeLounge'):path.join(os.homedir(),'.slimelounge'));
fs.mkdirSync(DATA_DIR,{recursive:true});const DATA_FILE=path.join(DATA_DIR,'data.json');
const SLIME_COLORS=new Set(['mint','sky','peach','lemon','lilac','milk','cocoa','rose','aqua','lime']);
const clients=new Set(),disconnectTimers=new Map(),activeTabs=new Map(),roomPollers=new Map(),ownerRecoveryAttempts=new Map(),originTransfers=new Map(),presencePersistAt=new Map();const roomChanges=createRoomChangeHub(),actionReceipts=createActionReceipts();let saveTimer=null;
const DISCONNECT_GRACE_MS=Math.max(500,Number(process.env.SLIMELOUNGE_DISCONNECT_GRACE_MS||15000)),TAB_TTL_MS=Math.max(30000,Number(process.env.SLIMELOUNGE_TAB_TTL_MS||45000)),TAB_HIDDEN_TTL_MS=Math.max(TAB_TTL_MS,Number(process.env.SLIMELOUNGE_TAB_HIDDEN_TTL_MS||1800000)),ROOM_POLL_TTL_MS=Math.max(30000,Number(process.env.SLIMELOUNGE_ROOM_POLL_TTL_MS||90000));
const disconnectKey=(userId,roomId)=>`${userId}|${roomId}`;
const tabKey=(userId,tabId)=>`${userId}|${tabId}`;
const roomPollKey=(userId,roomId,tabId)=>`${userId}|${roomId}|${tabId}`;
function purgeTabs(now=Date.now()){for(const [k,x] of activeTabs){const exp=typeof x==='number'?x+TAB_TTL_MS:Number(x?.expiresAt)||0;if(!exp||now>exp)activeTabs.delete(k)}}
function purgeRoomPollers(now=Date.now()){for(const [k,x] of roomPollers){const ttl=x.kind==='compat'?3500:ROOM_POLL_TTL_MS;if(now-x.at>ttl)roomPollers.delete(k)}}
function tabTouch(userId,tabId,leaseMs=TAB_TTL_MS){const tid=clean(tabId,96);if(!userId||!tid)return;purgeTabs();const now=Date.now(),lease=Math.max(TAB_TTL_MS,Math.min(TAB_HIDDEN_TTL_MS,Number(leaseMs)||TAB_TTL_MS));activeTabs.set(tabKey(userId,tid),{at:now,expiresAt:now+lease})}
function tabDrop(userId,tabId){const tid=clean(tabId,96);if(!userId||!tid)return;activeTabs.delete(tabKey(userId,tid))}
function roomPollTouch(userId,roomId,tabId,quiet=false,kind='poll'){const tid=clean(tabId,96);if(!userId||!roomId||!tid)return false;purgeRoomPollers();const k=roomPollKey(userId,roomId,tid),prev=roomPollers.get(k),fresh=!prev,nextKind=prev?.kind==='poll'?'poll':kind;roomPollers.set(k,{userId,roomId,tabId:tid,at:Date.now(),kind:nextKind});if(fresh){if(!quiet&&nextKind==='poll')console.warn(`[HTTP FALLBACK] user=${userId} room=${roomId}`);roomChanges.touch(roomId)}return fresh}
function roomPollDrop(userId,roomId,tabId){const tid=clean(tabId,96);if(!userId)return;for(const [k,x] of roomPollers)if(x.userId===userId&&(!roomId||x.roomId===roomId)&&(!tid||x.tabId===tid))roomPollers.delete(k)}
function userIsOnline(userId){purgeTabs();purgeRoomPollers();for(const c of clients)if(!c.closed&&c.userId===userId)return true;for(const x of roomPollers.values())if(x.userId===userId)return true;const prefix=`${userId}|`;for(const k of activeTabs.keys())if(k.startsWith(prefix))return true;return false}
function schedulePresenceSave(userId,now=Date.now()){const last=presencePersistAt.get(userId)||0;if(now-last<30000)return;presencePersistAt.set(userId,now);scheduleSave()}
function applyPresenceUpdate(u,{section='',roomId='',presenceStatus='',activityLabel='',tabId='',tabState='visible'}={}){const now=Date.now();u.lastSeenAt=now;u.currentSection=clean(section,24);u.currentRoomId=clean(roomId,48);if(['online','busy','away','trading','fishing','gaming','listening','voice'].includes(presenceStatus))u.presenceStatus=presenceStatus;u.activityLabel=clean(activityLabel,80);tabTouch(u.userId,tabId,tabState==='hidden'?TAB_HIDDEN_TTL_MS:TAB_TTL_MS);schedulePresenceSave(u.userId,now)}
function limitUser(a,key,limit,windowMs,req){const subject=`user:${a?.u?.userId||'unknown'}`;const ok=rateLimitSubject(subject,key,limit,windowMs);if(!ok)diagnostics.noteRateLimit(req,key,'user');return ok}
const actionSeen=(userId,roomId,actionId)=>actionReceipts.seen(userId,roomId,actionId);
const rememberAction=(userId,roomId,actionId)=>actionReceipts.remember(userId,roomId,actionId);
const blank=()=>({schemaVersion:23,salt:crypto.randomBytes(24).toString('hex'),ownerUserId:null,users:{},devices:{},employeeIndex:{},employeeHistory:[],employeeChangeRequests:[],ownerRecoveryTokens:[],deviceLinkTokens:[],musicAccounts:{},qqMusicAccounts:{},friendships:[],directMessages:{},directMessageReads:{},roomMessages:{},roomMusic:{},roomGames:{},rankings:{},rankingProcessed:{},chipSettlements:{},chipLedger:[],economy:null,releaseNotesPublished:[]});
function load(){try{if(!fs.existsSync(DATA_FILE))return blank();const d={...blank(),...JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))};d.users||={};d.devices||={};d.employeeIndex||={};d.employeeHistory||=[];d.employeeChangeRequests||=[];d.ownerRecoveryTokens||=[];d.deviceLinkTokens||=[];d.musicAccounts||={};d.qqMusicAccounts||={};d.friendships||=[];d.directMessages||={};d.directMessageReads||={};d.roomMessages||={};d.roomMusic||={};d.roomGames||={};d.rankings||={};d.rankingProcessed||={};d.chipSettlements||={};d.chipLedger=Array.isArray(d.chipLedger)?d.chipLedger:[];d.releaseNotesPublished=Array.isArray(d.releaseNotesPublished)?d.releaseNotesPublished:[];for(const k of ['dice','gomoku','xiangqi','chess','blackjack','poker','go','mahjong','uno','doudizhu'])d.rankings[k]||={};for(const u of Object.values(d.users))ensureProgressionUser(u);return d}catch(e){console.warn('[WARN] data load failed:',e.message);return blank()}}
let data=load();
function economyConfig(){data.economy=normalizeEconomy(data.economy||{});return data.economy}
function chipFloor(){return economyConfig().chipFloor??DEFAULT_ECONOMY.chipFloor}
function chipRecoverPerHour(){return economyConfig().recoverPerHour??DEFAULT_ECONOMY.recoverPerHour}
function chipDailyReward(){return economyConfig().dailyReward??DEFAULT_ECONOMY.dailyReward}
function chipRecoverMs(){const rate=chipRecoverPerHour();return rate>0?Math.ceil(chipFloor()/rate*3600000):0}
function gameEntryFee(kind,mode='human'){const r=economyConfig().gameRules?.[kind]||{};return Math.max(0,Math.floor(Number(mode==='ai'?r.aiEntryFee:r.entryFee)||0))}
try{if(fs.existsSync(DATA_FILE)){const bd=path.join(DATA_DIR,'backups');fs.mkdirSync(bd,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,'-');fs.copyFileSync(DATA_FILE,path.join(bd,`data-${stamp}.json`));const old=fs.readdirSync(bd).filter(x=>x.endsWith('.json')).sort().reverse();for(const x of old.slice(10))fs.unlinkSync(path.join(bd,x));}}catch(e){console.warn('[WARN] backup failed:',e.message)}
function save(){clearTimeout(saveTimer);saveTimer=null;const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2),{mode:0o600});fs.renameSync(tmp,DATA_FILE);try{fs.chmodSync(DATA_FILE,0o600)}catch{}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,200)}
const clean=(v,n=32)=>String(v??'').replace(/[\r\n\t]/g,' ').replace(/\s+/g,' ').trim().slice(0,n);
const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const secretHash=v=>sha(`${data.salt}:${v}`);
const token=()=>crypto.randomBytes(32).toString('base64url');
function normalizeEmployee(v){return clean(v,24).replace(/\s+/g,'').toUpperCase()}
function validEmployee(v){return /^[A-Z0-9]{6,9}$/.test(v)}
function maskEmployee(v){if(!v)return '未绑定';if(v.length<=4)return '*'.repeat(v.length);return '*'.repeat(Math.max(2,v.length-4))+v.slice(-4)}
const {addDeviceToken,deviceTokenOk,sessionKeyOk,sessionPair,issueRecoveryCookie,ensureRecoveryCookie}=createDeviceIdentity({sha,token,cookieSecure:COOKIE_SECURE,scheduleSave});
const {applyDeviceMeta,devicePublic,findReusableDevice}=createDeviceProfile({clean,sha,requestIpInfo});
function touchDevice(d,u,req,deviceInfo=null){const now=Date.now();d.lastSeenAt=now;u.lastSeenAt=now;if(req)applyDeviceMeta(d,req,deviceInfo);scheduleSave()}
function issueUserDevice(u,label,req,res,{deviceInfo={},existingDeviceId='',reuseDeviceId=''}={}){const now=Date.now(),reuse=findReusableDevice(data.devices,u.userId,{existingDeviceId:reuseDeviceId||existingDeviceId,installId:deviceInfo?.installId}),deviceId=reuse?.deviceId||crypto.randomUUID(),deviceToken=token(),d=reuse||{deviceId,userId:u.userId,createdAt:now};d.userId=u.userId;d.label=clean(label,32)||d.label||'当前设备';d.lastSeenAt=now;addDeviceToken(d,deviceToken);applyDeviceMeta(d,req,deviceInfo);data.devices[deviceId]=d;issueRecoveryCookie(d,res);u.lastSeenAt=now;return {ok:true,userId:u.userId,deviceId,deviceToken,profile:publicUser(u),employeeMasked:u.employeeMasked||'未绑定',deviceLabel:d.label,reusedDevice:!!reuse}}
function restoreByCookie(req,res){const p=sessionPair(req);if(!p)return null;const d=data.devices[p.deviceId],u=d&&data.users[d.userId];if(!d||!u||!sessionKeyOk(d,p.key))return null;const deviceToken=token();addDeviceToken(d,deviceToken);touchDevice(d,u,req);issueRecoveryCookie(d,res);return {ok:true,userId:u.userId,deviceId:d.deviceId,deviceToken,profile:publicUser(u),employeeMasked:u.employeeMasked||'未绑定',deviceLabel:d.label||'设备',social:social(u.userId)}}
function passiveSession(req){const p=sessionPair(req);if(!p)return null;const d=data.devices[p.deviceId],u=d&&data.users[d.userId];return d&&u&&sessionKeyOk(d,p.key)?{u,d}:null}
function secretBoxKey(){return crypto.createHash('sha256').update(String(process.env.NETEASE_COOKIE_SECRET||process.env.EMPLOYEE_HASH_SECRET||data.salt)).digest()}
function sealSecret(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',secretBoxKey(),iv),ct=Buffer.concat([c.update(String(v),'utf8'),c.final()]),tag=c.getAuthTag();return `${iv.toString('base64url')}.${tag.toString('base64url')}.${ct.toString('base64url')}`}
function openSecret(v){try{const [a,b,c]=String(v||'').split('.'),iv=Buffer.from(a,'base64url'),tag=Buffer.from(b,'base64url'),ct=Buffer.from(c,'base64url'),d=crypto.createDecipheriv('aes-256-gcm',secretBoxKey(),iv);d.setAuthTag(tag);return Buffer.concat([d.update(ct),d.final()]).toString('utf8')}catch{return''}}
function normalizeNeteaseCookie(v){const raw=String(v||'').trim();if(!raw)return'';const music=(raw.match(/(?:^|;\s*)MUSIC_U=([^;\s]+)/i)||[])[1]||(!raw.includes('=')?raw:'');if(!music)return'';const csrf=(raw.match(/(?:^|;\s*)__csrf=([^;\s]+)/i)||[])[1]||'';return `MUSIC_U=${music};${csrf?` __csrf=${csrf};`:''} os=pc; appver=9.3.0;`}
function neteaseCookieForUser(userId){const x=data.musicAccounts?.[userId];return x?.sealed?openSecret(x.sealed):''}
function neteaseAccountPublic(userId){const x=data.musicAccounts?.[userId];return x?{linked:true,updatedAt:x.updatedAt||0,label:x.label||'网易云账号授权'}:{linked:false}}
function normalizeQQCookie(v){const raw=String(v||'').trim();if(!raw)return'';const keep=new Set(['uin','wxuin','qqmusic_key','qm_keyst','psrf_qqaccess_token','psrf_qqopenid','psrf_qqunionid','psrf_access_token_expiresAt','psrf_musickey_createtime','qqmusic_fromtag','login_type']);const out=[];for(const part of raw.split(';')){const i=part.indexOf('=');if(i<1)continue;const k=part.slice(0,i).trim(),val=part.slice(i+1).trim();if(keep.has(k)&&val)out.push(`${k}=${val}`)}const hasKey=out.some(x=>x.startsWith('qqmusic_key=')||x.startsWith('qm_keyst='));return hasKey?out.join('; '):''}
function qqCookieForUser(userId){const x=data.qqMusicAccounts?.[userId];return x?.sealed?openSecret(x.sealed):''}
function qqAccountPublic(userId){const x=data.qqMusicAccounts?.[userId];return x?{linked:true,updatedAt:x.updatedAt||0,label:x.label||'QQ音乐账号授权'}:{linked:false}}
function qqUin(cookie=''){const m=String(cookie).match(/(?:^|;\s*)(?:uin|wxuin)=o?(\d{4,16})/i);return m?.[1]||'0'}
function purgeDeviceLinks(now=Date.now()){data.deviceLinkTokens=(data.deviceLinkTokens||[]).filter(x=>!x.usedAt&&(x.expiresAt||0)>now)}
const DEVICE_CODE_ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function normalizeDeviceLinkCode(v){return String(v||'').normalize('NFKC').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,32)}
function createDeviceLink(userId,reuseDeviceId=''){purgeDeviceLinks();const u=data.users[userId];if(!u)throw Error('账号不存在');if(reuseDeviceId&&data.devices[reuseDeviceId]?.userId!==userId)throw Error('指定设备不存在');let raw='';for(let i=0;i<16;i++)raw+=DEVICE_CODE_ALPHABET[crypto.randomInt(DEVICE_CODE_ALPHABET.length)];const code=raw.match(/.{1,4}/g).join('-'),now=Date.now();data.deviceLinkTokens.push({hash:sha(`device-link:${raw}`),userId,reuseDeviceId:reuseDeviceId||'',createdAt:now,expiresAt:now+30*60*1000});save();return {code,rawCode:raw,expiresAt:now+30*60*1000,profile:publicUser(u),reuseDeviceId:reuseDeviceId||''}}
function redeemDeviceLink(code,label,req,res,{existingDeviceId='',deviceInfo={}}={}){purgeDeviceLinks();const normalized=normalizeDeviceLinkCode(code),h=sha(`device-link:${normalized}`),x=(data.deviceLinkTokens||[]).find(t=>t.hash===h&&!t.usedAt&&(t.expiresAt||0)>Date.now());if(!x)throw Error('设备绑定码不正确或已失效');const u=data.users[x.userId];if(!u)throw Error('原账号不存在');x.usedAt=Date.now();const out=issueUserDevice(u,label||'新绑定设备',req,res,{deviceInfo,existingDeviceId,reuseDeviceId:x.reuseDeviceId||''});save();return out}
function isLoopbackRequest(req){return directLoopbackOnly(req)}
function proxyMode(){if(process.env.HTTPS_PROXY||process.env.HTTP_PROXY)return 'env-proxy';if(process.env.SLIMELOUNGE_PROXY_PAC)return 'pac-detected';return 'direct'}
function localUserRows(){return Object.values(data.users).map(u=>({...publicUser(u),employeeId:u.employeeId||'',employeeMasked:u.employeeMasked||'未绑定',lastSeenAt:u.lastSeenAt||0,deviceCount:Object.values(data.devices).filter(d=>d.userId===u.userId).length,devices:Object.values(data.devices).filter(d=>d.userId===u.userId).map(devicePublic),deviceLabels:Object.values(data.devices).filter(d=>d.userId===u.userId).map(d=>d.label||'设备')})).sort((a,b)=>(a.userId===data.ownerUserId?-1:b.userId===data.ownerUserId?1:(a.createdAt||0)-(b.createdAt||0)))}
function bindLocalOwnerDevice(label='服务器本机 · Owner'){const u=data.users[data.ownerUserId];if(!u||u.role!=='owner')return null;const now=Date.now(),safeLabel=clean(label,32)||'服务器本机 · Owner',existing=Object.values(data.devices).find(d=>d.userId===u.userId&&d.localOwnerDevice===true),deviceId=existing?.deviceId||crypto.randomUUID(),deviceToken=token(),d=existing||{deviceId,userId:u.userId,createdAt:now,localOwnerDevice:true};d.label=safeLabel;d.lastSeenAt=now;addDeviceToken(d,deviceToken);data.devices[deviceId]=d;u.lastSeenAt=now;u.employeeStatus='verified';save();return {ok:true,userId:u.userId,deviceId,deviceToken,profile:publicUser(u),employeeMasked:u.employeeMasked||'未绑定',deviceLabel:safeLabel}}
function makeLoungeId(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let id;do{id='SL-';for(let i=0;i<7;i++)id+=chars[crypto.randomInt(chars.length)]}while(Object.values(data.users).some(u=>u.loungeId===id));return id}
function gameChipRule(kind,st=null){return st?.chipRuleSnapshot||data.economy?.gameRules?.[kind]||DEFAULT_GAME_CHIP_RULES[kind]||{}}
function applyEconomyToGameState(st){if(!st)return st;const r=economyConfig().gameRules?.[st.kind]||DEFAULT_GAME_CHIP_RULES[st.kind]||{};st.entryFee=Math.max(0,Number(r.entryFee)||0);st.aiEntryFee=Math.max(0,Number(r.aiEntryFee)||0);if(st.kind==='blackjack'){st.defaultStack=chipFloor();st.betMin=r.minBet;st.betMax=r.maxBet;st.defaultBet=r.defaultBet;}else if(st.kind==='poker'){st.defaultStack=chipFloor();st.smallBlind=r.smallBlind;st.bigBlind=r.bigBlind;st.minRaiseBase=r.bigBlind;if(!gameIsActive(st))st.minRaise=r.bigBlind;}return st}
function snapshotChipRule(st){if(!st)return;const r=data.economy?.gameRules?.[st.kind]||DEFAULT_GAME_CHIP_RULES[st.kind]||{};st.chipRuleSnapshot=JSON.parse(JSON.stringify(r));}
function migrateData(){
const oldSchema=Number(data.schemaVersion||1);data.schemaVersion=23;data.economy=oldSchema<21?migrateEconomyV029(data.economy||{}):normalizeEconomy(data.economy||{});data.employeeChangeRequests||=[];data.ownerRecoveryTokens||=[];data.deviceLinkTokens||=[];data.musicAccounts||={};data.qqMusicAccounts||={};data.directMessages||={};data.directMessageReads||={};data.rankings||={};for(const k of ['dice','gomoku','xiangqi','chess','blackjack','poker','go','mahjong','uno','doudizhu'])data.rankings[k]||={};for(const u of Object.values(data.users))ensureProgressionUser(u);if(oldSchema<3)data.roomGames={};if(oldSchema<15)data.roomMessages['chat-changelog']=[];
const configured=normalizeEmployee(process.env.OWNER_EMPLOYEE_ID||'');let owner=null;
if(configured&&validEmployee(configured)){const h=secretHash(configured);owner=Object.values(data.users).find(u=>u.employeeHash===h)||null}else owner=Object.values(data.users).find(u=>u.role==='owner')||Object.values(data.users).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0))[0]||null;
for(const u of Object.values(data.users))if(u.role==='owner'&&u.userId!==owner?.userId)u.role='member';
if(owner){owner.role='owner';owner.employeeStatus='verified';data.ownerUserId=owner.userId}else data.ownerUserId=null;
for(const d of Object.values(data.devices)){if(!Array.isArray(d.tokenHashes))d.tokenHashes=d.tokenHash?[d.tokenHash]:[];if(!Array.isArray(d.sessionHashes))d.sessionHashes=d.sessionHash?[d.sessionHash]:[];d.lastIp=d.lastIp||'';d.lastIpVersion=d.lastIpVersion||0;d.lastForwardedFor=d.lastForwardedFor||'';d.lastProxyIp=d.lastProxyIp||'';d.lastHost=d.lastHost||'';d.lastUserAgent=d.lastUserAgent||'';}
for(const u of Object.values(data.users)){u.employeeId=u.employeeId||'';u.presenceStatus=u.presenceStatus==='focus'?'online':(u.presenceStatus||'online');u.manualPresenceStatus=['online','busy','away'].includes(u.manualPresenceStatus)?u.manualPresenceStatus:(['online','busy','away'].includes(u.presenceStatus)?u.presenceStatus:'online');u.activityLabel=u.activityLabel||'';u.followedChannels=Array.isArray(u.followedChannels)?u.followedChannels.filter(x=>ROOM_MAP[x]?.category==='chat'):[];if(!u.followedChannels.includes('chat-announcements'))u.followedChannels.unshift('chat-announcements');u.statusMessage=u.statusMessage||'';u.employeeStatus=u.employeeStatus||(u.userId===data.ownerUserId?'verified':'pending');u.lastSeenAt=u.lastSeenAt||0;u.currentSection=u.currentSection||'';u.currentRoomId=u.currentRoomId||'';u.chips=Number.isFinite(u.chips)?Math.max(0,u.chips):chipFloor();u.chipsUpdatedAt=u.chipsUpdatedAt||Date.now();u.lastChipCheckinDay=u.lastChipCheckinDay||'';}
save();
}
migrateData();
syncReleaseNotes({data,root:ROOT,crypto});ARR({data,version:VERSION});
for(const def of ROOM_DEFS)if(def.game&&!def.single){data.roomGames[def.id]=createGame(def.game);applyEconomyToGameState(data.roomGames[def.id]);}
save();
function purgeOwnerRecovery(now=Date.now()){data.ownerRecoveryTokens=(data.ownerRecoveryTokens||[]).filter(x=>!x.usedAt&&(x.expiresAt||0)>now)}
function createOwnerRecoveryCode(createdBy='server-console'){
const owner=data.users[data.ownerUserId];if(!owner||owner.role!=='owner')throw Error('当前没有可恢复的 Owner');purgeOwnerRecovery();
const code=crypto.randomBytes(12).toString('base64url').toUpperCase(),now=Date.now();data.ownerRecoveryTokens.push({id:crypto.randomUUID(),hash:sha(`owner-recovery:${code}`),createdAt:now,expiresAt:now+10*60*1000,createdBy});save();return {code,expiresAt:now+10*60*1000,ownerName:owner.name,employeeMasked:owner.employeeMasked||maskEmployee(owner.employeeId)};
}
function ownerRecoveryRateOk(ip){const now=Date.now(),key=String(ip||'unknown'),arr=(ownerRecoveryAttempts.get(key)||[]).filter(x=>now-x<15*60*1000);if(arr.length>=6){ownerRecoveryAttempts.set(key,arr);return false}arr.push(now);ownerRecoveryAttempts.set(key,arr);return true}
function recoverOwnerDevice(employeeId,code,label,req,res,{existingDeviceId='',deviceInfo={}}={}){
const owner=data.users[data.ownerUserId];if(!owner||owner.role!=='owner')throw Error('Owner 身份不存在');if(!ownerRecoveryRateOk(requestIp(req)))throw Error('恢复尝试过多，请 15 分钟后再试');const emp=normalizeEmployee(employeeId),ownerEmp=normalizeEmployee(owner.employeeId||process.env.OWNER_EMPLOYEE_ID||'');if(!emp||emp!==ownerEmp)throw Error('Owner 工号或一次性恢复码不正确');purgeOwnerRecovery();const h=sha(`owner-recovery:${clean(code,64).toUpperCase()}`),tok=(data.ownerRecoveryTokens||[]).find(x=>x.hash===h&&!x.usedAt&&(x.expiresAt||0)>Date.now());if(!tok)throw Error('Owner 工号或一次性恢复码不正确/已失效');
tok.usedAt=Date.now();for(const x of data.ownerRecoveryTokens||[])if(!x.usedAt)x.usedAt=Date.now();
for(const c of [...clients])if(c.userId===owner.userId){try{c.socket.end()}catch{}remove(c)}
for(const [k,x] of [...roomPollers])if(x.userId===owner.userId)roomPollers.delete(k);for(const k of [...activeTabs.keys()])if(k.startsWith(`${owner.userId}|`))activeTabs.delete(k);
const reuse=findReusableDevice(data.devices,owner.userId,{existingDeviceId,installId:deviceInfo?.installId});for(const [id,d] of Object.entries(data.devices))if(d.userId===owner.userId&&!d.localOwnerDevice&&id!==reuse?.deviceId)delete data.devices[id];owner.employeeStatus='verified';const out=issueUserDevice(owner,label||'Owner 恢复设备',req,res,{deviceInfo,existingDeviceId:reuse?.deviceId||existingDeviceId});save();return {...out,revokedOldDevices:true};
}
function dailyKey(now=Date.now()){const parts=new Intl.DateTimeFormat('en-US',{timeZone:CHIP_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(now));const pick=t=>parts.find(x=>x.type===t)?.value||'';return `${pick('year')}-${pick('month')}-${pick('day')}`}
function refreshWallet(u,now=Date.now()){if(!u)return 0;const floor=chipFloor(),rate=chipRecoverPerHour();u.chips=Number.isFinite(u.chips)?Math.max(0,u.chips):floor;u.chipsUpdatedAt=u.chipsUpdatedAt||now;const elapsed=Math.max(0,now-u.chipsUpdatedAt);if(u.chips<floor&&elapsed>0&&rate>0)u.chips=Math.min(floor,u.chips+rate*elapsed/3600000);u.chipsUpdatedAt=now;return Math.floor(u.chips)}
function publicUser(u){ensureProgressionUser(u);const chips=refreshWallet(u);return {userId:u.userId,loungeId:u.loungeId,name:u.name,slimeColor:u.slimeColor,bio:u.bio||'',role:u.role||'member',presenceStatus:u.presenceStatus||'online',manualPresenceStatus:u.manualPresenceStatus||'online',statusMessage:u.statusMessage||'',activityLabel:u.activityLabel||'',employeeStatus:u.employeeStatus||'pending',chips,chipsUpdatedAt:u.chipsUpdatedAt||Date.now(),chipFloor:chipFloor(),chipRecoverMs:chipRecoverMs(),chipRecoverPerHour:chipRecoverPerHour(),dailyChipReward:chipDailyReward(),lastChipCheckinDay:u.lastChipCheckinDay||'',canChipCheckin:(u.lastChipCheckinDay||'')!==dailyKey(),createdAt:u.createdAt,...publicProgressionExtras(u,data.progressionConfig)}}
function verifiedOnly(a){if(!a)return '身份无效';if(a.u.role==='owner'||a.u.role==='admin'||a.u.employeeStatus==='verified')return '';return a.u.employeeStatus==='rejected'?'认证未通过，请输入你自己的正确工号后联系管理员重新核验。':'工号正在等待认证，请联系 00931664 进行认证。认证通过后才能进入大厅。';}
function syncWalletFromGame(st){if(!st||hasBot(st))return;const seats=['blackjack','poker'].includes(st.kind)?st.seats:[];for(const seat of seats||[]){if(!seat||seat.isBot||isBotId(seat.userId))continue;const u=data.users[seat.userId];if(!u)continue;if(st.kind==='poker'&&Number.isFinite(Number(seat.buyIn))&&Number.isFinite(Number(seat.walletAtBuyIn))){u.chips=Math.max(0,Number(seat.walletAtBuyIn)+(Number(seat.chips)||0)-Number(seat.buyIn));}else u.chips=Math.max(0,Number(seat.chips)||0);u.chipsUpdatedAt=Date.now();}}
function auth(userId,deviceId,deviceToken,req=null,deviceInfo=null){const u=data.users[String(userId||'')],d=data.devices[String(deviceId||'')];if(!u||!d||d.userId!==u.userId||!deviceTokenOk(d,deviceToken))return null;if(req)diagnostics.identify(req,u,d);touchDevice(d,u,req,deviceInfo);return {u,d}}
function friendRel(a,b){return data.friendships.find(f=>((f.a===a&&f.b===b)||(f.a===b&&f.b===a))&&f.state!=='removed')}
const progression=createProgressionService({data,body,auth,json,isStaff,publicUser,refreshWallet,save,friendRel});
const leisure=createLeisureService({data,crypto,body,auth,json,isStaff,publicUser,refreshWallet,save,progression});
function onlineInfo(u){const online=userIsOnline(u.userId);return {online,lastSeenAt:u.lastSeenAt||0,currentSection:online?(u.currentSection||''):null,currentRoomId:online?(u.currentRoomId||''):null}}
function social(userId){return socialPayload(data,userId,publicUser,onlineInfo,dmUnreadCount,dmUnreadSummary)}
function roomData(id){const def=ROOM_MAP[id];if(!def)return null;if(!data.roomMessages[id])data.roomMessages[id]=[];if(def.category==='music'&&!data.roomMusic[id])data.roomMusic[id]={provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',updatedAt:0,duration:0,positionMs:0,playing:false,revision:0,queue:[]};if(def.game&&!def.single){const gs=data.roomGames[id];const stale=!gs||gs.kind!==def.game||(['gomoku','xiangqi','chess'].includes(def.game)&&(!Array.isArray(gs.ready)||typeof gs.started!=='boolean'));if(stale)data.roomGames[id]=roomInitialState(def).game;}return def}
function roomClients(roomId){return [...clients].filter(c=>c.roomId===roomId&&!c.closed)}
function roomUserIds(roomId){purgeRoomPollers();const ids=new Set(roomClients(roomId).map(c=>c.userId));for(const x of roomPollers.values())if(x.roomId===roomId)ids.add(x.userId);return ids}
function roomHasUser(roomId,userId){return roomUserIds(roomId).has(userId)}
function roomPublicUsers(roomId){const vc=roomClients(roomId);return [...roomUserIds(roomId)].map(id=>data.users[id]).filter(Boolean).map(u=>({...publicUser(u),online:true,voiceOn:vc.some(c=>c.userId===u.userId&&c.voiceOn),voiceSpeaking:vc.some(c=>c.userId===u.userId&&c.voiceOn&&c.voiceSpeaking)}))}
function occupancy(){purgeRoomPollers();return ROOM_DEFS.map(r=>({...r,online:roomUserIds(r.id).size,entryFee:r.game?gameEntryFee(r.game):0}))}
function roomSnapshot(roomId,userId){const r=roomData(roomId);if(!r)return null;const users=roomPublicUsers(roomId),u=data.users[userId],m=data.roomMessages[roomId]||[];if(u&&!users.some(x=>x.userId===userId))users.push({...publicUser(u),online:true,voiceOn:false,voiceSpeaking:false});return {room:r,profile:publicUser(u),users,messages:m.slice(-24),chatHasMore:r.category==='chat'&&m.length>24,music:data.roomMusic[roomId]||null,game:r.game&&!r.single?publicGameState(data.roomGames[roomId],userId):null,serverNow:Date.now(),revision:roomChanges.revision(roomId)}}
function gameHumanIds(st){const ids=new Set;if(!st)return [];if(Array.isArray(st.players))for(const x of st.players)if(x&&!isBotId(x))ids.add(x);if(Array.isArray(st.seats))for(const x of st.seats||[]){if(x?.forfeitUserId)ids.add(x.forfeitUserId);else if(x&&!x.isBot&&!isBotId(x.userId))ids.add(x.userId)}for(const x of Object.keys(st.forfeitUsers||{}))if(data.users[x])ids.add(x);return [...ids]}
function gameHumanCount(st){return gameHumanIds(st).length}
function gameLiveHumanIds(st){const ids=new Set;if(!st)return [];if(Array.isArray(st.players))for(const x of st.players)if(x&&!isBotId(x))ids.add(x);if(Array.isArray(st.seats))for(const x of st.seats||[])if(x&&!x.isBot&&!isBotId(x.userId))ids.add(x.userId);return [...ids]}
function gameLiveHumanCount(st){return gameLiveHumanIds(st).length}
function gameBotCount(st){if(!st)return 0;if(Array.isArray(st.players))return st.players.filter(isBotId).length;if(Array.isArray(st.seats))return st.seats.filter(x=>x&&(x.isBot||isBotId(x.userId))).length;return 0}
function chargeRoundEntryFee(st,roomId){const ids=gameHumanIds(st),mode=ids.length>=2?'human':'ai',fee=gameEntryFee(st.kind,mode);if(!fee||!ids.length)return {fee:0,mode};const wallets={};for(const uid of ids){const u=data.users[uid];if(!u)continue;wallets[uid]=refreshWallet(u);if(wallets[uid]<fee)throw Error(`${u.name||'玩家'} 筹码不足：${mode==='ai'?'AI练习':'真人对局'}每局费用为 ${fee}`)}const deltas={};for(const uid of ids){const u=data.users[uid];if(!u)continue;u.chips=Math.max(0,wallets[uid]-fee);u.chipsUpdatedAt=Date.now();deltas[uid]=-fee}if(mode==='human'&&st.kind==='blackjack'){for(const p of st.seats||[])if(p&&!p.isBot&&!isBotId(p.userId)&&deltas[p.userId])p.chips=Math.max(0,(Number(p.chips)||0)-fee)}if(mode==='human'&&st.kind==='poker'){for(const p of st.seats||[])if(p&&!p.isBot&&!isBotId(p.userId)&&deltas[p.userId])p.walletAtBuyIn=Math.max(0,(Number(p.walletAtBuyIn)||0)-fee)}logChipSettlement(roomId,st.kind,deltas,`${mode==='ai'?'AI练习':'真人对局'}每局入场费 -${fee}`);return {fee,mode}}
function gameRankMode(st){return gameHumanCount(st)>=2?'human':'ai'}
function gameIsActive(st){if(!st)return false;if(['gomoku','xiangqi','chess','go'].includes(st.kind))return !!st.started&&!st.winner&&!st.result;if(st.kind==='dice')return st.phase==='playing';if(st.kind==='blackjack')return ['insurance','playing','dealer'].includes(st.phase);if(st.kind==='poker')return ['preflop','flop','turn','river','run_choice'].includes(st.phase);if(st.kind==='doudizhu')return ['bidding','playing'].includes(st.phase);return ['uno','mahjong'].includes(st.kind)&&['playing','reaction'].includes(st.phase)}
function markForfeit(st,userId){if(!st||!userId)return;st.forfeitUsers||={};st.forfeitUsers[userId]=Date.now()}
function isCompletedPlacementExit(st,userId){if(st?.kind!=='uno')return false;const p=(st.seats||[]).find(x=>x?.userId===userId);return !!p?.finished}
function recordImmediateForfeit(st,userId){if(!st||!userId||['gomoku','xiangqi','chess','go'].includes(st.kind)||!data.users[userId])return;st.forfeitRanked||={};if(st.forfeitRanked[userId])return;rankingOutcome(st,userId,'loss','human');st.forfeitRanked[userId]=Date.now();scheduleSave()}
function resetGameRoom(roomId,reason=''){const def=ROOM_MAP[roomId];if(!def?.game||def.single)return false;const bt=botTurnTimers?.get?.(roomId);if(bt){clearTimeout(bt);botTurnTimers.delete(roomId)}data.roomGames[roomId]=createGame(def.game);applyEconomyToGameState(data.roomGames[roomId]);if(reason)console.log(`[ROOM RESET] ${roomId}: ${reason}`);scheduleSave();sendGame(roomId);return true}
function enforceHumanAiGuard(roomId){const st=data.roomGames[roomId];if(!st)return false;if(gameBotCount(st)>0&&gameLiveHumanCount(st)===0)return resetGameRoom(roomId,'AI-only table blocked');return false}
function clearMusicRoom(roomId){const ms=data.roomMusic[roomId];if(!ms)return false;if(!ms.trackId&&!(ms.queue||[]).length)return false;data.roomMusic[roomId]={provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',updatedAt:0,duration:0,positionMs:0,playing:false,revision:0,queue:[]};broadcast(roomId,{type:'music_state',music:data.roomMusic[roomId]});scheduleSave();return true}
function clearGameChatIfEmpty(roomId){const def=ROOM_MAP[roomId];if(def?.category!=='game'||roomUserIds(roomId).size>0)return false;const arr=data.roomMessages[roomId]||[];if(!arr.length)return false;data.roomMessages[roomId]=[];scheduleSave();return true}
function isStaff(u){return u&&['owner','admin'].includes(u.role)}
const chatService=createChatService({data,crypto,clean,isStaff,scheduleSave,broadcast,onChat:u=>progression.noteChat(u)});
const chatState=CCS({data,ROOM_MAP,body,auth,json,scheduleSave});
const {RANKED_KINDS,emptyRank,normalizeRankRecord,rankingOutcome,originalSeatUser,logChipSettlement,recordGameResult,repairRankings,leaderboardPayload,settleZeroSum,transferChips}=createRankingService({data,crypto,isBotId,refreshWallet,gameRankMode,gameHumanIds,gameChipRule,scheduleSave,hasBot,publicUser});
const hLb=createLeaderboardHttp({body,auth,json,verifiedOnly,limitUser,leaderboardPayload});
const {mergeUsers}=createUserMergeService({data,refreshWallet,RANKED_KINDS,normalizeRankRecord,clients,save});
const musicService=createMusicService({clean,proxyMode,qqCookieForUser,neteaseCookieForUser,qqUin,sha,json});
const {searchNetease,searchQQ,probeQQAudio,proxyQQAudio,probeNeteaseAudio,findPublicMusicFallback,proxyNeteaseAudio,clearProviderCache}=musicService;
const handleMusicHttp=createMusicHttpRoutes({passiveSession,json,limitUser,clean,proxyQQAudio,proxyNeteaseAudio,probeQQAudio,probeNeteaseAudio,searchQQ,searchNetease,findPublicMusicFallback});
function dmKey(a,b){return [String(a),String(b)].sort().join('|')}
function directMessages(a,b){const f=friendRel(a,b);if(!f||f.state!=='accepted')throw Error('只有好友之间可以私聊');return data.directMessages[dmKey(a,b)]||=[]}
function dmReadMap(userId){data.directMessageReads||={};return data.directMessageReads[userId]||(data.directMessageReads[userId]={})}
function dmUnreadCount(userId,otherId){const readAt=Number(dmReadMap(userId)[otherId]||0),arr=data.directMessages[dmKey(userId,otherId)]||[];return arr.filter(m=>m.to===userId&&Number(m.at||0)>readAt).length}
function dmUnreadSummary(userId){const byUser={};let total=0;for(const f of data.friendships||[]){if(f.state!=='accepted'||(f.a!==userId&&f.b!==userId))continue;const other=f.a===userId?f.b:f.a,n=dmUnreadCount(userId,other);if(n){byUser[other]=n;total+=n}}return {total,byUser}}
function markDmRead(userId,otherId){const arr=data.directMessages[dmKey(userId,otherId)]||[],last=Math.max(0,...arr.filter(m=>m.to===userId).map(m=>Number(m.at)||0));if(last>Number(dmReadMap(userId)[otherId]||0)){dmReadMap(userId)[otherId]=last;scheduleSave()}return dmUnreadSummary(userId)}
function channelNotificationPayload(u,since=0){const items=[];for(const roomId of u.followedChannels||[]){const def=ROOM_MAP[roomId];if(!def)continue;for(const m of data.roomMessages[roomId]||[])if((m.at||0)>since&&m.userId!==u.userId)items.push({...m,roomId,roomName:def.name})}items.sort((x,y)=>x.at-y.at);return {now:Date.now(),items:items.slice(-30)}}
const handleNetworkSync=createNetworkSync({body,auth,json,limitUser,applyPresenceUpdate,publicUser,dmUnreadSummary,notificationPayload:channelNotificationPayload,data,onlineInfo,social,isStaff,diagnostics,userIsOnline,roomPollers,activeTabs,clients,dataFile:DATA_FILE,trustProxy:TRUST_PROXY,trustedProxyIps:TRUSTED_PROXY_IPS,publicOrigin:PUBLIC_ORIGIN});
const handleHttpRoomTransport=createHttpRoomTransport({body,auth,json,limitUser,verifiedOnly,roomData,roomPollTouch,cancelDisconnectedSeatCleanup,schedulePresenceSave,roomChanges,roomSnapshot,clean,actionSeen,message,rememberAction,tabTouch,roomPollDrop,roomHasUser,scheduleDisconnectedSeatCleanup,clearGameChatIfEmpty,diagnostics,validateRoomMessage});
const serveStatic=createStaticService({publicDir:PUBLIC,contentType,applySecurityHeaders,version:VERSION});
const server=http.createServer(async(req,res)=>{try{
applySecurityHeaders(res);const url=new URL(req.url,`http://${req.headers.host||'localhost'}`),diagReq=diagnostics.beginRequest(req,url.pathname);res.once('finish',()=>diagReq.finish(res.statusCode));if(url.pathname.startsWith('/api/')){const cl=Number(req.headers['content-length']||0);if(Number.isFinite(cl)&&cl>65536)return json(res,413,{ok:false,error:'请求体过大'});if(req.method==='POST'&&!/^application\/json(?:;|$)/i.test(String(req.headers['content-type']||'')))return json(res,415,{ok:false,error:'API 仅接受 application/json'});}
if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,app:APP,version:VERSION});
if(req.method==='POST'&&url.pathname==='/api/voice/config'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});return json(res,200,{ok:true,iceServers:voiceIceServersFromEnv()});}
if(url.pathname.startsWith('/api/progression/')||url.pathname==='/api/profile-card'){if(await progression.handle(req,res,url))return}
if(url.pathname.startsWith('/api/leisure/')){if(await leisure.handle(req,res,url))return}
if(req.method==='POST'&&url.pathname==='/api/game/entry'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const kind=clean(b.kind,24),fee=gameEntryFee(kind,'ai'),wallet=refreshWallet(a.u);if(wallet<fee)return json(res,400,{ok:false,error:`筹码不足：本游戏每局费用为 ${fee}`});if(fee){a.u.chips=wallet-fee;a.u.chipsUpdatedAt=Date.now();logChipSettlement(`single:${kind}`,kind,{[a.u.userId]:-fee},`单机 / AI 每局费用 -${fee}`);save()}return json(res,200,{ok:true,fee,profile:publicUser(a.u)});}
if(req.method==='GET'&&url.pathname==='/api/session'){const x=restoreByCookie(req,res);return x?json(res,200,x):json(res,401,{ok:false,error:'没有可恢复的设备会话'});}
if(req.method==='POST'&&url.pathname==='/api/origin-transfer/start'){
const b=await body(req);let a=null;if(b?.userId&&b?.deviceId&&b?.deviceToken)a=auth(b.userId,b.deviceId,b.deviceToken,req,b.deviceInfo);if(!a)a=passiveSession(req);if(!a)return json(res,401,{ok:false,error:'旧入口没有可迁移的设备身份'});if(b.deviceInfo)applyDeviceMeta(a.d,req,b.deviceInfo);const raw=token(),h=sha(`origin-transfer:${raw}`);originTransfers.set(h,{userId:a.u.userId,deviceId:a.d.deviceId,clientInstallId:clean(b?.deviceInfo?.installId||'',128),exp:Date.now()+2*60*1000});if(originTransfers.size>256)for(const [k,x] of originTransfers)if(x.exp<Date.now())originTransfers.delete(k);return json(res,200,{ok:true,transferToken:raw,deviceId:a.d.deviceId,publicOrigin:PUBLIC_ORIGIN});
}
if(req.method==='POST'&&url.pathname==='/api/origin-transfer/redeem'){
const b=await body(req),h=sha(`origin-transfer:${String(b.transferToken||'')}`),x=originTransfers.get(h);originTransfers.delete(h);if(!x||x.exp<Date.now())return json(res,401,{ok:false,error:'设备迁移令牌无效或已过期'});const d=data.devices[x.deviceId],u=d&&data.users[x.userId];if(!d||!u||d.userId!==u.userId)return json(res,401,{ok:false,error:'原设备身份已经不存在'});const deviceToken=token();addDeviceToken(d,deviceToken);touchDevice(d,u,req);issueRecoveryCookie(d,res);return json(res,200,{ok:true,userId:u.userId,deviceId:d.deviceId,deviceToken,profile:publicUser(u),employeeMasked:u.employeeMasked||'未绑定',deviceLabel:d.label||'设备',social:social(u.userId),clientInstallId:x.clientInstallId||''});
}
if(req.method==='GET'&&url.pathname==='/api/rooms')return json(res,200,{ok:true,rooms:occupancy()});
if(await handleMusicHttp(req,res,url))return;
if(await hLb(req,res,url))return;
if(req.method==='POST'&&url.pathname==='/api/users/presence'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const gate=verifiedOnly(a);if(gate)return json(res,403,{ok:false,error:gate});const users=Object.values(data.users).map(u=>({...publicUser(u),...onlineInfo(u)}));return json(res,200,{ok:true,users});}
if(req.method==='POST'&&url.pathname==='/api/wallet/checkin'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const gate=verifiedOnly(a);if(gate)return json(res,403,{ok:false,error:gate});refreshWallet(a.u);const day=dailyKey();if(a.u.lastChipCheckinDay===day)return json(res,409,{ok:false,error:'今天已经签到领取过筹码'});a.u.chips=Math.max(0,Number(a.u.chips)||0)+chipDailyReward();a.u.lastChipCheckinDay=day;a.u.chipsUpdatedAt=Date.now();save();return json(res,200,{ok:true,profile:publicUser(a.u),reward:chipDailyReward()});}
if(req.method==='GET'&&url.pathname==='/api/network/info'){if(!directLoopbackOnly(req))return json(res,403,{ok:false,error:'仅限直接 localhost'});const addresses=[];for(const [name,list] of Object.entries(os.networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)addresses.push({name,address:n.address,netmask:n.netmask});return json(res,200,{ok:true,port:PORT,addresses,proxyMode:proxyMode(),trustProxy:TRUST_PROXY,trustedProxyIps:TRUSTED_PROXY_IPS||'',pacDetected:!!process.env.SLIMELOUNGE_PROXY_PAC});}
if(url.pathname.startsWith('/api/local-admin/')){if(!directLoopbackOnly(req))return json(res,403,{ok:false,error:'仅限直接 localhost'});if(req.method==='GET'&&url.pathname==='/api/local-admin/users')return json(res,200,{ok:true,ownerUserId:data.ownerUserId,users:localUserRows(),dataFile:DATA_FILE});if(req.method==='POST'&&url.pathname==='/api/local-admin/create-owner-recovery'){try{return json(res,200,{ok:true,...createOwnerRecoveryCode('server-console')})}catch(e){return json(res,400,{ok:false,error:e.message})}}if(req.method==='POST'&&url.pathname==='/api/local-admin/owner-session'){const x=bindLocalOwnerDevice('服务器本机 · 自动 Owner');if(!x)return json(res,404,{ok:false,error:'服务器尚未设置 Owner，请先在本机身份管理中指定一次'});issueRecoveryCookie(data.devices[x.deviceId],res);return json(res,200,x);}const b=await body(req);if(req.method==='POST'&&url.pathname==='/api/local-admin/bind'){const u=data.users[String(b.targetUserId||'')];if(!u)return json(res,404,{ok:false,error:'身份不存在'});const out=issueUserDevice(u,clean(b.deviceLabel,32)||'本机恢复设备',req,res,{deviceInfo:b.deviceInfo||{},existingDeviceId:b.existingDeviceId||''});save();return json(res,200,out);}if(req.method==='POST'&&url.pathname==='/api/local-admin/claim-owner'){const u=data.users[String(b.targetUserId||'')];if(!u)return json(res,404,{ok:false,error:'身份不存在'});for(const x of Object.values(data.users))if(x.role==='owner'&&x.userId!==u.userId)x.role='member';u.role='owner';u.employeeStatus='verified';u.updatedAt=Date.now();data.ownerUserId=u.userId;save();broadcastAll({type:'profile_update',profile:publicUser(u)});return json(res,200,{ok:true,ownerUserId:u.userId,profile:publicUser(u)});}if(req.method==='POST'&&url.pathname==='/api/local-admin/merge'){try{const target=mergeUsers(String(b.sourceUserId||''),String(b.targetUserId||''));return json(res,200,{ok:true,profile:publicUser(target),ownerUserId:data.ownerUserId})}catch(e){return json(res,400,{ok:false,error:e.message})}}return json(res,404,{ok:false,error:'未知本机管理操作'});}
if(req.method==='POST'&&url.pathname==='/api/device-link/redeem'){if(!rateLimit(req,'device-link-redeem',24,10*60*1000))return json(res,429,{ok:false,error:'绑定码尝试过于频繁'});const b=await body(req);const codeKey=sha(`device-link:${String(b.code||'')}`).slice(0,24);if(!rateLimitSubject(`redeem:${codeKey}`,'device-link-code',8,10*60*1000))return json(res,429,{ok:false,error:'该绑定码尝试次数过多'});try{return json(res,200,redeemDeviceLink(b.code,b.deviceLabel,req,res,{existingDeviceId:b.existingDeviceId||'',deviceInfo:b.deviceInfo||{}}))}catch(e){return json(res,400,{ok:false,error:e.message})}}
if(req.method==='POST'&&url.pathname==='/api/music/account'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const provider=b.provider==='qq'?'qq':'netease';data.musicAccounts||={};data.qqMusicAccounts||={};const pub=()=>provider==='qq'?qqAccountPublic(a.u.userId):neteaseAccountPublic(a.u.userId);
if(b.action==='status')return json(res,200,{ok:true,provider,account:pub()});
if(b.action==='unlink'){if(provider==='qq'){delete data.qqMusicAccounts[a.u.userId];clearProviderCache('qq')}else{delete data.musicAccounts[a.u.userId];clearProviderCache('netease')}save();return json(res,200,{ok:true,provider,account:{linked:false}})}
if(b.action==='save'){
if(provider==='qq'){const ck=normalizeQQCookie(b.cookie);if(!ck)return json(res,400,{ok:false,error:'没有识别到 QQ 音乐登录 Cookie。请登录 y.qq.com 后按页面说明复制 Cookie，至少包含 uin/wxuin 与 qm_keyst 或 qqmusic_key。'});data.qqMusicAccounts[a.u.userId]={sealed:sealSecret(ck),label:'个人 QQ 音乐 Cookie',updatedAt:Date.now()};clearProviderCache('qq')}
else{const ck=normalizeNeteaseCookie(b.cookie);if(!ck)return json(res,400,{ok:false,error:'没有识别到 MUSIC_U。请登录网易云网页版后按页面说明复制 MUSIC_U 值或包含 MUSIC_U 的 Cookie。'});data.musicAccounts[a.u.userId]={sealed:sealSecret(ck),label:'个人网易云 Cookie',updatedAt:Date.now()};clearProviderCache('netease')}
save();return json(res,200,{ok:true,provider,account:pub()})
}
return json(res,400,{ok:false,error:'未知音乐账号操作'});
}
if(req.method==='POST'&&url.pathname==='/api/device-link/create'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});try{return json(res,200,{ok:true,...createDeviceLink(a.u.userId)})}catch(e){return json(res,400,{ok:false,error:e.message})}}
if(req.method==='POST'&&url.pathname==='/api/owner/recover'){
if(!rateLimit(req,'owner-recover',12,15*60*1000))return json(res,429,{ok:false,error:'Owner 恢复尝试过于频繁'});const b=await body(req);try{return json(res,200,recoverOwnerDevice(b.employeeId,b.recoveryCode,b.deviceLabel,req,res,{existingDeviceId:b.existingDeviceId||'',deviceInfo:b.deviceInfo||{}}))}catch(e){return json(res,403,{ok:false,error:e.message})}
}
if(req.method==='POST'&&url.pathname==='/api/register'){
const b=await body(req),name=clean(b.name,16),emp=normalizeEmployee(b.employeeId),slimeColor=SLIME_COLORS.has(b.slimeColor)?b.slimeColor:'mint';if(!rateLimit(req,'register-hard',120,15*60*1000)){diagnostics.noteRateLimit(req,'register-hard','ip');return json(res,429,{ok:false,error:'注册过于频繁，请稍后再试'})}if(!name)return json(res,400,{ok:false,error:'请输入昵称'});if(!validEmployee(emp))return json(res,400,{ok:false,error:'工号仅接受 6~9 位字母或数字'});const eh=secretHash(emp);if(!rateLimitSubject(`employee:${eh}`,'register',6,15*60*1000)){diagnostics.noteRateLimit(req,'register','employee');return json(res,429,{ok:false,error:'该工号注册尝试过于频繁，请稍后再试'})}if(data.employeeIndex[eh])return json(res,409,{ok:false,error:'该工号已有账号，请使用设备恢复码恢复原账号。'});
const now=Date.now(),userId=crypto.randomUUID(),isFirst=Object.keys(data.users).length===0,configuredOwner=normalizeEmployee(process.env.OWNER_EMPLOYEE_ID||''),ownerClaim=!data.ownerUserId&&(configuredOwner?emp===configuredOwner:isFirst),u={userId,loungeId:makeLoungeId(),name,slimeColor,bio:'',role:ownerClaim?'owner':'member',employeeHash:eh,employeeId:emp,employeeMasked:maskEmployee(emp),employeeStatus:ownerClaim?'verified':'pending',presenceStatus:'online',manualPresenceStatus:'online',activityLabel:'',followedChannels:['chat-announcements'],statusMessage:'',lastSeenAt:now,currentSection:'chat',currentRoomId:'',chips:chipFloor(),chipsUpdatedAt:now,lastChipCheckinDay:'',createdAt:now,updatedAt:now};progression.initializeUser(u);data.users[userId]=u;if(ownerClaim)data.ownerUserId=userId;data.employeeIndex[eh]=userId;const out=issueUserDevice(u,clean(b.deviceLabel,32)||'当前设备',req,res,{deviceInfo:b.deviceInfo||{}});save();return json(res,201,out);
}
if(req.method==='POST'&&url.pathname==='/api/auth'){
const b=await body(req);if(!rateLimit(req,'auth-hard',600,5*60*1000)){diagnostics.noteRateLimit(req,'auth-hard','ip');return json(res,429,{ok:false,error:'登录过于频繁，请稍后再试'})}const ident=sha(`${b.userId||''}|${b.deviceId||''}`).slice(0,24);if(!rateLimitSubject(`device:${ident}`,'auth',30,5*60*1000)){diagnostics.noteRateLimit(req,'auth','device');return json(res,429,{ok:false,error:'这台设备登录尝试过于频繁，请稍后再试'})}const a=auth(b.userId,b.deviceId,b.deviceToken,req,b.deviceInfo);if(!a)return json(res,401,{ok:false,error:'身份无效'});tabTouch(a.u.userId,b.tabId);ensureRecoveryCookie(a.d,req,res);return json(res,200,{ok:true,profile:publicUser(a.u),employeeMasked:a.u.employeeMasked,deviceLabel:a.d.label,social:social(a.u.userId)});
}
if(await handleNetworkSync(req,res,url))return;
if(await chatState.handle(req,res,url))return;
if(req.method==='POST'&&url.pathname==='/api/presence/offline'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,200,{ok:true});const tid=clean(b.tabId,96),pollRooms=[...new Set([...roomPollers.values()].filter(x=>x.userId===a.u.userId&&(!tid||x.tabId===tid)).map(x=>x.roomId))];tabDrop(a.u.userId,tid);roomPollDrop(a.u.userId,'',tid);for(const roomId of pollRooms){if(!roomHasUser(roomId,a.u.userId))scheduleDisconnectedSeatCleanup(a.u.userId,roomId);clearGameChatIfEmpty(roomId)}for(const c of [...clients])if(c.userId===a.u.userId&&(!tid||c.tabId===tid)){try{c.socket.end()}catch{}remove(c)}if(!userIsOnline(a.u.userId)){a.u.presenceStatus='offline';a.u.activityLabel='';a.u.currentRoomId='';a.u.currentSection='';a.u.lastSeenAt=Date.now();scheduleSave();broadcastAll({type:'profile_update',profile:{...publicUser(a.u),online:false}});}return json(res,200,{ok:true});
}
if(req.method==='POST'&&url.pathname==='/api/profile'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const name=clean(b.name,16);if(!name)return json(res,400,{ok:false,error:'昵称不能为空'});a.u.name=name;a.u.bio=clean(b.bio,80);a.u.statusMessage=clean(b.statusMessage,48);if(['online','busy','away'].includes(b.presenceStatus)){a.u.manualPresenceStatus=b.presenceStatus;a.u.presenceStatus=b.presenceStatus;}if(SLIME_COLORS.has(b.slimeColor))a.u.slimeColor=b.slimeColor;a.u.updatedAt=Date.now();a.u.lastSeenAt=Date.now();save();broadcastAll({type:'profile_update',profile:publicUser(a.u)});return json(res,200,{ok:true,profile:publicUser(a.u)});
}
if(req.method==='POST'&&url.pathname==='/api/employee/change'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const emp=normalizeEmployee(b.employeeId);if(!validEmployee(emp))return json(res,400,{ok:false,error:'工号仅接受 6~9 位字母或数字'});const nh=secretHash(emp),owner=data.employeeIndex[nh];if(owner&&owner!==a.u.userId)return json(res,409,{ok:false,error:'该工号已被其他身份占用，请联系管理员处理冲突'});if(a.u.role==='owner'){const old=a.u.employeeHash;delete data.employeeIndex[old];data.employeeIndex[nh]=a.u.userId;a.u.employeeHash=nh;a.u.employeeId=emp;a.u.employeeMasked=maskEmployee(emp);a.u.employeeStatus='verified';data.employeeHistory.push({userId:a.u.userId,oldHash:old,newHash:nh,changedAt:Date.now(),approvedBy:a.u.userId});save();return json(res,200,{ok:true,employeeMasked:a.u.employeeMasked,employeeStatus:'verified'});}const reqId=crypto.randomUUID();data.employeeChangeRequests=data.employeeChangeRequests.filter(x=>x.userId!==a.u.userId||x.state!=='pending');data.employeeChangeRequests.push({id:reqId,userId:a.u.userId,newHash:nh,newEmployeeId:emp,newMasked:maskEmployee(emp),state:'pending',createdAt:Date.now()});save();return json(res,202,{ok:true,pending:true,error:'工号变更已提交，等待管理员核验'});
}
if(req.method==='POST'&&url.pathname==='/api/chat/follows'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});return json(res,200,{ok:true,followedChannels:a.u.followedChannels||[]});
}
if(req.method==='POST'&&url.pathname==='/api/chat/follow'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const roomId=String(b.roomId||'');if(ROOM_MAP[roomId]?.category!=='chat')return json(res,400,{ok:false,error:'不是聊天频道'});const set=new Set(a.u.followedChannels||[]);b.follow===false?set.delete(roomId):set.add(roomId);a.u.followedChannels=[...set];save();return json(res,200,{ok:true,followedChannels:a.u.followedChannels});
}
if(req.method==='POST'&&url.pathname==='/api/chat/notifications'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const n=channelNotificationPayload(a.u,Math.max(0,Number(b.since)||0));return json(res,200,{ok:true,...n});
}
if(await handleHttpRoomTransport(req,res,url))return;
if(req.method==='POST'&&url.pathname==='/api/admin/owner-recovery'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||a.u.userId!==data.ownerUserId||a.u.role!=='owner')return json(res,403,{ok:false,error:'只有唯一 Owner 可以生成恢复码'});try{return json(res,200,{ok:true,...createOwnerRecoveryCode(a.u.userId)})}catch(e){return json(res,400,{ok:false,error:e.message})}
}
if(req.method==='POST'&&url.pathname==='/api/admin/chips'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||!isStaff(a.u))return json(res,403,{ok:false,error:'无管理权限'});const action=String(b.action||'get');
data.economy=normalizeEconomy(data.economy||{});
if(action==='get')return json(res,200,{ok:true,economy:data.economy,defaults:{chipFloor:chipFloor(),chipRecoverMs:chipRecoverMs(),dailyReward:chipDailyReward(),recoverPerHour:chipRecoverPerHour()}});
if(action==='set_rules'){data.economy=normalizeEconomy({chipFloor:b.chipFloor,recoverPerHour:b.recoverPerHour,dailyReward:b.dailyReward,gameRules:b.gameRules,updatedAt:Date.now(),updatedBy:a.u.userId});for(const st of Object.values(data.roomGames||{}))if(st&&!gameIsActive(st))applyEconomyToGameState(st);save();return json(res,200,{ok:true,economy:data.economy});}
if(action==='set_user'){const target=data.users[String(b.targetUserId||'')];if(!target)return json(res,404,{ok:false,error:'用户不存在'});for(const st of Object.values(data.roomGames||{})){if(!st||!['blackjack','poker'].includes(st.kind)||!gameIsActive(st))continue;if((st.seats||[]).some(p=>originalSeatUser(p)===target.userId))return json(res,409,{ok:false,error:'该玩家正在进行 21 点/德州扑克，请本手结束后再修改筹码'});}refreshWallet(target);const before=Math.floor(Number(target.chips)||0),next=boundedInt(b.chips,0,1000000000,before);target.chips=next;target.chipsUpdatedAt=Date.now();for(const st of Object.values(data.roomGames||{})){if(!st||!['blackjack','poker'].includes(st.kind))continue;for(const p of st.seats||[])if(p&&originalSeatUser(p)===target.userId){p.chips=next;if(st.practiceSnapshot&&st.practiceSnapshot[target.userId]!=null)st.practiceSnapshot[target.userId]=next;}}logChipSettlement('ADMIN','admin',{[target.userId]:next-before},`管理员手动修改筹码 ${before} → ${next} · ${a.u.loungeId||a.u.name}`);save();broadcastAll({type:'profile_update',profile:publicUser(target)});return json(res,200,{ok:true,profile:publicUser(target),before,after:next});}
return json(res,400,{ok:false,error:'未知筹码管理操作'});
}
if(req.method==='POST'&&url.pathname==='/api/admin/rankings/repair'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||!isStaff(a.u))return json(res,403,{ok:false,error:'无管理权限'});const report=repairRankings();save();return json(res,200,{ok:true,report,leaderboards:leaderboardPayload()})}
if(req.method==='POST'&&url.pathname==='/api/admin/rankings/set'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||!isStaff(a.u))return json(res,403,{ok:false,error:'无管理权限'});const kind=String(b.kind||''),mode=b.mode==='ai'?'ai':'human';if(!RANKED_KINDS.includes(kind))return json(res,400,{ok:false,error:'未知排行榜游戏'});if(b.action==='reset_kind'){if(a.u.role!=='owner')return json(res,403,{ok:false,error:'只有 Owner 可以清空整个游戏榜'});data.rankings[kind]={};save();return json(res,200,{ok:true,leaderboards:leaderboardPayload()})}const loungeId=clean(b.loungeId,16).toUpperCase(),target=Object.values(data.users).find(u=>String(u.loungeId||'').toUpperCase()===loungeId);if(!target)return json(res,404,{ok:false,error:'没有找到该 Lounge ID'});const wins=Math.max(0,Math.floor(Number(b.wins)||0)),losses=Math.max(0,Math.floor(Number(b.losses)||0)),draws=Math.max(0,Math.floor(Number(b.draws)||0)),games=wins+losses+draws;data.rankings[kind]||={};const rec=data.rankings[kind][target.userId]=normalizeRankRecord(data.rankings[kind][target.userId]);if(!games)rec[mode]=emptyRank();else rec[mode]={games,wins,losses,draws,updatedAt:Date.now(),manualCorrectedAt:Date.now(),manualCorrectedBy:a.u.userId};save();return json(res,200,{ok:true,leaderboards:leaderboardPayload()})}
if(req.method==='POST'&&url.pathname==='/api/admin/users'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||!isStaff(a.u))return json(res,403,{ok:false,error:'无管理权限'});const users=Object.values(data.users).map(u=>{const devices=Object.values(data.devices).filter(d=>d.userId===u.userId).map(devicePublic).sort((a,b)=>(b.lastSeenAt||0)-(a.lastSeenAt||0));return {...publicUser(u),...onlineInfo(u),employeeId:u.employeeId||'',employeeMasked:u.employeeMasked||'',deviceCount:devices.length,devices}}).sort((x,y)=>{const pri=u=>u.employeeStatus!=='verified'?0:u.online&&['trading','fishing'].includes(u.presenceStatus)?1:u.online&&u.presenceStatus==='gaming'?2:u.online&&u.presenceStatus==='listening'?3:u.online&&['online','voice'].includes(u.presenceStatus)?4:u.online&&u.presenceStatus==='busy'?5:u.online&&u.presenceStatus==='away'?6:7,px=pri(x),py=pri(y);if(px!==py)return px-py;if(px>=5)return (y.lastSeenAt||0)-(x.lastSeenAt||0)||(x.createdAt||0)-(y.createdAt||0);return (x.createdAt||0)-(y.createdAt||0)});return json(res,200,{ok:true,ownerUserId:data.ownerUserId,users,employeeRequests:data.employeeChangeRequests.filter(x=>x.state==='pending').map(x=>({...x,user:publicUser(data.users[x.userId]||{})}))});
}
if(req.method==='POST'&&url.pathname==='/api/admin/role'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||a.u.userId!==data.ownerUserId||a.u.role!=='owner')return json(res,403,{ok:false,error:'只有唯一 Owner 可以调整管理员'});const target=data.users[String(b.targetUserId||'')];if(!target||target.userId===a.u.userId)return json(res,400,{ok:false,error:'目标用户无效'});const role=b.role==='admin'?'admin':'member';if(target.role==='owner'||target.userId===data.ownerUserId)return json(res,403,{ok:false,error:'不能修改 Owner'});target.role=role;target.updatedAt=Date.now();save();broadcastAll({type:'profile_update',profile:publicUser(target)});return json(res,200,{ok:true,profile:publicUser(target)});
}
if(req.method==='POST'&&url.pathname==='/api/admin/employee'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||!isStaff(a.u))return json(res,403,{ok:false,error:'无管理权限'});const action=String(b.action||'');if(action==='verify'){const target=data.users[String(b.targetUserId||'')];if(!target)return json(res,404,{ok:false,error:'用户不存在'});target.employeeStatus='verified';target.updatedAt=Date.now();save();return json(res,200,{ok:true});}if(action==='reject'){const target=data.users[String(b.targetUserId||'')];if(!target||target.role==='owner')return json(res,400,{ok:false,error:'目标无效'});if(target.employeeHash)delete data.employeeIndex[target.employeeHash];target.employeeHash=null;target.employeeId='';target.employeeMasked='未绑定';target.employeeStatus='rejected';target.updatedAt=Date.now();save();return json(res,200,{ok:true});}if(action==='approve_change'){const r=data.employeeChangeRequests.find(x=>x.id===b.requestId&&x.state==='pending');if(!r)return json(res,404,{ok:false,error:'变更申请不存在'});const target=data.users[r.userId];if(!target)return json(res,404,{ok:false,error:'用户不存在'});const conflict=data.employeeIndex[r.newHash];if(conflict&&conflict!==target.userId)return json(res,409,{ok:false,error:'新工号已被其他身份占用'});if(target.employeeHash)delete data.employeeIndex[target.employeeHash];data.employeeIndex[r.newHash]=target.userId;target.employeeHash=r.newHash;target.employeeId=r.newEmployeeId||'';target.employeeMasked=r.newMasked;target.employeeStatus='verified';r.state='approved';r.approvedBy=a.u.userId;r.updatedAt=Date.now();save();return json(res,200,{ok:true});}if(action==='reject_change'){const r=data.employeeChangeRequests.find(x=>x.id===b.requestId&&x.state==='pending');if(!r)return json(res,404,{ok:false,error:'变更申请不存在'});r.state='rejected';r.approvedBy=a.u.userId;r.updatedAt=Date.now();save();return json(res,200,{ok:true});}if(action==='release_conflict'){const emp=normalizeEmployee(b.employeeId);if(!validEmployee(emp))return json(res,400,{ok:false,error:'工号格式无效'});const h=secretHash(emp),uid=data.employeeIndex[h],target=data.users[uid];if(!target)return json(res,404,{ok:false,error:'该工号当前未被占用'});if(target.role==='owner')return json(res,403,{ok:false,error:'不能释放 Owner 工号'});delete data.employeeIndex[h];target.employeeHash=null;target.employeeId='';target.employeeMasked='未绑定';target.employeeStatus='rejected';target.updatedAt=Date.now();save();return json(res,200,{ok:true,releasedUserId:uid});}return json(res,400,{ok:false,error:'未知管理员工号操作'});
}
if(req.method==='POST'&&url.pathname==='/api/admin/manage'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a||!isStaff(a.u))return json(res,403,{ok:false,error:'无管理权限'});const action=String(b.action||''),target=data.users[String(b.targetUserId||'')];
if(action==='update_user'){if(!target)return json(res,404,{ok:false,error:'用户不存在'});const name=clean(b.name,16);if(name)target.name=name;if(typeof b.employeeId==='string'){const emp=normalizeEmployee(b.employeeId);if(emp){if(!validEmployee(emp))return json(res,400,{ok:false,error:'工号格式无效'});const h=secretHash(emp),occupied=data.employeeIndex[h];if(occupied&&occupied!==target.userId)return json(res,409,{ok:false,error:'该工号已绑定到其他身份'});if(target.employeeHash&&data.employeeIndex[target.employeeHash]===target.userId)delete data.employeeIndex[target.employeeHash];target.employeeId=emp;target.employeeHash=h;target.employeeMasked=maskEmployee(emp);data.employeeIndex[h]=target.userId}else{if(target.role==='owner')return json(res,403,{ok:false,error:'不能清空 Owner 工号'});if(target.employeeHash&&data.employeeIndex[target.employeeHash]===target.userId)delete data.employeeIndex[target.employeeHash];target.employeeId='';target.employeeHash=null;target.employeeMasked='未绑定'}}if(['pending','verified','rejected'].includes(b.employeeStatus))target.employeeStatus=b.employeeStatus;if(a.u.role==='owner'&&target.role!=='owner'&&['member','admin'].includes(b.role))target.role=b.role;target.updatedAt=Date.now();save();broadcastAll({type:'profile_update',profile:publicUser(target)});return json(res,200,{ok:true});}
if(action==='create_device_recovery'){const d=data.devices[String(b.targetDeviceId||'')];if(!d||d.userId!==String(b.targetUserId||''))return json(res,404,{ok:false,error:'设备不存在'});try{return json(res,200,{ok:true,...createDeviceLink(d.userId,d.deviceId)})}catch(e){return json(res,400,{ok:false,error:e.message})}}
if(action==='update_device'){const d=data.devices[String(b.targetDeviceId||'')];if(!d||d.userId!==String(b.targetUserId||''))return json(res,404,{ok:false,error:'设备不存在'});d.label=clean(b.label,32)||d.label||'设备';scheduleSave();return json(res,200,{ok:true});}
if(action==='delete_device'){const d=data.devices[String(b.targetDeviceId||'')];if(!d||d.userId!==String(b.targetUserId||''))return json(res,404,{ok:false,error:'设备不存在'});if(d.deviceId===a.d.deviceId)return json(res,400,{ok:false,error:'不能在当前会话中删除正在使用的管理设备'});if(d.userId===data.ownerUserId&&a.u.role!=='owner')return json(res,403,{ok:false,error:'只有 Owner 可以删除 Owner 的设备'});delete data.devices[d.deviceId];save();return json(res,200,{ok:true});}
if(action==='merge_user'){if(a.u.role!=='owner')return json(res,403,{ok:false,error:'只有 Owner 可以合并账号'});const sourceId=String(b.sourceUserId||''),targetId=String(b.targetUserId||'');if(sourceId===a.u.userId)return json(res,400,{ok:false,error:'不能把当前 Owner 作为源账号合并'});try{mergeUsers(sourceId,targetId);return json(res,200,{ok:true,ownerUserId:data.ownerUserId})}catch(e){return json(res,400,{ok:false,error:e.message})}}
if(action==='delete_user'){if(a.u.role!=='owner')return json(res,403,{ok:false,error:'仅 Owner 可删除账号'});if(!target)return json(res,404,{ok:false,error:'用户不存在'});if(target.userId===a.u.userId||target.role==='owner'||target.userId===data.ownerUserId)return json(res,403,{ok:false,error:'不能删除当前唯一 Owner'});for(const c of [...clients])if(c.userId===target.userId){try{c.socket.end()}catch{}remove(c)}for(const [id,d] of Object.entries(data.devices))if(d.userId===target.userId)delete data.devices[id];if(target.employeeHash&&data.employeeIndex[target.employeeHash]===target.userId)delete data.employeeIndex[target.employeeHash];data.friendships=data.friendships.filter(f=>f.a!==target.userId&&f.b!==target.userId);for(const k of Object.keys(data.directMessages||{}))if(k.split('|').includes(target.userId))delete data.directMessages[k];delete data.directMessageReads?.[target.userId];for(const mp of Object.values(data.directMessageReads||{}))if(mp)delete mp[target.userId];data.employeeChangeRequests=data.employeeChangeRequests.filter(r=>r.userId!==target.userId);for(const ranks of Object.values(data.rankings||{}))if(ranks&&typeof ranks==='object')delete ranks[target.userId];for(const [roomId,st] of Object.entries(data.roomGames||{})){try{applyGameAction(st,target.userId,{type:'leave'});sendGame(roomId)}catch{}}delete data.users[target.userId];save();return json(res,200,{ok:true});}
return json(res,400,{ok:false,error:'未知管理操作'});
}
if(req.method==='POST'&&url.pathname==='/api/social/unread'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});return json(res,200,{ok:true,unread:dmUnreadSummary(a.u.userId)})}
if(req.method==='POST'&&url.pathname==='/api/social/messages'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const other=String(b.otherUserId||'');try{const arr=directMessages(a.u.userId,other),since=Math.max(0,Number(b.since)||0),unread=markDmRead(a.u.userId,other);return json(res,200,{ok:true,other:publicUser(data.users[other]),messages:arr.filter(m=>(m.at||0)>=since).slice(-200),now:Date.now(),unread})}catch(e){return json(res,400,{ok:false,error:e.message})}}
if(req.method==='POST'&&url.pathname==='/api/social/send'){const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const other=String(b.otherUserId||''),text=clean(b.text,500);if(!text)return json(res,400,{ok:false,error:'消息不能为空'});try{const arr=directMessages(a.u.userId,other),m={id:crypto.randomUUID(),from:a.u.userId,to:other,text,at:Date.now()};arr.push(m);if(arr.length>500)arr.splice(0,arr.length-500);save();return json(res,200,{ok:true,message:m})}catch(e){return json(res,400,{ok:false,error:e.message})}}
if(req.method==='POST'&&url.pathname==='/api/social/search'){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const id=clean(b.loungeId,16).toUpperCase(),u=Object.values(data.users).find(x=>x.loungeId===id);if(!u)return json(res,404,{ok:false,error:'没有找到该 Lounge ID'});return json(res,200,{ok:true,profile:publicUser(u),relation:friendRel(a.u.userId,u.userId)?.state||'none'});
}
if(req.method==='POST'&&url.pathname.startsWith('/api/social/')){
const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'});const me=a.u.userId;
if(url.pathname==='/api/social/list')return json(res,200,{ok:true,social:social(me)});
if(url.pathname==='/api/social/request'){const other=String(b.otherUserId||'');if(!data.users[other]||other===me)return json(res,400,{ok:false,error:'用户无效'});let f=friendRel(me,other);if(f){if(f.state==='pending'&&f.b===me){f.state='accepted';f.updatedAt=Date.now();save();return json(res,200,{ok:true,social:social(me)})}return json(res,409,{ok:false,error:'关系已存在'})}data.friendships.push({a:me,b:other,state:'pending',createdAt:Date.now(),updatedAt:Date.now()});save();return json(res,200,{ok:true,social:social(me)});}
if(url.pathname==='/api/social/respond'){const other=String(b.otherUserId||''),f=friendRel(me,other);if(!f||f.state!=='pending'||f.b!==me)return json(res,404,{ok:false,error:'申请不存在'});f.state=b.accept?'accepted':'removed';f.updatedAt=Date.now();save();return json(res,200,{ok:true,social:social(me)});}
if(url.pathname==='/api/social/remark'){const other=String(b.otherUserId||''),f=friendRel(me,other);if(!f||f.state!=='accepted')return json(res,404,{ok:false,error:'好友不存在'});f.remarks||={};const r=clean(b.remark,24);if(r)f.remarks[me]=r;else delete f.remarks[me];f.updatedAt=Date.now();save();return json(res,200,{ok:true,social:social(me)});}
if(url.pathname==='/api/social/remove'){const other=String(b.otherUserId||''),f=friendRel(me,other);if(!f||f.state!=='accepted')return json(res,404,{ok:false,error:'好友不存在'});f.state='removed';f.updatedAt=Date.now();save();return json(res,200,{ok:true,social:social(me)});}
}
if(url.pathname.startsWith('/api/'))return json(res,404,{ok:false,error:'Not found'});
const migrationAsset=url.pathname==='/origin-migrate.html'||url.pathname==='/origin-migrate.js';
const canonical=migrationAsset?'':canonicalRedirectTarget(req,url);if(canonical){const hop=`/origin-migrate.html?to=${encodeURIComponent(canonical)}`;res.writeHead(307,{location:hop,'cache-control':'no-store'});return res.end()}
serveStatic(req,res,url);
}catch(e){console.error(e);const status=Number(e?.statusCode)||500;if(!res.headersSent)json(res,status,{ok:false,error:status>=500?'server error':(e.message||'请求无效')});else res.end()}});
function wsAccept(k){return crypto.createHash('sha1').update(k+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64')}
function frame(text,opcode=1){const p=Buffer.from(text),l=p.length;let h;if(l<126){h=Buffer.alloc(2);h[1]=l}else if(l<65536){h=Buffer.alloc(4);h[1]=126;h.writeUInt16BE(l,2)}else{h=Buffer.alloc(10);h[1]=127;h.writeBigUInt64BE(BigInt(l),2)}h[0]=0x80|opcode;return Buffer.concat([h,p])}
function send(c,o){if(!c.closed&&!c.socket.destroyed)try{c.socket.write(frame(JSON.stringify(o)))}catch{}}
function broadcast(roomId,o,except=null){roomChanges.touch(roomId);for(const c of clients)if(c.roomId===roomId&&c!==except)send(c,o)}
function broadcastAll(o){for(const c of clients)send(c,o)}
function sendGame(roomId){const st=data.roomGames[roomId];roomChanges.touch(roomId);for(const c of roomClients(roomId))send(c,{type:'game_state',state:publicGameState(st,c.userId)});scheduleSave()}
const unreadySeatTimers=new Map();
const UNREADY_SEAT_MS=Math.max(0,Number(process.env.SLIMELOUNGE_UNREADY_SEAT_MS||0));
function gameSeatState(st,userId){if(!st)return null;if(Array.isArray(st.players)){const i=st.players.indexOf(userId);return i<0?null:{ready:!!st.ready?.[i],active:!!st.started}}const i=(st.seats||[]).findIndex(x=>x?.userId===userId),p=i>=0?st.seats[i]:null;return !p?null:{ready:!!p.ready,active:['playing','dealer','insurance','preflop','flop','turn','river','run_choice','reaction','bidding'].includes(st.phase)}}
function clearUnreadySeatTimer(roomId,userId){const k=roomId+'|'+userId,t=unreadySeatTimers.get(k);if(t){clearTimeout(t);unreadySeatTimers.delete(k)}}
function scheduleUnreadySeatTimer(roomId,userId){clearUnreadySeatTimer(roomId,userId);const k=roomId+'|'+userId,delay=unreadySeatDelayMs(data.roomGames[roomId],UNREADY_SEAT_MS);unreadySeatTimers.set(k,setTimeout(()=>{unreadySeatTimers.delete(k);const st=data.roomGames[roomId],ss=gameSeatState(st,userId);if(!ss||ss.ready||ss.active)return;try{applyGameAction(st,userId,{type:'leave'});sendGame(roomId);scheduleSave();for(const c of roomClients(roomId))if(c.userId===userId)send(c,{type:'error',error:`入座 ${Math.round(delay/1000)} 秒仍未准备，已自动离席`});}catch{}},delay))}
const botTurnTimers=new Map();
function botThinkDelay(st){return ['xiangqi','chess'].includes(st?.kind)?420:['gomoku','go'].includes(st?.kind)?300:['mahjong','uno'].includes(st?.kind)?850:520}
function scheduleBotTurn(roomId,delay=null){const st=data.roomGames[roomId];if(!st||!hasBot(st))return;const prev=botTurnTimers.get(roomId);if(prev)return;const timer=setTimeout(()=>{botTurnTimers.delete(roomId);try{const cur=data.roomGames[roomId];if(!cur||enforceHumanAiGuard(roomId))return;const before=JSON.parse(JSON.stringify(cur)),sig=JSON.stringify(cur);advanceBots(cur,1);if(JSON.stringify(cur)===sig)return;if(enforceHumanAiGuard(roomId))return;syncWalletFromGame(cur);recordGameResult(roomId,before,cur);sendGame(roomId);scheduleBotTurn(roomId)}catch(e){console.error('[BOT TURN]',roomId,e?.stack||e);for(const c of roomClients(roomId))send(c,{type:'error',error:'AI 回合执行异常，服务器已保留连接；请重试当前操作'})}},delay??botThinkDelay(st));botTurnTimers.set(roomId,timer)}
function cleanupDisconnectedSeat(userId,roomId){
const key=disconnectKey(userId,roomId);disconnectTimers.delete(key);clearUnreadySeatTimer(roomId,userId);
if(roomHasUser(roomId,userId))return;
const def=ROOM_MAP[roomId],u=data.users[userId];
if(def?.game){
const st=data.roomGames[roomId];
if(st){
try{
const before=JSON.parse(JSON.stringify(st)),active=gameIsActive(st),humans=gameHumanCount(st),seated=!!gameSeatState(st,userId),cleanPlacementExit=isCompletedPlacementExit(st,userId),practiceAbandon=active&&seated&&humans<2&&!cleanPlacementExit,pvpForfeit=active&&seated&&humans>=2&&!cleanPlacementExit;
try{applyGameAction(st,userId,{type:'leave'})}catch{}
if(pvpForfeit&&!['gomoku','xiangqi','chess','go'].includes(st.kind)){markForfeit(st,userId);recordImmediateForfeit(st,userId)}
if(practiceAbandon){resetGameRoom(roomId,'single-human AI practice disconnected');return}
if(!enforceHumanAiGuard(roomId)){recordGameResult(roomId,before,st);sendGame(roomId);scheduleBotTurn(roomId);}
}catch(e){console.warn('[ROOM CLEANUP]',roomId,userId,e.message)}
}
}
if(u&&u.currentRoomId===roomId){u.currentRoomId='';u.currentSection='';u.lastSeenAt=Date.now();scheduleSave()}
}
function scheduleDisconnectedSeatCleanup(userId,roomId){
const key=disconnectKey(userId,roomId);clearTimeout(disconnectTimers.get(key));
const delay=disconnectedSeatDelayMs(data.roomGames[roomId],DISCONNECT_GRACE_MS);disconnectTimers.set(key,setTimeout(()=>cleanupDisconnectedSeat(userId,roomId),delay));
}
function cancelDisconnectedSeatCleanup(userId,roomId){const key=disconnectKey(userId,roomId),t=disconnectTimers.get(key);if(t){clearTimeout(t);disconnectTimers.delete(key)}}
function remove(c){if(c.closed)return;c.closed=true;clearTimeout(c.authTimer);clients.delete(c);if(c.countedWs)diagnostics.wsClosed();if(!c.userId||!c.roomId)return;const u=data.users[c.userId],d=data.devices[c.deviceId||''];diagnostics.clientEvent(c.req,u,d,'ws-close','WebSocket 连接关闭',{roomId:c.roomId,transport:'websocket'});if(u){u.lastSeenAt=Date.now();if(!userIsOnline(u.userId)){u.presenceStatus='offline';u.activityLabel='';u.currentRoomId='';u.currentSection='';}scheduleSave();}if(!roomHasUser(c.roomId,c.userId))scheduleDisconnectedSeatCleanup(c.userId,c.roomId);broadcast(c.roomId,{type:'presence',users:roomPublicUsers(c.roomId)});clearGameChatIfEmpty(c.roomId);if(u&&!userIsOnline(u.userId))broadcastAll({type:'profile_update',profile:{...publicUser(u),online:false}});}
const authenticateWsClient=createWsSessionAuth({rateLimitSubject,diagnostics,auth,verifiedOnly,roomData,clean,clients,roomPollDrop,cancelDisconnectedSeatCleanup,tabTouch,schedulePresenceSave,send,data,publicUser,roomPublicUsers,publicGameState,roomRevision:roomId=>roomChanges.revision(roomId),broadcast});
function parse(c,chunk){if(c.buf.length+chunk.length>131072){try{c.socket.destroy()}catch{};return}c.buf=Buffer.concat([c.buf,chunk]);while(c.buf.length>=2){let b0=c.buf[0],b1=c.buf[1],op=b0&15,len=b1&127,off=2;if(len===126){if(c.buf.length<4)return;len=c.buf.readUInt16BE(2);off=4}else if(len===127){if(c.buf.length<10)return;len=Number(c.buf.readBigUInt64BE(2));off=10}if(len>65536||!(b1&128)){try{c.socket.destroy()}catch{};return}let mask;if(b1&128){if(c.buf.length<off+4)return;mask=c.buf.subarray(off,off+4);off+=4}if(c.buf.length<off+len)return;let p=Buffer.from(c.buf.subarray(off,off+len));c.buf=c.buf.subarray(off+len);if(mask)for(let i=0;i<p.length;i++)p[i]^=mask[i%4];if(op===8){remove(c);try{c.socket.write(frame(p,8),()=>c.socket.end())}catch{try{c.socket.destroy()}catch{}}return}if(op===9){try{c.socket.write(frame(p,10))}catch{}continue}if(op===1)message(c,p.toString())}}
function message(c,raw,throwErrors=false){if(raw.length>16384){if(throwErrors)throw Error('房间操作数据过大');return}const now=Date.now();c.msgTimes=(c.msgTimes||[]).filter(x=>now-x<10000);if(c.msgTimes.length>=120){if(throwErrors)throw Error('操作过于频繁');return}c.msgTimes.push(now);let m;try{m=JSON.parse(raw);validateRoomMessage(m,{allowAuth:c.awaitingAuth})}catch(e){if(throwErrors)throw e;send(c,{type:'error',error:e.message||'输入参数无效'});return}
if(c.awaitingAuth){authenticateWsClient(c,m);return}
const def=ROOM_MAP[c.roomId],u=data.users[c.userId];try{
if(m.type==='heartbeat'){if(u){u.lastSeenAt=Date.now();tabTouch(u.userId,c.tabId);schedulePresenceSave(u.userId);}send(c,{type:'heartbeat_ack',at:Date.now(),clientAt:Number(m.clientAt)||0});return}
if(chatService.handle(c,m,def,u,now))return
if((m.type==='music_set'||m.type==='music_add')&&def.category==='music'){const provider=m.provider==='qq'?'qq':'netease',raw=String(m.trackId||''),id=provider==='qq'?raw.match(/^[A-Za-z0-9]{6,32}$/)?.[0]:raw.match(/^\d{3,20}$/)?.[0];if(!id)throw Error(provider==='qq'?'QQ音乐歌曲 MID 无效':'歌曲 ID 无效');const mediaId=provider==='qq'?(String(m.mediaId||id).match(/^[A-Za-z0-9]{6,32}$/)?.[0]||id):'';const ms=data.roomMusic[c.roomId]||(data.roomMusic[c.roomId]={provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',updatedAt:0,duration:0,positionMs:0,playing:false,revision:0,queue:[]});ms.queue=Array.isArray(ms.queue)?ms.queue:[];const cover=/^https?:\/\//i.test(String(m.cover||''))?clean(m.cover,300):'';const item={provider,trackId:id,mediaId,title:clean(m.title,80)||`${provider==='qq'?'QQ音乐':'网易云'}歌曲 ${id}`,setBy:u.name,cover,duration:Math.max(0,Number(m.duration)||0),queuedAt:Date.now()};if(!ms.trackId){Object.assign(ms,item,{positionMs:0,playing:true,updatedAt:Date.now(),revision:(ms.revision||0)+1});}else ms.queue.push(item);scheduleSave();broadcast(c.roomId,{type:'music_state',music:ms});return}
if(m.type==='music_control'&&def.category==='music'){const ms=data.roomMusic[c.roomId];if(!ms?.trackId||String(ms.trackId)!==String(m.trackId||ms.trackId))return;const now=Date.now(),elapsed=ms.playing?Math.max(0,now-(ms.updatedAt||now)):0,current=Math.max(0,Number(ms.positionMs)||0)+elapsed,duration=Math.max(0,Number(ms.duration)||0),clampPos=v=>Math.max(0,duration?Math.min(Number(v)||0,duration):Number(v)||0);if(m.action==='seek')ms.positionMs=clampPos(m.positionMs);else ms.positionMs=clampPos(current);if(m.action==='play')ms.playing=true;else if(m.action==='pause')ms.playing=false;else if(m.action!=='seek')return;ms.updatedAt=now;ms.revision=(ms.revision||0)+1;scheduleSave();broadcast(c.roomId,{type:'music_state',music:ms});return}
if(m.type==='music_ended'&&def.category==='music'){const ms=data.roomMusic[c.roomId];if(!ms||String(ms.trackId||'')!==String(m.trackId||''))return;const next=(ms.queue||[]).shift();if(next)Object.assign(ms,next,{positionMs:0,playing:true,updatedAt:Date.now(),revision:(ms.revision||0)+1});else Object.assign(ms,{provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',duration:0,positionMs:0,playing:false,updatedAt:Date.now(),revision:(ms.revision||0)+1});scheduleSave();broadcast(c.roomId,{type:'music_state',music:ms});return}
if(m.type==='voice_toggle'&&(def.category==='game'||def.voiceAllowed)){c.voiceOn=!!m.enabled;if(!c.voiceOn)c.voiceSpeaking=false;if(u&&def.category==='chat'&&def.voiceAllowed){u.presenceStatus=c.voiceOn?'voice':(u.manualPresenceStatus||'online');u.activityLabel=c.voiceOn?`语音中 · ${def.name}`:'';u.lastSeenAt=Date.now();scheduleSave();broadcastAll({type:'profile_update',profile:{...publicUser(u),online:true}})}broadcast(c.roomId,{type:'presence',users:roomPublicUsers(c.roomId)});return}
if(m.type==='voice_activity'&&(def.category==='game'||def.voiceAllowed)){const speaking=!!m.speaking&&c.voiceOn;if(c.voiceSpeaking!==speaking){c.voiceSpeaking=speaking;broadcast(c.roomId,{type:'presence',users:roomPublicUsers(c.roomId)})}return}
if(m.type==='voice_signal'&&(def.category==='game'||def.voiceAllowed)){const target=String(m.target||'');if(!target||target===c.userId||!m.signal||typeof m.signal!=='object')return;for(const peer of roomClients(c.roomId))if(peer.userId===target)send(peer,{type:'voice_signal',from:c.userId,signal:m.signal});return}
if(m.type==='game_action'&&def.game){
const actionId=clean(m.clientActionId,96);if(actionSeen(c.userId,c.roomId,actionId)){send(c,{type:'action_ack',actionId,duplicate:true});return}
const st=data.roomGames[c.roomId],before=JSON.parse(JSON.stringify(st)),a={...(m.action||{})},activeBefore=gameIsActive(st);
if(!activeBefore&&['join','ready','start','reset','rematch','bet','pair_bet','boxes'].includes(a.type))applyEconomyToGameState(st);
if(a.type==='start'||a.type==='rematch'){st.forfeitUsers={};st.forfeitRanked={}}
const humansBefore=gameHumanCount(st),seatedBefore=!!gameSeatState(st,c.userId),cleanPlacementExit=a.type==='leave'&&isCompletedPlacementExit(st,c.userId),practiceAbandon=a.type==='leave'&&activeBefore&&seatedBefore&&humansBefore<2&&!cleanPlacementExit,pvpForfeit=a.type==='leave'&&activeBefore&&seatedBefore&&humansBefore>=2&&!cleanPlacementExit;
if(a.type==='join'&&['blackjack','poker'].includes(st.kind)){const wallet=refreshWallet(u);if(st.kind==='blackjack')a.chips=wallet;else{const bb=Math.max(1,Number(st.bigBlind)||20),standardMin=Math.max(bb*20,bb*2),minBuyIn=Math.min(wallet,standardMin),defaultBuyIn=Math.min(wallet,Math.max(Number(st.defaultStack)||chipFloor(),bb*100));if(wallet<bb*2)throw Error(`筹码不足，德州至少需要 ${bb*2} 筹码才能入座`);const requested=Math.floor(Number(a.chips));if(!Number.isFinite(requested))a.chips=defaultBuyIn;else if(requested<minBuyIn||requested>wallet)throw Error(`本桌可带入 ${minBuyIn} ～ ${wallet} 筹码`);else a.chips=requested;a.walletAtBuyIn=wallet;}}
if(a.type==='add_bot'){if(gameLiveHumanCount(st)<1)throw Error('请先有真人入座');addBotToGame(st,Number.isInteger(a.seat)?a.seat:null)}else if(a.type==='remove_bot')removeBotFromGame(st,Number.isInteger(a.seat)?a.seat:null);else applyGameAction(st,c.userId,a);
if(!activeBefore&&gameIsActive(st)){try{chargeRoundEntryFee(st,c.roomId)}catch(err){data.roomGames[c.roomId]=before;applyEconomyToGameState(data.roomGames[c.roomId]);throw err}snapshotChipRule(st)}
if(actionId)rememberAction(c.userId,c.roomId,actionId);
if(pvpForfeit&&!['gomoku','xiangqi','chess','go'].includes(st.kind)){markForfeit(st,c.userId);recordImmediateForfeit(st,c.userId)}
if(practiceAbandon){resetGameRoom(c.roomId,'single-human AI practice abandoned');return}
if(a.type==='join'){const ss=gameSeatState(st,c.userId);if(ss&&!ss.ready&&!ss.active)scheduleUnreadySeatTimer(c.roomId,c.userId)}else if(a.type==='ready'){const ss=gameSeatState(st,c.userId);if(!ss||ss.ready||ss.active)clearUnreadySeatTimer(c.roomId,c.userId);else scheduleUnreadySeatTimer(c.roomId,c.userId)}else if(['leave','start','rematch'].includes(a.type))clearUnreadySeatTimer(c.roomId,c.userId);
if(enforceHumanAiGuard(c.roomId))return;syncWalletFromGame(st);recordGameResult(c.roomId,before,st);if(progression.recordGameFinish(before,st))scheduleSave();sendGame(c.roomId);scheduleBotTurn(c.roomId);if(actionId)send(c,{type:'action_ack',actionId});return
}
}catch(e){if(throwErrors)throw e;send(c,{type:'error',error:e.message})}}
const handleWsUpgrade=createWsTransport({sameOriginWs,rateLimit,diagnostics,wsAccept,parse,remove});
server.on('upgrade',handleWsUpgrade);
const gameTickTimer=setInterval(()=>{const now=Date.now();purgeRoomPollers();purgeTabs();for(const def of ROOM_DEFS){if(!def.game)continue;try{const st=data.roomGames[def.id];if(!st)continue;if(roomUserIds(def.id).size===0){clearGameChatIfEmpty(def.id);if(gameBotCount(st)>0||gameHumanCount(st)>0){resetGameRoom(def.id,'room empty');continue}}if(enforceHumanAiGuard(def.id))continue;const before=JSON.parse(JSON.stringify(st)),r=tickGame(st,now);if(r.changed){if(enforceHumanAiGuard(def.id))continue;syncWalletFromGame(st);recordGameResult(def.id,before,st);if(progression.recordGameFinish(before,st))scheduleSave();for(const uid of r.forceLeaveUsers||[]){for(const c of roomClients(def.id))if(c.userId===uid)send(c,{type:'force_leave',reason:'操作超时，已移出房间'});}sendGame(def.id);scheduleBotTurn(def.id);}if(r.autoReset&&st.finishedAt&&now-st.finishedAt>=resultCleanupDelayMs(st)){const sec=Math.round(resultCleanupDelayMs(st)/1000);for(const c of roomClients(def.id))send(c,{type:'force_leave',reason:`本局结束 ${sec} 秒，房间已整理`});resetGameRoom(def.id,'result timeout');}}catch(e){console.error('[GAME TICK]',def.id,e?.stack||e)}}for(const def of ROOM_DEFS){if(def.category!=='music')continue;const online=roomUserIds(def.id).size;if(online===0){clearMusicRoom(def.id);continue}const ms=data.roomMusic[def.id];if(!ms||!ms.trackId||!ms.duration)continue;const current=(Number(ms.positionMs)||0)+(ms.playing?Math.max(0,now-(ms.updatedAt||now)):0);if(ms.playing&&current>=ms.duration){const next=(ms.queue||[]).shift();if(next)Object.assign(ms,next,{positionMs:0,playing:true,updatedAt:now,revision:(ms.revision||0)+1});else Object.assign(ms,{provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',duration:0,positionMs:0,playing:false,updatedAt:now,revision:(ms.revision||0)+1});broadcast(def.id,{type:'music_state',music:ms});scheduleSave();}}},500);
server.on('error',e=>{console.error(e);process.exitCode=1});server.keepAliveTimeout=65000;server.headersTimeout=70000;server.listen(PORT,HOST,()=>{const url=`http://localhost:${PORT}`;console.log(`${APP} v${VERSION} · ${url} · data=${DATA_FILE} · proxy=${TRUST_PROXY?'on':'off'}`);setTimeout(()=>openBrowser(url),250)});process.on('SIGINT',()=>{clearInterval(gameTickTimer);roomChanges.cancelAll();diagnostics.stop();try{save()}catch{}process.exit(0)});
