const clone=x=>JSON.parse(JSON.stringify(x));
const int=(v,d=0)=>{const n=Math.floor(Number(v));return Number.isFinite(n)?n:d};
const clamp=(v,a,b,d=a)=>Math.max(a,Math.min(b,int(v,d)));
const text=(v,n=80)=>String(v??'').trim().slice(0,n);
const bool=v=>v!==false&&v!=='false'&&v!==0&&v!=='0';

export const DEFAULT_PROGRESSION_CONFIG={
  version:9,
  account:{defaultLevel:1,defaultXp:0,levelXpBase:160,levelXpPerLevel:65,activityCooldownSec:55,chatMessageXp:2,chatMessageCooldownSec:20,chatMinuteXp:1,musicMinuteXp:3,gameMinuteXp:4,gameFinishXp:20,purchaseXp:2,petXpSharePct:65},
  pet:{defaultName:'小史莱姆',defaultLevel:1,defaultXp:0,defaultHunger:80,defaultMood:70,levelXpBase:100,levelXpPerLevel:40,hungerDecayPerHour:2,moodHungerThreshold:35,moodDecayPerHour:1,moodHungerPenaltyPerHour:2,badMoodThreshold:25,lowHungerXpPenaltyPct:20,badMoodXpPenaltyPct:20,chipPenaltyHungerThreshold:15,chipPenaltyMoodThreshold:15,lowHungerChipCostPerHour:40,badMoodChipCostPerHour:25,maxOfflineChipPenaltyHours:24,maxOfflineDecayHours:72,feedXp:4,playXp:6,playCooldownSec:300,playMoodGain:14,playHungerCost:5},
  shop:{
    accessories:[
      {id:'acc_bow',name:'小蝴蝶结',price:1800,slot:'head',desc:'像素蝴蝶结，可装备在头顶',enabled:true,asset:'/accessories/bow.svg',x:50,y:7,w:48,rotate:0,z:5,color:'#ff7fa2'},
      {id:'acc_leaf',name:'薄荷叶',price:2400,slot:'head',desc:'清爽的小叶子',enabled:true,asset:'/accessories/leaf.svg',x:60,y:7,w:34,rotate:8,z:5,color:'#6fd477'},
      {id:'acc_star',name:'星星发夹',price:3200,slot:'head',desc:'一颗像素小星星',enabled:true,asset:'/accessories/star.svg',x:64,y:16,w:30,rotate:8,z:6,color:'#ffd75d'},
      {id:'acc_glasses',name:'圆框眼镜',price:4200,slot:'face',desc:'真实叠加在史莱姆脸上的圆框眼镜',enabled:true,asset:'/accessories/glasses.svg',x:50,y:52,w:82,rotate:0,z:7,color:'#1c2944'},
      {id:'acc_scarf',name:'小围巾',price:5200,slot:'neck',desc:'围在史莱姆下沿的小围巾',enabled:true,asset:'/accessories/scarf.svg',x:50,y:82,w:80,rotate:0,z:6,color:'#d96583'},
      {id:'acc_flower',name:'像素小花',price:3800,slot:'head',desc:'别在史莱姆头侧的小花',enabled:true,asset:'/accessories/flower.svg',x:68,y:18,w:30,rotate:-8,z:6,color:'#ff83ad'},
      {id:'acc_crown',name:'小皇冠',price:6800,slot:'head',desc:'金色像素小皇冠',enabled:true,asset:'/accessories/crown.svg',x:50,y:4,w:46,rotate:0,z:6,color:'#f1c84c'},
      {id:'acc_headphones',name:'像素耳机',price:7600,slot:'face',desc:'包在史莱姆两侧的像素耳机',enabled:true,asset:'/accessories/headphones.svg',x:50,y:45,w:102,rotate:0,z:7,color:'#6278a8'},
      {id:'acc_partyhat',name:'庆典尖帽',price:5400,slot:'head',desc:'派对风格像素尖帽',enabled:true,asset:'/accessories/partyhat.svg',x:50,y:3,w:48,rotate:0,z:6,color:'#8f76df'},
      {id:'acc_horns',name:'恶魔小角',price:7200,slot:'head',desc:'一对俏皮的小尖角',enabled:true,asset:'/accessories/horns.svg',x:50,y:12,w:74,rotate:0,z:6,color:'#d45c77'},
      {id:'acc_blush',name:'害羞脸红',price:4600,slot:'face',desc:'脸颊两侧的像素红晕',enabled:true,asset:'/accessories/blush.svg',x:50,y:64,w:78,rotate:0,z:8,color:'#ff7891'},
      {id:'acc_monocle',name:'单片眼镜',price:8800,slot:'face',desc:'带链条的单片眼镜',enabled:true,asset:'/accessories/monocle.svg',x:58,y:51,w:60,rotate:0,z:8,color:'#d3b260'},
      {id:'acc_bowtie',name:'礼服领结',price:6200,slot:'neck',desc:'适合正式场合的小领结',enabled:true,asset:'/accessories/bowtie.svg',x:50,y:82,w:52,rotate:0,z:7,color:'#cb5472'},
      {id:'acc_bell',name:'月铃项圈',price:9600,slot:'neck',desc:'带小铃铛的像素项圈',enabled:true,asset:'/accessories/bell.svg',x:50,y:82,w:64,rotate:0,z:7,color:'#e0b349'},
      {id:'acc_halo',name:'史莱姆光环',price:12800,slot:'effect',desc:'漂浮在头顶的柔光环',enabled:true,asset:'/accessories/halo.svg',x:50,y:-2,w:70,rotate:0,z:4,color:'#ffe77a'},
      {id:'acc_sparkles',name:'闪闪星尘',price:14800,slot:'effect',desc:'环绕史莱姆的星尘特效',enabled:true,asset:'/accessories/sparkles.svg',x:50,y:48,w:120,rotate:0,z:9,color:'#9dd9ff'}
    ],
    food:[
      {id:'food_jelly',name:'果冻丁',price:180,hunger:18,mood:2,desc:'日常口粮',enabled:true},
      {id:'food_pudding',name:'布丁',price:360,hunger:32,mood:5,desc:'甜甜的布丁',enabled:true},
      {id:'food_starcake',name:'星星蛋糕',price:780,hunger:55,mood:12,desc:'适合庆祝升级',enabled:true},
      {id:'food_mint_mochi',name:'薄荷糯米团',price:620,hunger:38,mood:8,desc:'清凉软糯的日常零食',enabled:true},
      {id:'food_berry_soda',name:'莓果汽水',price:920,hunger:18,mood:18,desc:'饱腹一般，但很提心情',enabled:true},
      {id:'food_moon_cookie',name:'月亮曲奇',price:1450,hunger:48,mood:22,desc:'比较奢侈的高级零食',enabled:true}
    ],
    titles:[
      {id:'title_lounge_regular',name:'大厅常客',price:8000,desc:'展示在用户名旁边',enabled:true},
      {id:'title_music_lover',name:'耳机不离身',price:12000,desc:'听歌室风格头衔',enabled:true},
      {id:'title_game_night',name:'今晚开黑',price:12000,desc:'游戏室风格头衔',enabled:true},
      {id:'title_slime_keeper',name:'史莱姆饲养员',price:18000,desc:'宠物养成风格头衔',enabled:true},
      {id:'title_lake_angler',name:'湖畔钓手',price:16000,desc:'钓鱼玩法主题头衔',enabled:true},
      {id:'title_market_watcher',name:'行情观察员',price:16000,desc:'虚拟交易所主题头衔',enabled:true},
      {id:'title_table_regular',name:'牌桌常客',price:22000,desc:'多人游戏主题头衔',enabled:true},
      {id:'title_lounge_familiar',name:'频道熟面孔',price:24000,desc:'大厅常客的中阶聊天头衔',enabled:true},
      {id:'title_lounge_voice',name:'大厅话事人',price:52000,desc:'大厅常客的高阶聊天头衔',enabled:true},
      {id:'title_music_collector',name:'旋律收藏家',price:28000,desc:'耳机不离身的中阶音乐头衔',enabled:true},
      {id:'title_music_master',name:'音浪主理人',price:58000,desc:'耳机不离身的高阶音乐头衔',enabled:true},
      {id:'title_game_veteran',name:'百战玩家',price:30000,desc:'今晚开黑的中阶游戏头衔',enabled:true},
      {id:'title_game_master',name:'游戏大师',price:62000,desc:'今晚开黑的高阶游戏头衔',enabled:true},
      {id:'title_slime_butler',name:'史莱姆管家',price:36000,desc:'史莱姆饲养员的中阶宠物头衔',enabled:true},
      {id:'title_slime_breeder',name:'史莱姆培育大师',price:72000,desc:'史莱姆饲养员的高阶宠物头衔',enabled:true},
      {id:'title_lake_hunter',name:'深水猎手',price:34000,desc:'湖畔钓手的中阶钓鱼头衔',enabled:true},
      {id:'title_lake_legend',name:'传奇钓神',price:70000,desc:'湖畔钓手的高阶钓鱼头衔',enabled:true},
      {id:'title_market_trader',name:'趋势交易员',price:36000,desc:'行情观察员的中阶交易头衔',enabled:true},
      {id:'title_market_operator',name:'市场操盘手',price:76000,desc:'行情观察员的高阶交易头衔',enabled:true},
      {id:'title_table_veteran',name:'牌局老手',price:42000,desc:'牌桌常客的中阶牌局头衔',enabled:true},
      {id:'title_table_master',name:'牌桌宗师',price:82000,desc:'牌桌常客的高阶牌局头衔',enabled:true}
    ]
  },
  achievements:[
    {id:'first_chat',name:'初次发言',desc:'发送第一条聊天消息',counter:'chatMessages',goal:1,xp:20,enabled:true},
    {id:'chat_100',name:'聊得来',desc:'累计发送 100 条聊天消息',counter:'chatMessages',goal:100,xp:120,enabled:true},
    {id:'chat_500',name:'频道常驻',desc:'累计发送 500 条聊天消息',counter:'chatMessages',goal:500,xp:260,enabled:true},
    {id:'music_30',name:'听歌半小时',desc:'累计在听歌室活跃 30 分钟',counter:'musicMinutes',goal:30,xp:100,enabled:true},
    {id:'music_180',name:'循环播放',desc:'累计在听歌室活跃 180 分钟',counter:'musicMinutes',goal:180,xp:260,enabled:true},
    {id:'game_1',name:'第一次开局',desc:'完成第一局游戏',counter:'gamesFinished',goal:1,xp:40,enabled:true},
    {id:'game_20',name:'今晚开局',desc:'累计完成 20 局游戏',counter:'gamesFinished',goal:20,xp:180,enabled:true},
    {id:'game_100',name:'百局玩家',desc:'累计完成 100 局游戏',counter:'gamesFinished',goal:100,xp:420,enabled:true},
    {id:'friends_1',name:'第一位好友',desc:'拥有第一位好友',counter:'friends',goal:1,xp:30,enabled:true},
    {id:'friends_5',name:'五人成行',desc:'拥有 5 位好友',counter:'friends',goal:5,xp:100,enabled:true},
    {id:'friends_10',name:'小小社群',desc:'拥有 10 位好友',counter:'friends',goal:10,xp:180,enabled:true},
    {id:'shop_1',name:'第一次购物',desc:'在商城购买第一件商品',counter:'purchases',goal:1,xp:30,enabled:true},
    {id:'shop_5',name:'第一次剁手之后',desc:'累计购买 5 件商品',counter:'purchases',goal:5,xp:80,enabled:true},
    {id:'shop_20',name:'收藏柜满了',desc:'累计购买 20 件商品',counter:'purchases',goal:20,xp:200,enabled:true},
    {id:'pet_1',name:'第一次投喂',desc:'第一次给宠物喂食',counter:'petFeeds',goal:1,xp:30,enabled:true},
    {id:'pet_10',name:'投喂专家',desc:'累计投喂宠物 10 次',counter:'petFeeds',goal:10,xp:100,enabled:true},
    {id:'pet_50',name:'长期饭票',desc:'累计投喂宠物 50 次',counter:'petFeeds',goal:50,xp:260,enabled:true},
    {id:'level_5',name:'五级居民',desc:'账号等级达到 5 级',counter:'level',goal:5,xp:80,enabled:true},
    {id:'level_10',name:'十级居民',desc:'账号等级达到 10 级',counter:'level',goal:10,xp:200,enabled:true},
    {id:'level_20',name:'二十级居民',desc:'账号等级达到 20 级',counter:'level',goal:20,xp:400,enabled:true}
    ,{id:'fish_1',name:'第一竿',desc:'成功钓到第一条鱼',counter:'fishCaught',goal:1,xp:30,enabled:true}
    ,{id:'fish_25',name:'小小钓手',desc:'累计钓到 25 条鱼',counter:'fishCaught',goal:25,xp:160,enabled:true}
    ,{id:'fish_100',name:'钓鱼大师',desc:'累计钓到 100 条鱼',counter:'fishCaught',goal:100,xp:420,enabled:true}
    ,{id:'fish_legendary',name:'稀有上钩',desc:'钓到第一条传奇稀有鱼',counter:'fishLegendary',goal:1,xp:260,enabled:true}
    ,{id:'market_1',name:'第一次下单',desc:'完成第一笔虚拟市场交易',counter:'marketTrades',goal:1,xp:30,enabled:true}
    ,{id:'market_50',name:'行情观察员',desc:'累计完成 50 笔虚拟市场交易',counter:'marketTrades',goal:50,xp:220,enabled:true}
    ,{id:'market_profit',name:'落袋为安',desc:'累计实现 5000 筹码交易盈利',counter:'marketProfit',goal:5000,xp:360,enabled:true}
    ,{id:'fish_250',name:'湖边常客',desc:'累计钓到 250 条鱼',counter:'fishCaught',goal:250,xp:700,enabled:true}
    ,{id:'market_200',name:'长期观察',desc:'累计完成 200 笔虚拟市场交易',counter:'marketTrades',goal:200,xp:650,enabled:true}
    ,{id:'pet_100',name:'百次投喂',desc:'累计投喂宠物 100 次',counter:'petFeeds',goal:100,xp:620,enabled:true}
    ,{id:'game_300',name:'长期玩家',desc:'累计完成 300 局游戏',counter:'gamesFinished',goal:300,xp:900,enabled:true}
    ,{id:'checkin_streak_3',name:'三日不断',desc:'连续签到达到 3 天',counter:'checkinStreakMax',goal:3,xp:80,enabled:true}
    ,{id:'checkin_streak_7',name:'一周全勤',desc:'连续签到达到 7 天',counter:'checkinStreakMax',goal:7,xp:180,enabled:true}
    ,{id:'checkin_streak_30',name:'月度全勤',desc:'连续签到达到 30 天',counter:'checkinStreakMax',goal:30,xp:650,enabled:true}
    ,{id:'checkin_total_30',name:'签到熟客',desc:'累计签到 30 次',counter:'checkinTotal',goal:30,xp:260,enabled:true}
    ,{id:'checkin_total_100',name:'百日居民',desc:'累计签到 100 次',counter:'checkinTotal',goal:100,xp:900,enabled:true}
    ,{id:'market_batch_100',name:'整手成交',desc:'单笔交易份额达到 100',counter:'marketMaxTradeQty',goal:100,xp:100,enabled:true}
    ,{id:'market_batch_1000',name:'千股一单',desc:'单笔交易份额达到 1000',counter:'marketMaxTradeQty',goal:1000,xp:300,enabled:true}
    ,{id:'market_batch_10000',name:'大宗订单',desc:'单笔交易份额达到 10000',counter:'marketMaxTradeQty',goal:10000,xp:800,enabled:true}
    ,{id:'market_profit_20000',name:'稳健盈利',desc:'累计实现 20000 筹码交易盈利',counter:'marketProfit',goal:20000,xp:600,enabled:true}
    ,{id:'fish_500',name:'鱼篓专家',desc:'累计钓到 500 条鱼',counter:'fishCaught',goal:500,xp:1100,enabled:true}
    ,{id:'legendary_5',name:'传奇收藏家',desc:'累计钓到 5 条传奇鱼',counter:'fishLegendary',goal:5,xp:700,enabled:true}
    ,{id:'shop_50',name:'收藏家',desc:'累计购买 50 件商品',counter:'purchases',goal:50,xp:500,enabled:true}
    ,{id:'pet_250',name:'贴心饲主',desc:'累计投喂宠物 250 次',counter:'petFeeds',goal:250,xp:900,enabled:true}
    ,{id:'chat_1000',name:'频道核心',desc:'累计发送 1000 条聊天消息',counter:'chatMessages',goal:1000,xp:700,enabled:true}
    ,{id:'music_600',name:'年度歌单',desc:'累计在听歌室活跃 600 分钟',counter:'musicMinutes',goal:600,xp:700,enabled:true}
    ,{id:'tetris_5000',name:'方块高手',desc:'俄罗斯方块最高分达到 5000',counter:'tetrisBestScore',goal:5000,xp:240,enabled:true}
    ,{id:'tetris_20000',name:'方块大师',desc:'俄罗斯方块最高分达到 20000',counter:'tetrisBestScore',goal:20000,xp:650,enabled:true}
    ,{id:'sudoku_hard_10',name:'逻辑专家',desc:'完成 10 局困难数独',counter:'sudokuHardWins',goal:10,xp:500,enabled:true}
    ,{id:'mines_hell_5',name:'拆弹专家',desc:'完成 5 局地狱扫雷',counter:'minesHellWins',goal:5,xp:650,enabled:true}
  ]
};

const COUNTERS=new Set(['chatMessages','musicMinutes','gameMinutes','gamesFinished','purchases','petFeeds','friends','level','fishCaught','fishSold','fishLegendary','marketTrades','marketProfit','checkinStreakMax','checkinTotal','marketMaxTradeQty','tetrisBestScore','tetrisGames','sudokuHardWins','minesHellWins']);
function safeAsset(v){const s=text(v,300);return /^(?:\/|https:\/\/|data:image\/)/i.test(s)?s:''}
const safeColor=v=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):'';
const ACCESSORY_ORIGINAL_COLORS={'/accessories/bow.svg':'#ff7fa2','/accessories/leaf.svg':'#6fd477','/accessories/star.svg':'#ffd75d','/accessories/glasses.svg':'#1c2944','/accessories/scarf.svg':'#d96583','/accessories/flower.svg':'#ff83ad','/accessories/crown.svg':'#f1c84c','/accessories/headphones.svg':'#6278a8','/accessories/partyhat.svg':'#8f76df','/accessories/horns.svg':'#d45c77','/accessories/blush.svg':'#ff7891','/accessories/monocle.svg':'#d3b260','/accessories/bowtie.svg':'#cb5472','/accessories/bell.svg':'#e0b349','/accessories/halo.svg':'#ffe77a','/accessories/sparkles.svg':'#9dd9ff'};
function normalizeAccessory(x,i=0){const asset=safeAsset(x?.asset)||'/accessories/bow.svg',color=safeColor(x?.color)||ACCESSORY_ORIGINAL_COLORS[asset]||'';return {id:text(x?.id,48)||`acc_${Date.now().toString(36)}_${i}`,name:text(x?.name,30)||'新配饰',price:clamp(x?.price,0,99999999,1000),slot:['head','face','neck','effect'].includes(x?.slot)?x.slot:'head',desc:text(x?.desc,100),enabled:bool(x?.enabled),asset,x:clamp(x?.x,0,100,50),y:clamp(x?.y,-30,130,10),w:clamp(x?.w,8,160,45),rotate:clamp(x?.rotate,-180,180,0),z:clamp(x?.z,1,20,5),color}}
function normalizeFood(x,i=0){return {id:text(x?.id,48)||`food_${Date.now().toString(36)}_${i}`,name:text(x?.name,30)||'新食物',price:clamp(x?.price,0,99999999,300),hunger:clamp(x?.hunger,-100,100,20),mood:clamp(x?.mood,-100,100,3),desc:text(x?.desc,100),enabled:bool(x?.enabled)}}
function normalizeTitle(x,i=0){return {id:text(x?.id,48)||`title_${Date.now().toString(36)}_${i}`,name:text(x?.name,20)||'新头衔',price:clamp(x?.price,0,99999999,10000),desc:text(x?.desc,100),enabled:bool(x?.enabled)}}
function normalizeAchievement(x,i=0){return {id:text(x?.id,48)||`achievement_${Date.now().toString(36)}_${i}`,name:text(x?.name,30)||'新成就',desc:text(x?.desc,120),counter:COUNTERS.has(x?.counter)?x.counter:'gamesFinished',goal:clamp(x?.goal,1,99999999,1),xp:clamp(x?.xp,0,99999999,50),enabled:bool(x?.enabled)}}
function mergeById(current,defaults){const cur=Array.isArray(current)?current:[],out=cur.map(x=>({...x})),ids=new Set(out.map(x=>String(x?.id||'')));for(const d of defaults||[])if(!ids.has(String(d?.id||''))){out.push(clone(d));ids.add(String(d?.id||''))}return out}
const V4_ADDED_IDS={accessories:new Set(['acc_flower','acc_crown','acc_headphones']),food:new Set(['food_mint_mochi','food_berry_soda','food_moon_cookie']),titles:new Set(['title_lake_angler','title_market_watcher','title_table_regular']),achievements:new Set(['fish_250','market_200','pet_100','game_300'])};
const V9_ADDED_IDS={accessories:new Set(['acc_partyhat','acc_horns','acc_blush','acc_monocle','acc_bowtie','acc_bell','acc_halo','acc_sparkles']),titles:new Set(['title_lounge_familiar','title_lounge_voice','title_music_collector','title_music_master','title_game_veteran','title_game_master','title_slime_butler','title_slime_breeder','title_lake_hunter','title_lake_legend','title_market_trader','title_market_operator','title_table_veteran','title_table_master']),achievements:new Set(['checkin_streak_3','checkin_streak_7','checkin_streak_30','checkin_total_30','checkin_total_100','market_batch_100','market_batch_1000','market_batch_10000','market_profit_20000','fish_500','legendary_5','shop_50','pet_250','chat_1000','music_600','tetris_5000','tetris_20000','sudoku_hard_10','mines_hell_5'])};
function mergeVersioned(current,defaults,version,kind){let out=Array.isArray(current)?current:defaults;if(version<3)out=mergeById(out,defaults);else if(version<4)out=mergeById(out,(defaults||[]).filter(x=>V4_ADDED_IDS[kind]?.has(String(x?.id||''))));if(version<9)out=mergeById(out,(defaults||[]).filter(x=>V9_ADDED_IDS[kind]?.has(String(x?.id||''))));return out}
function migrateAccessoryColor(x,version){if(!x)return x;const asset=safeAsset(x.asset),original=ACCESSORY_ORIGINAL_COLORS[asset],c=safeColor(x.color);if(!original)return x;if(version<5&&(!c||c.toLowerCase()==='#ffffff'))return {...x,color:original};if(version<6&&c.toLowerCase()==='#ffffff')return {...x,color:original};return !c?{...x,color:original}:x}
function normalizeCore(src={},base=DEFAULT_PROGRESSION_CONFIG){const a={...base.account,...(src.account||{})},p={...base.pet,...(src.pet||{})};return {account:{defaultLevel:clamp(a.defaultLevel,1,9999,1),defaultXp:clamp(a.defaultXp,0,999999999,0),levelXpBase:clamp(a.levelXpBase,1,999999,160),levelXpPerLevel:clamp(a.levelXpPerLevel,0,999999,65),activityCooldownSec:clamp(a.activityCooldownSec,10,3600,55),chatMessageXp:clamp(a.chatMessageXp,0,99999,2),chatMessageCooldownSec:clamp(a.chatMessageCooldownSec,0,3600,20),chatMinuteXp:clamp(a.chatMinuteXp,0,99999,1),musicMinuteXp:clamp(a.musicMinuteXp,0,99999,3),gameMinuteXp:clamp(a.gameMinuteXp,0,99999,4),gameFinishXp:clamp(a.gameFinishXp,0,99999,20),purchaseXp:clamp(a.purchaseXp,0,99999,2),petXpSharePct:clamp(a.petXpSharePct,0,100,65)},pet:{defaultName:text(p.defaultName,12)||'小史莱姆',defaultLevel:clamp(p.defaultLevel,1,9999,1),defaultXp:clamp(p.defaultXp,0,999999999,0),defaultHunger:clamp(p.defaultHunger,0,100,80),defaultMood:clamp(p.defaultMood,0,100,70),levelXpBase:clamp(p.levelXpBase,1,999999,100),levelXpPerLevel:clamp(p.levelXpPerLevel,0,999999,40),hungerDecayPerHour:clamp(p.hungerDecayPerHour,0,100,2),moodHungerThreshold:clamp(p.moodHungerThreshold,0,100,35),moodDecayPerHour:clamp(p.moodDecayPerHour,0,100,1),moodHungerPenaltyPerHour:clamp(p.moodHungerPenaltyPerHour,0,100,2),badMoodThreshold:clamp(p.badMoodThreshold,0,100,25),lowHungerXpPenaltyPct:clamp(p.lowHungerXpPenaltyPct,0,90,20),badMoodXpPenaltyPct:clamp(p.badMoodXpPenaltyPct,0,90,20),chipPenaltyHungerThreshold:clamp(p.chipPenaltyHungerThreshold,0,100,15),chipPenaltyMoodThreshold:clamp(p.chipPenaltyMoodThreshold,0,100,15),lowHungerChipCostPerHour:clamp(p.lowHungerChipCostPerHour,0,100000,40),badMoodChipCostPerHour:clamp(p.badMoodChipCostPerHour,0,100000,25),maxOfflineChipPenaltyHours:clamp(p.maxOfflineChipPenaltyHours,0,720,24),maxOfflineDecayHours:clamp(p.maxOfflineDecayHours,0,720,72),feedXp:clamp(p.feedXp,0,99999,4),playXp:clamp(p.playXp,0,99999,6),playCooldownSec:clamp(p.playCooldownSec,0,86400,300),playMoodGain:clamp(p.playMoodGain,-100,100,14),playHungerCost:clamp(p.playHungerCost,-100,100,5)}}}
export function normalizeProgressionConfig(src={}){const core=normalizeCore(src),shop=src.shop||{},version=int(src.version),accessories=mergeVersioned(shop.accessories,DEFAULT_PROGRESSION_CONFIG.shop.accessories,version,'accessories'),food=mergeVersioned(shop.food,DEFAULT_PROGRESSION_CONFIG.shop.food,version,'food'),titles=mergeVersioned(shop.titles,DEFAULT_PROGRESSION_CONFIG.shop.titles,version,'titles'),ach=mergeVersioned(src.achievements,DEFAULT_PROGRESSION_CONFIG.achievements,version,'achievements');return {version:9,...core,shop:{accessories:accessories.map(x=>migrateAccessoryColor(x,version)).map(normalizeAccessory),food:food.map(normalizeFood),titles:titles.map(normalizeTitle)},achievements:ach.map(normalizeAchievement)}}
export function ensureProgressionConfig(data){data.progressionConfig=normalizeProgressionConfig(data.progressionConfig||{});return data.progressionConfig}

export function ensureProgressionUser(u){if(!u)return u;u.level=Math.max(1,int(u.level,1));u.xp=Math.max(0,int(u.xp,0));u.stats={chatMessages:0,musicMinutes:0,gameMinutes:0,gamesFinished:0,purchases:0,petFeeds:0,fishCaught:0,fishSold:0,fishLegendary:0,marketTrades:0,marketProfit:0,checkinStreak:0,checkinStreakMax:0,checkinTotal:0,marketMaxTradeQty:0,tetrisBestScore:0,tetrisGames:0,sudokuHardWins:0,minesHellWins:0,...(u.stats||{})};u.inventory={accessories:[],food:{},titles:[],...(u.inventory||{})};u.inventory.accessories=[...new Set(u.inventory.accessories||[])];u.inventory.titles=[...new Set(u.inventory.titles||[])];u.inventory.food={...(u.inventory.food||{})};u.achievements=[...new Set(u.achievements||[])];u.unlockedTitles=[];u.customTitles=[];u.equippedTitles=[...new Set(Array.isArray(u.equippedTitles)?u.equippedTitles:(u.equippedTitle?[String(u.equippedTitle)]:[]))].slice(0,8);u.equippedTitle=u.equippedTitles[0]||'';u.activityXpAt={...(u.activityXpAt||{})};u.pet={name:'小史莱姆',level:1,xp:0,hunger:80,mood:70,lastCareAt:Date.now(),equipped:{head:'',face:'',neck:'',effect:''},accessoryColors:{},...(u.pet||{})};u.pet.level=Math.max(1,int(u.pet.level,1));u.pet.xp=Math.max(0,int(u.pet.xp,0));u.pet.hunger=Math.max(0,Math.min(100,int(u.pet.hunger,80)));u.pet.mood=Math.max(0,Math.min(100,int(u.pet.mood,70)));u.pet.equipped={head:'',face:'',neck:'',effect:'',...(u.pet.equipped||{})};u.pet.accessoryColors={...(u.pet.accessoryColors||{})};return u}
function activeShop(cfg){return {accessories:cfg.shop.accessories.filter(x=>x.enabled),food:cfg.shop.food.filter(x=>x.enabled),titles:cfg.shop.titles.filter(x=>x.enabled)}}
function titleOptions(u,cfg){ensureProgressionUser(u);const names=cfg.shop.titles.filter(x=>x.enabled&&u.inventory.titles.includes(x.id)).map(x=>x.name);return [...new Set(names)]}
function cleanUserInventory(u,cfg){ensureProgressionUser(u);const accIds=new Set(cfg.shop.accessories.map(x=>x.id)),titleIds=new Set(cfg.shop.titles.map(x=>x.id));u.inventory.accessories=u.inventory.accessories.filter(x=>accIds.has(x));u.inventory.titles=u.inventory.titles.filter(x=>titleIds.has(x));for(const slot of ['head','face','neck','effect'])if(u.pet.equipped[slot]&&!u.inventory.accessories.includes(u.pet.equipped[slot]))u.pet.equipped[slot]='';for(const id of Object.keys(u.pet.accessoryColors||{}))if(!u.inventory.accessories.includes(id))delete u.pet.accessoryColors[id];const names=new Set(titleOptions(u,cfg));u.equippedTitles=(u.equippedTitles||[]).filter(x=>names.has(x)).slice(0,8);u.equippedTitle=u.equippedTitles[0]||'';u.unlockedTitles=[];u.customTitles=[]}
function accountXpNeed(level,cfg){return cfg.account.levelXpBase+Math.max(0,level-1)*cfg.account.levelXpPerLevel}
function petXpNeed(level,cfg){return cfg.pet.levelXpBase+Math.max(0,level-1)*cfg.pet.levelXpPerLevel}
function levelUp(u,cfg){let changed=false;while(u.xp>=accountXpNeed(u.level,cfg)){u.xp-=accountXpNeed(u.level,cfg);u.level++;changed=true}return changed}
function petLevelUp(u,cfg){let changed=false;while(u.pet.xp>=petXpNeed(u.pet.level,cfg)){u.pet.xp-=petXpNeed(u.pet.level,cfg);u.pet.level++;changed=true}return changed}
function refreshPet(u,cfg,now=Date.now()){ensureProgressionUser(u);const last=Number(u.pet.lastCareAt)||now,hours=Math.floor(Math.max(0,now-last)/3600000);if(hours>0){const h=Math.min(cfg.pet.maxOfflineDecayHours,hours),chargeHours=Math.min(h,cfg.pet.maxOfflineChipPenaltyHours);let charge=0;for(let i=0;i<h;i++){u.pet.hunger=Math.max(0,u.pet.hunger-cfg.pet.hungerDecayPerHour);u.pet.mood=Math.max(0,u.pet.mood-cfg.pet.moodDecayPerHour);if(u.pet.hunger<cfg.pet.moodHungerThreshold)u.pet.mood=Math.max(0,u.pet.mood-cfg.pet.moodHungerPenaltyPerHour);if(i<chargeHours){if(u.pet.hunger<=cfg.pet.chipPenaltyHungerThreshold)charge+=cfg.pet.lowHungerChipCostPerHour;if(u.pet.mood<=cfg.pet.chipPenaltyMoodThreshold)charge+=cfg.pet.badMoodChipCostPerHour}}if(charge>0){const before=Math.max(0,int(u.chips)),paid=Math.min(before,Math.max(0,int(charge)));u.chips=before-paid;u.chipsUpdatedAt=now;u.stats.petCareChipCost=(u.stats.petCareChipCost||0)+paid;u.pet.lastChipPenalty={at:now,amount:paid,hours:chargeHours}}u.pet.lastCareAt=last+hours*3600000}return u.pet}
function carePenalty(u,cfg){refreshPet(u,cfg);let pct=0;const reasons=[];if(u.pet.hunger<=cfg.pet.moodHungerThreshold){pct+=cfg.pet.lowHungerXpPenaltyPct;reasons.push(`饱腹 ${u.pet.hunger}≤${cfg.pet.moodHungerThreshold}：-${cfg.pet.lowHungerXpPenaltyPct}%`)}if(u.pet.mood<=cfg.pet.badMoodThreshold){pct+=cfg.pet.badMoodXpPenaltyPct;reasons.push(`心情 ${u.pet.mood}≤${cfg.pet.badMoodThreshold}：-${cfg.pet.badMoodXpPenaltyPct}%`)}return {pct:Math.min(90,pct),reasons}}
function grantXp(u,amount,cfg,{pet=true,care=false}={}){ensureProgressionUser(u);let n=Math.max(0,int(amount));if(care&&n){const penalty=carePenalty(u,cfg).pct;n=Math.max(0,Math.floor(n*(100-penalty)/100))}if(!n)return 0;u.xp+=n;if(pet&&cfg.account.petXpSharePct>0)u.pet.xp+=Math.max(1,Math.round(n*cfg.account.petXpSharePct/100));levelUp(u,cfg);petLevelUp(u,cfg);return n}
function evaluateAchievements(u,cfg,friendCount=0){ensureProgressionUser(u);const got=[],values={...u.stats,friends:friendCount,level:u.level};for(const a of cfg.achievements){if(!a.enabled||u.achievements.includes(a.id))continue;if((values[a.counter]||0)>=a.goal){u.achievements.push(a.id);grantXp(u,a.xp,cfg,{pet:false});got.push(a)}}return got}
export function publicProgressionExtras(u,cfg){ensureProgressionUser(u);const acc=cfg?.shop?.accessories||[],appearance=Object.values(u.pet.equipped||{}).filter(Boolean).map(id=>{const x=acc.find(a=>a.id===id);return x?{id:x.id,name:x.name,asset:x.asset,x:x.x,y:x.y,w:x.w,rotate:x.rotate,z:x.z,color:u.pet.accessoryColors?.[id]||x.color||''}:null}).filter(Boolean);return {level:u.level,xp:u.xp,equippedTitle:u.equippedTitle||'',equippedTitles:u.equippedTitles||[],appearance,pet:{name:u.pet.name,level:u.pet.level,hunger:u.pet.hunger,mood:u.pet.mood,equipped:u.pet.equipped},achievementCount:u.achievements.length}}

function parseList(v){if(Array.isArray(v))return v.map(x=>String(x));if(typeof v==='string')return v.split(',').map(x=>x.trim()).filter(Boolean);return []}
function parseFood(v){if(v&&typeof v==='object'&&!Array.isArray(v))return Object.fromEntries(Object.entries(v).map(([k,n])=>[k,Math.max(0,int(n))]));if(typeof v==='string')try{return parseFood(JSON.parse(v))}catch{}return {}}
function updateAdminUser(u,b,cfg){ensureProgressionUser(u);u.level=clamp(b.level,1,9999,u.level);u.xp=clamp(b.xp,0,999999999,u.xp);u.pet.level=clamp(b.petLevel,1,9999,u.pet.level);u.pet.xp=clamp(b.petXp,0,999999999,u.pet.xp);u.pet.hunger=clamp(b.hunger,0,100,u.pet.hunger);u.pet.mood=clamp(b.mood,0,100,u.pet.mood);for(const k of ['chatMessages','musicMinutes','gameMinutes','gamesFinished','purchases','petFeeds','fishCaught','fishSold','fishLegendary','marketTrades','marketProfit','checkinStreak','checkinStreakMax','checkinTotal','marketMaxTradeQty','tetrisBestScore','tetrisGames','sudokuHardWins','minesHellWins'])if(b[k]!=null)u.stats[k]=clamp(b[k],0,999999999,u.stats[k]);if(b.accessories!=null)u.inventory.accessories=parseList(b.accessories);if(b.titles!=null)u.inventory.titles=parseList(b.titles);if(b.food!=null)u.inventory.food=parseFood(b.food);cleanUserInventory(u,cfg)}

export function createProgressionService({data,body,auth,json,isStaff,publicUser,refreshWallet,save,friendRel}){
  let cfg=ensureProgressionConfig(data);for(const u of Object.values(data.users||{}))cleanUserInventory(u,cfg);
  const refreshCfg=()=>cfg=ensureProgressionConfig(data);
  const chipLocked=id=>Object.values(data.roomGames||{}).some(s=>['blackjack','poker'].includes(s?.kind)&&['insurance','playing','dealer','preflop','flop','turn','river','run_choice'].includes(s.phase)&&(s.seats||[]).some(p=>p?.userId===id));
  const friendCount=id=>(data.friendships||[]).filter(f=>f.state==='accepted'&&(f.a===id||f.b===id)).length;
  const selfPayload=u=>{refreshCfg();cleanUserInventory(u,cfg);refreshPet(u,cfg);evaluateAchievements(u,cfg,friendCount(u.userId));return {profile:publicUser(u),progression:{level:u.level,xp:u.xp,xpNext:accountXpNeed(u.level,cfg),petXpNext:petXpNeed(u.pet.level,cfg),stats:u.stats,achievements:cfg.achievements.filter(x=>x.enabled).map(a=>({...a,done:u.achievements.includes(a.id),progress:a.counter==='friends'?friendCount(u.userId):a.counter==='level'?u.level:u.stats[a.counter]||0})),titles:titleOptions(u,cfg),equippedTitle:u.equippedTitle,equippedTitles:u.equippedTitles,inventory:u.inventory,pet:u.pet,carePenalty:carePenalty(u,cfg),careChipRule:{hungerThreshold:cfg.pet.chipPenaltyHungerThreshold,moodThreshold:cfg.pet.chipPenaltyMoodThreshold,hungerPerHour:cfg.pet.lowHungerChipCostPerHour,moodPerHour:cfg.pet.badMoodChipCostPerHour,maxHours:cfg.pet.maxOfflineChipPenaltyHours},playReadyAt:Number(u.pet.lastPlayAt||0)+cfg.pet.playCooldownSec*1000,shop:activeShop(cfg)}}};
  function initializeUser(u){refreshCfg();if(!u)return u;const hadLevel=u.level!=null,hadPet=!!u.pet;if(!hadLevel){u.level=cfg.account.defaultLevel;u.xp=cfg.account.defaultXp}if(!hadPet)u.pet={name:cfg.pet.defaultName,level:cfg.pet.defaultLevel,xp:cfg.pet.defaultXp,hunger:cfg.pet.defaultHunger,mood:cfg.pet.defaultMood,lastCareAt:Date.now(),equipped:{head:'',face:'',neck:'',effect:''}};ensureProgressionUser(u);cleanUserInventory(u,cfg);return u}
  function activity(u,kind){refreshCfg();ensureProgressionUser(u);const now=Date.now(),last=Number(u.activityXpAt[kind]||0),wait=cfg.account.activityCooldownSec*1000;if(now-last<wait)return 0;u.activityXpAt[kind]=now;const pts=kind==='game'?cfg.account.gameMinuteXp:kind==='music'?cfg.account.musicMinuteXp:cfg.account.chatMinuteXp;const gained=grantXp(u,pts,cfg,{care:true});if(kind==='game')u.stats.gameMinutes++;if(kind==='music')u.stats.musicMinutes++;evaluateAchievements(u,cfg,friendCount(u.userId));return gained}
  function noteChat(u){refreshCfg();ensureProgressionUser(u);u.stats.chatMessages++;const now=Date.now();if(now-Number(u.activityXpAt.chatMessage||0)>=cfg.account.chatMessageCooldownSec*1000){u.activityXpAt.chatMessage=now;grantXp(u,cfg.account.chatMessageXp,cfg,{care:true})}evaluateAchievements(u,cfg,friendCount(u.userId));return true}
  function recordGameFinish(before,after){if(Number(before?.finishedAt)||!Number(after?.finishedAt))return false;refreshCfg();const ids=[];for(const p of after?.players||[])if(p&&!String(p).startsWith('BOT:'))ids.push(String(p));for(const p of after?.seats||[]){const id=p?.forfeitUserId||p?.userId;if(id&&!String(id).startsWith('BOT:'))ids.push(String(id))}let changed=false;for(const id of new Set(ids)){const u=data.users[id];if(!u)continue;ensureProgressionUser(u);u.stats.gamesFinished++;grantXp(u,cfg.account.gameFinishXp,cfg,{care:true});evaluateAchievements(u,cfg,friendCount(id));changed=true}return changed}
  const adminPayload=()=>({config:clone(cfg),defaults:clone(DEFAULT_PROGRESSION_CONFIG),users:Object.values(data.users||{}).map(u=>{ensureProgressionUser(u);return {userId:u.userId,loungeId:u.loungeId,name:u.name,slimeColor:u.slimeColor,level:u.level,xp:u.xp,stats:clone(u.stats),inventory:clone(u.inventory),pet:clone(u.pet),equippedTitle:u.equippedTitle||'',equippedTitles:u.equippedTitles||[]}})});
  async function handle(req,res,url){
    if(!url.pathname.startsWith('/api/progression/')&&!url.pathname.startsWith('/api/profile-card'))return false;
    if(req.method!=='POST')return json(res,405,{ok:false,error:'Method Not Allowed'}),true;
    const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'设备身份无效'}),true;refreshCfg();ensureProgressionUser(a.u);
    if(url.pathname==='/api/profile-card'){const target=data.users[String(b.targetUserId||a.u.userId)];if(!target)return json(res,404,{ok:false,error:'用户不存在'}),true;cleanUserInventory(target,cfg);refreshPet(target,cfg);const rel=target.userId===a.u.userId?'self':friendRel(a.u.userId,target.userId)?.state||'none';return json(res,200,{ok:true,profile:publicUser(target),relation:rel,achievements:target.achievements.length,pet:{name:target.pet.name,level:target.pet.level,equipped:target.pet.equipped}}),true}
    if(url.pathname==='/api/progression/self'){const out=selfPayload(a.u);save();return json(res,200,{ok:true,...out}),true}
    if(url.pathname==='/api/progression/tick'){const kind=['chat','music','game'].includes(b.kind)?b.kind:'chat',gained=activity(a.u,kind);if(gained)save();return json(res,200,{ok:true,gained,...selfPayload(a.u)}),true}
    if(url.pathname==='/api/progression/equip-title'){const owned=new Set(titleOptions(a.u,cfg)),titles=[...new Set((Array.isArray(b.titles)?b.titles:(b.title?[b.title]:[])).map(x=>text(x,20)).filter(Boolean))].slice(0,8);if(titles.some(x=>!owned.has(x)))return json(res,403,{ok:false,error:'包含尚未购买的头衔'}),true;a.u.equippedTitles=titles;a.u.equippedTitle=titles[0]||'';save();return json(res,200,{ok:true,...selfPayload(a.u)}),true}
    if(url.pathname==='/api/progression/pet'){refreshPet(a.u,cfg);const action=String(b.action||'');if(action==='rename'){const name=text(b.name,12);if(!name)return json(res,400,{ok:false,error:'宠物名字不能为空'}),true;a.u.pet.name=name}else if(action==='feed'){const id=String(b.itemId||''),item=cfg.shop.food.find(x=>x.enabled&&x.id===id),n=int(a.u.inventory.food[id]);if(!item||n<=0)return json(res,400,{ok:false,error:'背包里没有这份食物'}),true;a.u.inventory.food[id]=n-1;a.u.pet.hunger=Math.max(0,Math.min(100,a.u.pet.hunger+item.hunger));a.u.pet.mood=Math.max(0,Math.min(100,a.u.pet.mood+item.mood));a.u.stats.petFeeds++;a.u.pet.lastCareAt=Date.now();grantXp(a.u,cfg.pet.feedXp,cfg)}else if(action==='play'){const now=Date.now();if(now-Number(a.u.pet.lastPlayAt||0)<cfg.pet.playCooldownSec*1000)return json(res,409,{ok:false,error:'刚陪它玩过，过一会再来',retryAfterMs:Math.max(0,cfg.pet.playCooldownSec*1000-(now-Number(a.u.pet.lastPlayAt||0)))}),true;a.u.pet.lastPlayAt=now;a.u.pet.mood=Math.max(0,Math.min(100,a.u.pet.mood+cfg.pet.playMoodGain));a.u.pet.hunger=Math.max(0,Math.min(100,a.u.pet.hunger-cfg.pet.playHungerCost));grantXp(a.u,cfg.pet.playXp,cfg)}else if(action==='equip'){const id=String(b.itemId||''),item=cfg.shop.accessories.find(x=>x.enabled&&x.id===id);if(!item||!a.u.inventory.accessories.includes(id))return json(res,403,{ok:false,error:'还没有这个配饰'}),true;a.u.pet.equipped[item.slot]=a.u.pet.equipped[item.slot]===id?'':id}else if(action==='unequip'){const slot=['head','face','neck','effect'].includes(b.slot)?b.slot:'';if(slot)a.u.pet.equipped[slot]=''}else if(action==='color'){const id=String(b.itemId||'');if(!a.u.inventory.accessories.includes(id))return json(res,403,{ok:false,error:'还没有这个配饰'}),true;const c=safeColor(b.color);if(c)a.u.pet.accessoryColors[id]=c;else delete a.u.pet.accessoryColors[id]}else return json(res,400,{ok:false,error:'未知宠物操作'}),true;evaluateAchievements(a.u,cfg,friendCount(a.u.userId));save();return json(res,200,{ok:true,...selfPayload(a.u)}),true}
    if(url.pathname==='/api/progression/buy'){if(chipLocked(a.u.userId))return json(res,409,{ok:false,error:'21点 / 德州本手进行中，结束后再使用筹码购物'}),true;const cat=String(b.category||''),id=String(b.itemId||''),list=cfg.shop[cat],item=Array.isArray(list)?list.find(x=>x.enabled&&x.id===id):null;if(!item)return json(res,404,{ok:false,error:'商品不存在或已下架'}),true;const wallet=refreshWallet(a.u);if(wallet<item.price)return json(res,400,{ok:false,error:`筹码不足，需要 ${item.price}`}),true;if(cat==='accessories'&&a.u.inventory.accessories.includes(id))return json(res,409,{ok:false,error:'已经拥有这个配饰'}),true;if(cat==='titles'&&a.u.inventory.titles.includes(id))return json(res,409,{ok:false,error:'已经拥有这个头衔'}),true;a.u.chips=wallet-item.price;a.u.chipsUpdatedAt=Date.now();if(cat==='accessories')a.u.inventory.accessories.push(id);else if(cat==='titles')a.u.inventory.titles.push(id);else if(cat==='food')a.u.inventory.food[id]=int(a.u.inventory.food[id])+1;a.u.stats.purchases++;grantXp(a.u,cfg.account.purchaseXp,cfg,{care:true});evaluateAchievements(a.u,cfg,friendCount(a.u.userId));save();return json(res,200,{ok:true,...selfPayload(a.u)}),true}
    if(url.pathname==='/api/progression/admin-title')return json(res,410,{ok:false,error:'v0.3.8 起头衔统一由后台创建商品并在商城购买，不再直接授予玩家'}),true;
    if(url.pathname==='/api/progression/admin-config'){if(!isStaff(a.u))return json(res,403,{ok:false,error:'无管理员权限'}),true;const action=String(b.action||'get');if(action==='get')return json(res,200,{ok:true,...adminPayload()}),true;if(action==='save-core'){const n=normalizeCore({account:b.account||{},pet:b.pet||{}},cfg);cfg={...cfg,...n};data.progressionConfig=normalizeProgressionConfig(cfg);cfg=data.progressionConfig;save();return json(res,200,{ok:true,...adminPayload()}),true}if(action==='reset-defaults'){data.progressionConfig=clone(DEFAULT_PROGRESSION_CONFIG);cfg=ensureProgressionConfig(data);for(const u of Object.values(data.users||{}))cleanUserInventory(u,cfg);save();return json(res,200,{ok:true,...adminPayload()}),true}if(action==='reset-account'){cfg.account=clone(DEFAULT_PROGRESSION_CONFIG.account);data.progressionConfig=normalizeProgressionConfig(cfg);cfg=data.progressionConfig;save();return json(res,200,{ok:true,...adminPayload()}),true}if(action==='reset-pet'){cfg.pet=clone(DEFAULT_PROGRESSION_CONFIG.pet);data.progressionConfig=normalizeProgressionConfig(cfg);cfg=data.progressionConfig;save();return json(res,200,{ok:true,...adminPayload()}),true}return json(res,400,{ok:false,error:'未知配置操作'}),true}
    if(url.pathname==='/api/progression/admin-shop'){if(!isStaff(a.u))return json(res,403,{ok:false,error:'无管理员权限'}),true;const cat=String(b.category||''),action=String(b.action||'');if(!['accessories','food','titles'].includes(cat))return json(res,400,{ok:false,error:'商城分类无效'}),true;const list=cfg.shop[cat];if(action==='upsert'){const raw={...(b.item||{})},old=list.find(x=>x.id===raw.id),norm=cat==='accessories'?normalizeAccessory({...old,...raw}):cat==='food'?normalizeFood({...old,...raw}):normalizeTitle({...old,...raw});const idx=list.findIndex(x=>x.id===norm.id);if(idx>=0)list[idx]=norm;else list.push(norm)}else if(action==='move'){const id=String(b.itemId||''),idx=list.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{ok:false,error:'商品不存在'}),true;const step=Number(b.direction)<0?-1:1,next=Math.max(0,Math.min(list.length-1,idx+step));if(next!==idx){const [item]=list.splice(idx,1);list.splice(next,0,item)}}else if(action==='delete'){const id=String(b.itemId||''),idx=list.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{ok:false,error:'商品不存在'}),true;list.splice(idx,1);for(const u of Object.values(data.users||{})){ensureProgressionUser(u);if(cat==='accessories'){u.inventory.accessories=u.inventory.accessories.filter(x=>x!==id);for(const s of ['head','face','neck','effect'])if(u.pet.equipped[s]===id)u.pet.equipped[s]=''}else if(cat==='titles'){u.inventory.titles=u.inventory.titles.filter(x=>x!==id);cleanUserInventory(u,cfg)}else delete u.inventory.food[id]}}else return json(res,400,{ok:false,error:'未知商城操作'}),true;data.progressionConfig=normalizeProgressionConfig(cfg);cfg=data.progressionConfig;for(const u of Object.values(data.users||{}))cleanUserInventory(u,cfg);save();return json(res,200,{ok:true,...adminPayload()}),true}
    if(url.pathname==='/api/progression/admin-achievement'){if(!isStaff(a.u))return json(res,403,{ok:false,error:'无管理员权限'}),true;const action=String(b.action||'');if(action==='upsert'){const raw=b.item||{},old=cfg.achievements.find(x=>x.id===raw.id),norm=normalizeAchievement({...old,...raw}),idx=cfg.achievements.findIndex(x=>x.id===norm.id);if(idx>=0)cfg.achievements[idx]=norm;else cfg.achievements.push(norm)}else if(action==='delete'){const id=String(b.itemId||''),idx=cfg.achievements.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{ok:false,error:'成就不存在'}),true;cfg.achievements.splice(idx,1);for(const u of Object.values(data.users||{}))u.achievements=(u.achievements||[]).filter(x=>x!==id)}else return json(res,400,{ok:false,error:'未知成就操作'}),true;data.progressionConfig=normalizeProgressionConfig(cfg);cfg=data.progressionConfig;save();return json(res,200,{ok:true,...adminPayload()}),true}
    if(url.pathname==='/api/progression/admin-user'){if(!isStaff(a.u))return json(res,403,{ok:false,error:'无管理员权限'}),true;const target=data.users[String(b.targetUserId||'')];if(!target)return json(res,404,{ok:false,error:'用户不存在'}),true;updateAdminUser(target,b,cfg);save();return json(res,200,{ok:true,profile:publicUser(target)}),true}
    return json(res,404,{ok:false,error:'未知养成接口'}),true
  }
  function evaluateUser(u){refreshCfg();ensureProgressionUser(u);evaluateAchievements(u,cfg,friendCount(u.userId));return u}
  function grantExternalXp(u,amount){refreshCfg();ensureProgressionUser(u);grantXp(u,amount,cfg,{care:true});evaluateAchievements(u,cfg,friendCount(u.userId));return u}
  return {handle,activity,selfPayload,recordGameFinish,noteChat,initializeUser,evaluateUser,grantExternalXp}
}
