export function createRankingService({data,crypto,isBotId,refreshWallet,gameRankMode,gameHumanIds,gameChipRule,scheduleSave,hasBot,publicUser}){
const RANKED_KINDS=['dice','gomoku','xiangqi','chess','blackjack','poker','go','mahjong','uno','doudizhu'];
const emptyRank=()=>({games:0,wins:0,losses:0,draws:0,placements:[0,0,0,0],updatedAt:0});
function normalizeRankRecord(raw){if(raw&&('human' in raw||'ai' in raw||'legacy' in raw)){raw.human=raw.human||emptyRank();raw.ai=raw.ai||emptyRank();return raw}const legacy=raw&&typeof raw==='object'?{...emptyRank(),...raw}:emptyRank();return {human:emptyRank(),ai:emptyRank(),legacy}}
function rankStat(kind,userId,mode='human'){if(!RANKED_KINDS.includes(kind))throw Error('未知排行榜游戏');data.rankings[kind]||={};const rec=data.rankings[kind][userId]=normalizeRankRecord(data.rankings[kind][userId]);return rec[mode==='ai'?'ai':'human']}
function rankingOutcome(st,userId,outcome,mode){if(!data.users[userId])return;const r=rankStat(st.kind,userId,mode);r.games++;if(outcome==='win')r.wins++;else if(outcome==='draw')r.draws++;else r.losses++;r.updatedAt=Date.now()}
function rankingPlacement(st,userId,place,mode,outcome=null){if(!data.users[userId])return;const r=rankStat(st.kind,userId,mode),p=Math.max(1,Math.min(4,Math.floor(Number(place)||4)));r.games++;r.placements=Array.isArray(r.placements)?r.placements.slice(0,4):[0,0,0,0];while(r.placements.length<4)r.placements.push(0);r.placements[p-1]=(r.placements[p-1]||0)+1;const out=outcome||(p<=2?'win':'loss');if(out==='win')r.wins++;else if(out==='draw')r.draws++;else r.losses++;r.updatedAt=Date.now()}
function originalSeatUser(p){if(!p)return null;return p.forfeitUserId||(!p.isBot&&!isBotId(p.userId)?p.userId:null)}
function logChipSettlement(roomId,kind,deltas,reason){data.chipLedger||=[];data.chipLedger.push({id:crypto.randomUUID(),roomId,kind,reason,at:Date.now(),deltas});if(data.chipLedger.length>5000)data.chipLedger.splice(0,data.chipLedger.length-5000)}
function settleZeroSum(roomId,kind,claims,reason){const entries=Object.entries(claims||{}).filter(([uid,v])=>data.users[uid]&&Number.isFinite(Number(v))&&Math.trunc(Number(v))!==0).map(([uid,v])=>[uid,Math.trunc(Number(v))]);if(entries.length<2)return {};let wantPos=entries.filter(x=>x[1]>0),wantNeg=entries.filter(x=>x[1]<0);if(!wantPos.length||!wantNeg.length)return {};const paid={};let pool=0;for(const [uid,v] of wantNeg){const u=data.users[uid],available=refreshWallet(u),amt=Math.min(-v,available);if(amt<=0)continue;u.chips=Math.max(0,Number(u.chips)||0)-amt;u.chipsUpdatedAt=Date.now();paid[uid]=(paid[uid]||0)-amt;pool+=amt}if(pool<=0)return paid;let weight=wantPos.reduce((a,x)=>a+x[1],0),left=pool;for(let i=0;i<wantPos.length;i++){const [uid,v]=wantPos[i],amt=i===wantPos.length-1?left:Math.min(left,Math.floor(pool*v/weight));if(amt<=0)continue;const u=data.users[uid];refreshWallet(u);u.chips=Math.max(0,Number(u.chips)||0)+amt;u.chipsUpdatedAt=Date.now();paid[uid]=(paid[uid]||0)+amt;left-=amt}logChipSettlement(roomId,kind,paid,reason);return paid}
function transferChips(roomId,kind,loser,winner,amount,reason){if(!loser||!winner||loser===winner||!data.users[loser]||!data.users[winner])return {};return settleZeroSum(roomId,kind,{[loser]:-Math.max(0,Math.trunc(amount)),[winner]:Math.max(0,Math.trunc(amount))},reason)}
function centerClaims(rows){if(!rows.length)return {};const claims=Object.fromEntries(rows.map(x=>[x.uid,Math.round(x.raw||0)]));let sum=Object.values(claims).reduce((a,b)=>a+b,0);if(sum!==0){const target=rows.filter(x=>!x.forfeited).sort((a,b)=>(b.raw||0)-(a.raw||0))[0]||rows[0];claims[target.uid]-=sum}return claims}
function resultSignature(before,after){if(after.kind==='dice'&&after.phase==='result'&&before?.phase!=='result'&&after.winner&&after.loser)return `dice:${after.round-1}:${after.finishedAt}:${after.winner}:${after.loser}`;if(['gomoku','xiangqi','chess','go'].includes(after.kind)){if(!(after.winner||after.result)||before?.winner===after.winner&&before?.result===after.result)return'';return `${after.kind}:round:${after.round||1}:${after.finishedAt||Date.now()}:${after.winner||''}:${after.result||''}`}if(['blackjack','poker'].includes(after.kind)&&after.handNo>(before?.handNo||after.handNo))return `${after.kind}:hand:${after.handNo-1}`;if(after.kind==='uno'&&after.phase==='result'&&before?.phase!=='result'&&(after.placements||after.finishOrder)?.length)return `uno:${after.finishedAt||Date.now()}:${(after.placements||after.finishOrder).join(',')}`;if(after.kind==='mahjong'&&after.matchEnded&&!before?.matchEnded)return `mahjong:${after.finishedAt||after.matchEndedAt||Date.now()}:${(after.points||[]).join(',')}`;if(after.kind==='doudizhu'&&after.phase==='result'&&before?.phase!=='result')return `doudizhu:${after.finishedAt||Date.now()}:${after.winnerTeam||''}:${after.multiplier||1}`;return''}
function recordGameResult(roomId,before,after){
  if(!after||!RANKED_KINDS.includes(after.kind))return;const sig=resultSignature(before,after);if(!sig)return;if(data.rankingProcessed?.[roomId]===sig)return;data.rankingProcessed||={};data.rankingProcessed[roomId]=sig;const mode=gameRankMode(after)==='human'||gameRankMode(before)==='human'?'human':'ai';
  if(after.kind==='dice'){
    const winnerSeat=(after.seats||[]).find(p=>originalSeatUser(p)===after.winner||p?.userId===after.winner),loserSeat=(after.seats||[]).find(p=>originalSeatUser(p)===after.loser||p?.userId===after.loser);
    const winner=originalSeatUser(winnerSeat),loser=originalSeatUser(loserSeat);if(winner)rankingOutcome(after,winner,'win',mode);if(loser)rankingOutcome(after,loser,'loss',mode);
    if(mode==='human'&&winner&&loser&&winner!==loser){const stake=gameChipRule('dice',after).stake||30;transferChips(roomId,'dice',loser,winner,stake,`摇骰子真人局：胜 +${stake} / 负 -${stake}`)}scheduleSave();return
  }
  if(['gomoku','xiangqi','chess','go'].includes(after.kind)){
    const humans=[...new Set([...gameHumanIds(before),...gameHumanIds(after)])];for(const uid of humans)rankingOutcome(after,uid,after.winner?after.winner===uid?'win':'loss':'draw',mode);if(mode==='human'&&after.winner&&humans.length>=2){const loser=humans.find(x=>x!==after.winner);{const stake=gameChipRule(after.kind,after).stake||50;transferChips(roomId,after.kind,loser,after.winner,stake,`棋类真人局：胜 +${stake} / 负 -${stake}`)}}scheduleSave();return
  }
  if(['blackjack','poker'].includes(after.kind)){
    const participants=new Set;for(const p of after.seats||[]){const uid=originalSeatUser(p);if(uid)participants.add(uid)}for(const uid of Object.keys(after.forfeitUsers||{}))participants.add(uid);for(const uid of participants){const p=(after.seats||[]).find(x=>originalSeatUser(x)===uid);if(after.forfeitUsers?.[uid]&&!p){if(!after.forfeitRanked?.[uid])rankingOutcome(after,uid,'loss',mode);continue}if(!p?.result){if(after.forfeitUsers?.[uid]&&!after.forfeitRanked?.[uid])rankingOutcome(after,uid,'loss',mode);continue}const x=String(p.result||'');let out='loss';if(after.kind==='blackjack'){if(x.includes('持平')||x.includes('平局'))out='draw';else if(/^本局 \+/.test(x)||x==='胜'||x.startsWith('Blackjack · 3:2'))out='win'}else out=(Number(p.payout)||0)>Number(p.totalBet||0)?'win':Number(p.payout||0)===Number(p.totalBet||0)?'draw':'loss';if(after.forfeitUsers?.[uid])out='loss';if(!after.forfeitRanked?.[uid])rankingOutcome(after,uid,out,mode)}
    if(mode==='human'&&hasBot(after)){const rows=[];for(const p of after.seats||[]){const uid=originalSeatUser(p);if(!uid||!data.users[uid])continue;let raw=0;if(after.kind==='poker')raw=(Number(p.payout)||0)-(Number(p.totalBet)||0);else{const x=String(p.result||'');raw=x.includes('平')?0:x.startsWith('Blackjack · 3:2')?Math.round((Number(p.bet)||0)*1.5):x==='胜'?(Number(p.bet)||0):-(Number(p.bet)||0)}if(after.forfeitUsers?.[uid])raw=Math.min(raw,-50);rows.push({uid,raw,forfeited:!!after.forfeitUsers?.[uid]})}settleZeroSum(roomId,after.kind,centerClaims(rows),'含 AI 补位的多人真人局：仅真人之间零和结算')}
    after.forfeitUsers={};after.forfeitRanked={};scheduleSave();return
  }
  if(after.kind==='uno'){
    const seats=after.seats||[],order=(after.placements||after.finishOrder||[]).slice(),humanRows=[];for(const seatIndex of order){const p=seats[seatIndex],uid=originalSeatUser(p);if(uid&&data.users[uid]&&!humanRows.some(x=>x.uid===uid))humanRows.push({uid,seatIndex,forfeited:!!(p?.forfeited||after.forfeitUsers?.[uid])})}for(const uid of Object.keys(after.forfeitUsers||{}))if(data.users[uid]&&!humanRows.some(x=>x.uid===uid))humanRows.push({uid,seatIndex:999,forfeited:true});const ranked=humanRows.filter(x=>!x.forfeited).concat(humanRows.filter(x=>x.forfeited));const n=ranked.length,claims={},rankStep=gameChipRule('uno',after).rankStep||50;for(let i=0;i<n;i++)claims[ranked[i].uid]=rankStep*(n-1-2*i);for(let i=0;i<n;i++){const uid=ranked[i].uid,v=claims[uid]||0,seat=ranked[i].seatIndex,actualPlace=Math.max(1,Math.min(4,order.indexOf(seat)+1||4));if(!after.forfeitRanked?.[uid])rankingPlacement(after,uid,ranked[i].forfeited?4:actualPlace,mode,v>0?'win':v<0?'loss':'draw')}if(mode==='human'&&n>=2){settleZeroSum(roomId,'uno',claims,'UNO 名次零和结算')}after.forfeitUsers={};after.forfeitRanked={};scheduleSave();return
  }
  if(after.kind==='doudizhu'){
    const rows=[];for(let i=0;i<(after.seats||[]).length;i++){const p=after.seats[i],uid=originalSeatUser(p);if(!uid||!data.users[uid])continue;const won=(after.winnerTeam==='landlord')===(i===after.landlordSeat);rankingOutcome(after,uid,won?'win':'loss',mode);rows.push({uid,seat:i,won})}if(mode==='human'&&rows.length>=2){const stake=(gameChipRule('doudizhu',after).stake||40)*Math.max(1,Number(after.baseScore)||1)*Math.max(1,Number(after.multiplier)||1),claims={};for(const x of rows)claims[x.uid]=(x.seat===after.landlordSeat?(x.won?2:-2):(x.won?1:-1))*stake;settleZeroSum(roomId,'doudizhu',claims,`斗地主结算：基础分×倍数，地主双份`)}scheduleSave();return
  }
  if(after.kind==='mahjong'){
    const fullOrder=(after.points||[]).map((points,seat)=>({seat,points:Number(points||0)})).sort((a,b)=>b.points-a.points||a.seat-b.seat),rows=[];for(let i=0;i<(after.seats||[]).length;i++){const p=after.seats[i],uid=originalSeatUser(p);if(!uid||!data.users[uid]||rows.some(x=>x.uid===uid))continue;rows.push({uid,seat:i,points:Number(after.points?.[i]||25000),forfeited:!!(p?.forfeited||after.forfeitUsers?.[uid])})}for(const uid of Object.keys(after.forfeitUsers||{}))if(data.users[uid]&&!rows.some(x=>x.uid===uid))rows.push({uid,seat:-1,points:0,forfeited:true});for(const x of rows){const tablePlace=x.seat>=0?fullOrder.findIndex(y=>y.seat===x.seat)+1:4,actualPlace=Math.max(1,Math.min(4,tablePlace||4));if(!after.forfeitRanked?.[x.uid])rankingPlacement(after,x.uid,x.forfeited?4:actualPlace,mode,x.forfeited?'loss':actualPlace===1?'win':'loss')}if(mode==='human'&&rows.length>=2){const mean=rows.reduce((a,x)=>a+x.points,0)/rows.length,mjRule=gameChipRule('mahjong',after),ppc=mjRule.pointsPerChip||100,fp=mjRule.forfeitPenalty||50;const chipRows=rows.map(x=>({uid:x.uid,forfeited:x.forfeited,raw:x.forfeited?Math.min(Math.round((x.points-mean)/ppc),-fp):Math.round((x.points-mean)/ppc)}));settleZeroSum(roomId,'mahjong',centerClaims(chipRows),`日麻终局点数折算：每 ${ppc} 点≈1 筹码，真人间零和`)}after.forfeitUsers={};after.forfeitRanked={};scheduleSave();return
  }
}
function sanitizeRankStat(r){r=r&&typeof r==='object'?r:emptyRank();for(const k of ['wins','losses','draws'])r[k]=Math.max(0,Math.floor(Number(r[k])||0));r.placements=Array.isArray(r.placements)?r.placements.slice(0,4).map(x=>Math.max(0,Math.floor(Number(x)||0))):[0,0,0,0];while(r.placements.length<4)r.placements.push(0);r.games=Math.max(r.wins+r.losses+r.draws,r.placements.reduce((a,b)=>a+b,0));r.updatedAt=Math.max(0,Math.floor(Number(r.updatedAt)||0));return r}
function repairRankings(){let corrected=0,removed=0;data.rankings||={};for(const kind of RANKED_KINDS){const src=data.rankings[kind]||{};data.rankings[kind]=src;for(const [uid,raw] of Object.entries(src)){if(!data.users[uid]){delete src[uid];removed++;continue}const before=JSON.stringify(raw),rec=normalizeRankRecord(raw);rec.human=sanitizeRankStat(rec.human);rec.ai=sanitizeRankStat(rec.ai);if(rec.legacy)rec.legacy=sanitizeRankStat(rec.legacy);if(JSON.stringify(rec)!==before)corrected++;src[uid]=rec}}for(const k of Object.keys(data.rankings))if(!RANKED_KINDS.includes(k)){delete data.rankings[k];corrected++}if(corrected||removed)scheduleSave();return {corrected,removed,kinds:RANKED_KINDS.slice()}}
function leaderboardRows(kind,mode){const rows=Object.entries(data.rankings[kind]||{}).map(([userId,rec])=>{const u=data.users[userId],st=sanitizeRankStat(normalizeRankRecord(rec)[mode]||emptyRank());return {...st,userId,name:u?.name||'已离开用户',slimeColor:u?.slimeColor||'mint',loungeId:u?.loungeId||''}}).filter(x=>x.games>0);if(['uno','mahjong'].includes(kind))rows.sort((a,b)=>(b.placements?.[0]||0)-(a.placements?.[0]||0)||(b.placements?.[1]||0)-(a.placements?.[1]||0)||(a.placements?.[3]||0)-(b.placements?.[3]||0)||b.games-a.games||b.updatedAt-a.updatedAt);else rows.sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.games-a.games||b.updatedAt-a.updatedAt);return rows.slice(0,50)}
function leaderboardPayload(){repairRankings();const games={};for(const kind of RANKED_KINDS)games[kind]={human:leaderboardRows(kind,'human'),ai:leaderboardRows(kind,'ai')};const chips=Object.values(data.users).map(u=>({...publicUser(u)})).map(u=>({userId:u.userId,name:u.name,slimeColor:u.slimeColor,loungeId:u.loungeId,chips:u.chips})).sort((a,b)=>b.chips-a.chips||String(a.name).localeCompare(String(b.name),'zh-CN')).slice(0,100);const market=Object.values(data.users).map(u=>({userId:u.userId,name:u.name||'用户',slimeColor:u.slimeColor||'mint',loungeId:u.loungeId||'',profit:Math.round(Number(u.market?.realized)||0),trades:Math.max(0,Math.floor(Number(u.stats?.marketTrades)||0))})).filter(x=>x.trades>0||x.profit!==0).sort((a,b)=>b.profit-a.profit||b.trades-a.trades||String(a.name).localeCompare(String(b.name),'zh-CN')).slice(0,100);const fishing=Object.values(data.users).map(u=>({userId:u.userId,name:u.name||'用户',slimeColor:u.slimeColor||'mint',loungeId:u.loungeId||'',profit:Math.max(0,Math.round(Number(u.fishing?.totalValueSold)||0)),sold:Math.max(0,Math.floor(Number(u.stats?.fishSold)||0))})).filter(x=>x.sold>0||x.profit>0).sort((a,b)=>b.profit-a.profit||b.sold-a.sold||String(a.name).localeCompare(String(b.name),'zh-CN')).slice(0,100);return {chips,market,fishing,games}}

return {RANKED_KINDS,emptyRank,normalizeRankRecord,rankingOutcome,originalSeatUser,logChipSettlement,recordGameResult,repairRankings,leaderboardPayload,settleZeroSum,transferChips};
}
