const text=(v,n=40)=>String(v??'').trim().slice(0,n);
const int=(v,d=0)=>{const n=Math.floor(Number(v));return Number.isFinite(n)?n:d};
const DIFF={sudoku:new Set(['easy','medium','hard']),minesweeper:new Set(['beginner','normal','intermediate','expert','hell']),tetris:new Set(['classic'])};
export function createSingleGameService({data,crypto,body,auth,json,refreshWallet,gameEntryFee,logChipSettlement,publicUser,save,progression}){
 const rounds=new Map();
 function ensure(u){u.singleGames=u.singleGames&&typeof u.singleGames==='object'?u.singleGames:{};for(const k of ['tetris','sudoku','minesweeper'])u.singleGames[k]=u.singleGames[k]&&typeof u.singleGames[k]==='object'?u.singleGames[k]:{};return u.singleGames}
 function stat(u,kind,difficulty){const all=ensure(u),bucket=all[kind];bucket[difficulty]=bucket[difficulty]&&typeof bucket[difficulty]==='object'?bucket[difficulty]:{games:0,wins:0,bestScore:0,bestLines:0,bestMs:0,updatedAt:0};return bucket[difficulty]}
 function cleanRounds(){const now=Date.now();for(const [k,x] of rounds)if(now-x.at>21600000)rounds.delete(k)}
 async function handle(req,res,url){if(!['/api/game/entry','/api/game/single/result'].includes(url.pathname))return false;if(req.method!=='POST')return json(res,405,{ok:false,error:'Method Not Allowed'}),true;cleanRounds();const b=await body(req),a=auth(b.userId,b.deviceId,b.deviceToken,req);if(!a)return json(res,401,{ok:false,error:'身份无效'}),true;
  if(url.pathname==='/api/game/entry'){const kind=text(b.kind,24),difficulty=text(b.difficulty||({sudoku:'easy',minesweeper:'beginner',tetris:'classic'}[kind]||'classic'),24);if(!DIFF[kind])return json(res,400,{ok:false,error:'未知单机游戏'}),true;if(!DIFF[kind].has(difficulty))return json(res,400,{ok:false,error:'难度无效'}),true;const fee=gameEntryFee(kind,'ai'),wallet=refreshWallet(a.u);if(wallet<fee)return json(res,400,{ok:false,error:`筹码不足：本游戏每局费用为 ${fee}`}),true;if(fee){a.u.chips=wallet-fee;a.u.chipsUpdatedAt=Date.now();logChipSettlement(`single:${kind}`,kind,{[a.u.userId]:-fee},`单机每局费用 -${fee}`)}const token=crypto.randomUUID();rounds.set(token,{userId:a.u.userId,kind,difficulty,at:Date.now()});save();return json(res,200,{ok:true,fee,roundToken:token,profile:publicUser(a.u)}),true}
  const token=text(b.roundToken,80),r=rounds.get(token);if(!r||r.userId!==a.u.userId)return json(res,404,{ok:false,error:'本局记录不存在或已结算'}),true;rounds.delete(token);const elapsed=Math.max(0,Date.now()-r.at);if(elapsed<1500)return json(res,409,{ok:false,error:'本局完成时间异常，未计入排行榜'}),true;const st=stat(a.u,r.kind,r.difficulty),won=!!b.won,score=Math.max(0,Math.min(2000000,int(b.score))),lines=Math.max(0,Math.min(10000,int(b.lines)));st.games++;if(won)st.wins++;if(r.kind==='tetris'){st.bestScore=Math.max(st.bestScore||0,score);st.bestLines=Math.max(st.bestLines||0,lines);a.u.stats.tetrisGames=(a.u.stats.tetrisGames||0)+1;a.u.stats.tetrisBestScore=Math.max(a.u.stats.tetrisBestScore||0,score)}else if(won){if(!st.bestMs||elapsed<st.bestMs)st.bestMs=elapsed;if(r.kind==='sudoku'&&r.difficulty==='hard')a.u.stats.sudokuHardWins=(a.u.stats.sudokuHardWins||0)+1;if(r.kind==='minesweeper'&&r.difficulty==='hell')a.u.stats.minesHellWins=(a.u.stats.minesHellWins||0)+1}st.updatedAt=Date.now();progression?.evaluateUser?.(a.u);save();return json(res,200,{ok:true,record:st,profile:publicUser(a.u)}),true
 }
 return {handle,ensureUser:ensure};
}
