export function createWsSessionAuth({rateLimitSubject,diagnostics,auth,verifiedOnly,roomData,clean,clients,roomPollDrop,cancelDisconnectedSeatCleanup,tabTouch,schedulePresenceSave,send,data,publicUser,roomPublicUsers,publicGameState,roomRevision,broadcast}){
  return function authenticateWsClient(c,m){
    if(m?.type!=='auth'){diagnostics.wsDenied('auth-first-frame',c.req);try{c.socket.destroy()}catch{}return}
    if(!rateLimitSubject(`user:${String(m.userId||'unknown')}`,'ws-upgrade',60,60000)){diagnostics.noteRateLimit(c.req,'ws-upgrade','user');diagnostics.wsDenied('user-rate',c.req);try{c.socket.destroy()}catch{}return}
    const a=auth(m.userId,m.deviceId,m.deviceToken,c.req,m.deviceInfo||null);if(!a){diagnostics.clientEvent(c.req,null,null,'ws-auth-failed','设备身份无效',{userId:String(m.userId||''),deviceId:String(m.deviceId||'')});diagnostics.wsDenied('auth-invalid',c.req);send(c,{type:'error',error:'设备身份无效'});try{c.socket.end()}catch{}return}
    const gate=verifiedOnly(a);if(gate){diagnostics.clientEvent(c.req,a.u,a.d,'ws-auth-failed',gate);diagnostics.wsDenied('permission',c.req);send(c,{type:'error',error:gate});try{c.socket.end()}catch{}return}
    const roomId=String(m.roomId||''),def=roomData(roomId);if(!def){diagnostics.clientEvent(c.req,a.u,a.d,'ws-auth-failed','房间不存在',{roomId});diagnostics.wsDenied('room',c.req);send(c,{type:'error',error:'房间不存在'});try{c.socket.end()}catch{}return}
    c.userId=a.u.userId;c.deviceId=a.d.deviceId;c.roomId=roomId;c.tabId=clean(m.tabId,96);c.awaitingAuth=false;c.countedWs=true;c.connectedAt=Date.now();clearTimeout(c.authTimer);clients.add(c);diagnostics.identify(c.req,a.u,a.d,{roomId,transport:'websocket'});diagnostics.wsOpened();diagnostics.clientEvent(c.req,a.u,a.d,'ws-connected','WebSocket 第一帧认证成功',{roomId,transport:'websocket'});roomPollDrop(c.userId,roomId,c.tabId);cancelDisconnectedSeatCleanup(c.userId,roomId);tabTouch(c.userId,c.tabId);a.u.lastSeenAt=Date.now();a.u.currentRoomId=roomId;schedulePresenceSave(a.u.userId);
    const allMessages=data.roomMessages[roomId]||[],messages=allMessages.slice(-24);send(c,{type:'auth_ack',at:Date.now()});send(c,{type:'init',room:def,profile:publicUser(a.u),users:roomPublicUsers(roomId),messages,chatHasMore:def.category==='chat'&&allMessages.length>messages.length,music:data.roomMusic[roomId]||null,game:def.game?publicGameState(data.roomGames[roomId],a.u.userId):null,revision:roomRevision(roomId)});broadcast(roomId,{type:'presence',users:roomPublicUsers(roomId)});
  }
}
