const BOT_PREFIX='BOT:';
const isBot=v=>typeof v==='string'&&v.startsWith(BOT_PREFIX);
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-5);
const botId=()=>`${BOT_PREFIX}doudizhu:${uid()}`;
const clone=v=>JSON.parse(JSON.stringify(v));
const SUITS=['S','H','C','D'];
const RANKS=['3','4','5','6','7','8','9','10','J','Q','K','A','2'];
const rankValue=r=>RANKS.indexOf(r)+3;
const cardRank=c=>c.joker==='small'?16:c.joker==='big'?17:rankValue(c.r);
const sortCards=(a,b)=>cardRank(a)-cardRank(b)||String(a.s||'').localeCompare(String(b.s||''));
function deck(){const a=[];for(const r of RANKS)for(const s of SUITS)a.push({id:`${r}${s}`,r,s,v:rankValue(r)});a.push({id:'SJ',joker:'small',r:'SJ',v:16},{id:'BJ',joker:'big',r:'BJ',v:17});return a}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function counts(cards){const m=new Map;for(const c of cards)m.set(cardRank(c),(m.get(cardRank(c))||0)+1);return m}
function seq(vals){if(!vals.length)return false;for(let i=1;i<vals.length;i++)if(vals[i]!==vals[i-1]+1)return false;return true}
export function classifyDdz(cards){
  const cs=(cards||[]).slice().sort(sortCards),n=cs.length;if(!n)return null;const m=counts(cs),groups=[...m.entries()].sort((a,b)=>a[0]-b[0]),vals=groups.map(x=>x[0]),byCount=k=>groups.filter(x=>x[1]===k).map(x=>x[0]);
  if(n===2&&vals.length===2&&vals[0]===16&&vals[1]===17)return {type:'rocket',main:17,n};
  if(n===4&&groups.length===1)return {type:'bomb',main:vals[0],n};
  if(n===1)return {type:'single',main:vals[0],n};
  if(n===2&&groups.length===1)return {type:'pair',main:vals[0],n};
  if(n===3&&groups.length===1)return {type:'triple',main:vals[0],n};
  if(n===4&&byCount(3).length===1)return {type:'triple_single',main:byCount(3)[0],n};
  if(n===5&&byCount(3).length===1&&byCount(2).length===1)return {type:'triple_pair',main:byCount(3)[0],n};
  if(n>=5&&groups.every(x=>x[1]===1)&&vals.at(-1)<=14&&seq(vals))return {type:'straight',main:vals.at(-1),n,len:n};
  if(n>=6&&n%2===0&&groups.every(x=>x[1]===2)&&vals.at(-1)<=14&&seq(vals))return {type:'pair_straight',main:vals.at(-1),n,len:vals.length};
  const triples=byCount(3).filter(x=>x<=14),tseq=triples.length>=2&&seq(triples);
  if(tseq&&groups.length===triples.length&&n===triples.length*3)return {type:'airplane',main:triples.at(-1),n,len:triples.length};
  if(tseq&&n===triples.length*4){const rem=groups.filter(([v])=>!triples.includes(v)).reduce((a,[,c])=>a+c,0);if(rem===triples.length)return {type:'airplane_single',main:triples.at(-1),n,len:triples.length}}
  if(tseq&&n===triples.length*5){const rem=groups.filter(([v])=>!triples.includes(v));if(rem.length===triples.length&&rem.every(([,c])=>c===2))return {type:'airplane_pair',main:triples.at(-1),n,len:triples.length}}
  if(n===6&&byCount(4).length===1)return {type:'four_two_single',main:byCount(4)[0],n};
  if(n===8&&byCount(4).length===1){const rest=groups.filter(([v])=>v!==byCount(4)[0]);if(rest.length===2&&rest.every(([,c])=>c===2))return {type:'four_two_pair',main:byCount(4)[0],n}}
  return null
}
export function beatsDdz(a,b){const A=typeof a?.type==='string'?a:classifyDdz(a),B=typeof b?.type==='string'?b:classifyDdz(b);if(!A)return false;if(!B)return true;if(A.type==='rocket')return true;if(B.type==='rocket')return false;if(A.type==='bomb'&&B.type!=='bomb')return true;if(B.type==='bomb'&&A.type!=='bomb')return false;return A.type===B.type&&A.n===B.n&&(A.len||0)===(B.len||0)&&A.main>B.main}
export function createDoudizhu(){return {kind:'doudizhu',seats:Array(3).fill(null),phase:'waiting',turnSeat:null,turnStartedAt:0,turnTimeoutMs:30000,round:1,deck:[],bottom:[],landlordSeat:null,bidSeat:0,bids:[null,null,null],highestBid:0,highestBidSeat:null,lastPlay:null,lastPlaySeat:null,passCount:0,multiplier:1,baseScore:1,winner:null,winnerTeam:null,message:'等待 3 位玩家入座（可 AI 补位）',finishedAt:0,startedAt:0,playCounts:[0,0,0]}}
function seatIndex(s,u){return s.seats.findIndex(x=>x?.userId===u)}
function join(s,u,seat=null){if(seatIndex(s,u)>=0)return;const i=Number.isInteger(seat)?seat:s.seats.findIndex(x=>!x);if(i<0||i>=3||s.seats[i])throw Error('座位不可用');s.seats[i]={userId:u,isBot:isBot(u),ready:isBot(u),hand:[],result:''}}
function leave(s,u){const i=seatIndex(s,u);if(i<0)return;if(['bidding','playing'].includes(s.phase)){const p=s.seats[i];s.seats[i]={...p,userId:botId(),isBot:true,ready:true,forfeitUserId:p.forfeitUserId||p.userId,forfeited:true};s.message='有玩家离开，已由 AI 托管该座位';return}s.seats[i]=null}
function ready(s,u){const i=seatIndex(s,u);if(i<0)throw Error('请先入座');if(s.seats[i].isBot)return;s.seats[i].ready=!s.seats[i].ready}
function allReady(s){return s.seats.every(x=>x&&(x.isBot||x.ready))}
function fillBots(s){while(s.seats.some(x=>!x)){const i=s.seats.findIndex(x=>!x);s.seats[i]={userId:botId(),isBot:true,ready:true,hand:[],result:''}}}
function deal(s){const d=shuffle(deck());for(const p of s.seats){p.hand=[];p.result=''}for(let i=0;i<51;i++)s.seats[i%3].hand.push(d[i]);for(const p of s.seats)p.hand.sort(sortCards);s.bottom=d.slice(51);s.phase='bidding';s.landlordSeat=null;s.bidSeat=Math.floor(Math.random()*3);s.bids=[null,null,null];s.highestBid=0;s.highestBidSeat=null;s.lastPlay=null;s.lastPlaySeat=null;s.passCount=0;s.multiplier=1;s.baseScore=1;s.winner=null;s.winnerTeam=null;s.finishedAt=0;s.startedAt=Date.now();s.playCounts=[0,0,0];s.turnStartedAt=Date.now();s.message=`叫地主 · ${s.bidSeat+1}号位选择 0~3 分`}
function start(s){if(s.seats.filter(Boolean).length===1)fillBots(s);if(s.seats.filter(Boolean).length<3)throw Error('斗地主需要 3 位玩家，可添加 AI 补位');if(!allReady(s))throw Error('所有真人准备后才能开始');deal(s)}
function finishBidding(s){if(s.highestBid<=0||s.highestBidSeat==null){s.message='三家都不叫，重新发牌';deal(s);return}s.landlordSeat=s.highestBidSeat;s.baseScore=s.highestBid;s.seats[s.landlordSeat].hand.push(...s.bottom);s.seats[s.landlordSeat].hand.sort(sortCards);s.phase='playing';s.turnSeat=s.landlordSeat;s.turnStartedAt=Date.now();s.message=`${s.landlordSeat+1}号位成为地主 · 底牌已加入手牌 · 倍数 ${s.multiplier}`}
function bid(s,u,score){const i=seatIndex(s,u);if(s.phase!=='bidding'||i!==s.bidSeat)throw Error('现在不是你叫地主');const v=Math.floor(Number(score));if(!Number.isInteger(v)||v<0||v>3)throw Error('叫分必须是 0~3');if(v>0&&v<=s.highestBid)throw Error(`必须高于当前 ${s.highestBid} 分，或选择不叫`);s.bids[i]=v;if(v>s.highestBid){s.highestBid=v;s.highestBidSeat=i}if(v===3)return finishBidding(s);let next=(i+1)%3,count=0;while(count<3&&s.bids[next]!=null){next=(next+1)%3;count++}if(s.bids.every(x=>x!=null))return finishBidding(s);s.bidSeat=next;s.turnStartedAt=Date.now();s.message=`叫地主 · 当前最高 ${s.highestBid||0} 分 · ${next+1}号位选择`}
function resolveCards(p,ids){const set=new Set((ids||[]).map(String));if(!set.size)throw Error('请选择要出的牌');const cards=p.hand.filter(c=>set.has(c.id));if(cards.length!==set.size)throw Error('选中的牌已经变化，请重新选择');return cards}
function finishGame(s,seat){s.winner=s.seats[seat]?.userId||null;s.winnerTeam=seat===s.landlordSeat?'landlord':'peasants';const landlordPlays=s.playCounts[s.landlordSeat]||0,peasants=s.playCounts.reduce((a,x,i)=>a+(i===s.landlordSeat?0:x),0);if((seat===s.landlordSeat&&peasants===0)||(seat!==s.landlordSeat&&landlordPlays<=1))s.multiplier*=2;const unit=s.baseScore*s.multiplier;for(let i=0;i<3;i++){const p=s.seats[i];if(!p)continue;const won=(seat===s.landlordSeat)===(i===s.landlordSeat);p.result=won?`胜 +${i===s.landlordSeat?unit*2:unit}`:`负 -${i===s.landlordSeat?unit*2:unit}`}s.phase='result';s.turnSeat=null;s.turnStartedAt=0;s.finishedAt=Date.now();s.message=`${s.winnerTeam==='landlord'?'地主':'农民'}胜 · 基础 ${s.baseScore} × 倍数 ${s.multiplier}`}
function play(s,u,ids){const i=seatIndex(s,u);if(s.phase!=='playing'||i!==s.turnSeat)throw Error('还没轮到你');const p=s.seats[i],cards=resolveCards(p,ids),combo=classifyDdz(cards);if(!combo)throw Error('这不是合法的斗地主牌型');if(s.lastPlay&&s.lastPlaySeat!==i&&!beatsDdz(combo,s.lastPlay.combo))throw Error('这手牌压不过上一手');const idset=new Set(cards.map(c=>c.id));p.hand=p.hand.filter(c=>!idset.has(c.id));s.lastPlay={cards:clone(cards),combo};s.lastPlaySeat=i;s.passCount=0;s.playCounts[i]=(s.playCounts[i]||0)+1;if(combo.type==='bomb'||combo.type==='rocket')s.multiplier*=2;if(!p.hand.length)return finishGame(s,i);s.turnSeat=(i+1)%3;s.turnStartedAt=Date.now();s.message=`${i+1}号位出牌 · ${combo.type} · 当前倍数 ${s.multiplier}`}
function pass(s,u){const i=seatIndex(s,u);if(s.phase!=='playing'||i!==s.turnSeat)throw Error('还没轮到你');if(!s.lastPlay||s.lastPlaySeat===i)throw Error('你是新一轮领出，不能不出');s.passCount++;if(s.passCount>=2){s.turnSeat=s.lastPlaySeat;s.lastPlay=null;s.lastPlaySeat=null;s.passCount=0;s.message='两家不出 · 上一手玩家重新领出'}else{s.turnSeat=(i+1)%3;s.message=`${i+1}号位不出`}s.turnStartedAt=Date.now()}
function reset(s){const seats=s.seats;Object.assign(s,createDoudizhu(),{seats});for(const p of seats)if(p){p.ready=p.isBot;p.hand=[];p.result=''}}
export function applyDoudizhuAction(s,u,a){if(a.type==='join')return join(s,u,a.seat);if(a.type==='leave')return leave(s,u);if(a.type==='ready')return ready(s,u);if(a.type==='start')return start(s);if(a.type==='reset')return reset(s);if(a.type==='bid')return bid(s,u,a.score);if(a.type==='play')return play(s,u,a.cardIds);if(a.type==='pass')return pass(s,u);throw Error('未知斗地主操作')}
function allSubsetsForSimple(hand,last){const out=[];const by=new Map;for(const c of hand){const r=cardRank(c);if(!by.has(r))by.set(r,[]);by.get(r).push(c)}const target=last?.combo;if(!target||target.type==='single')for(const [r,a] of by)if(a.length>=1&&(!target||r>target.main))out.push([a[0]]);if(!target||target.type==='pair')for(const [r,a] of by)if(a.length>=2&&(!target||r>target.main))out.push(a.slice(0,2));if(!target||target.type==='triple')for(const [r,a] of by)if(a.length>=3&&(!target||r>target.main))out.push(a.slice(0,3));for(const [r,a] of by)if(a.length===4&&(!target||target.type!=='bomb'||r>target.main))out.push(a.slice());const sj=hand.find(c=>c.joker==='small'),bj=hand.find(c=>c.joker==='big');if(sj&&bj)out.push([sj,bj]);return out}
function botAction(s,seat){const p=s.seats[seat];if(s.phase==='bidding'){const strength=p.hand.reduce((v,c)=>v+(cardRank(c)>=15?2:cardRank(c)>=13?1:0),0)+(p.hand.some(c=>c.joker==='small')&&p.hand.some(c=>c.joker==='big')?4:0);let score=strength>=10?3:strength>=7?2:strength>=4?1:0;if(score<=s.highestBid)score=0;return {type:'bid',score}}if(s.phase!=='playing')return null;const last=s.lastPlaySeat===seat?null:s.lastPlay,opts=allSubsetsForSimple(p.hand,last);if(opts.length){opts.sort((a,b)=>a.length-b.length||cardRank(a[0])-cardRank(b[0]));return {type:'play',cardIds:opts[0].map(c=>c.id)}}if(!last){const c=p.hand[0];return c?{type:'play',cardIds:[c.id]}:null}return {type:'pass'}}
export function advanceDoudizhuBots(s,max=80){for(let k=0;k<max;k++){if(!['bidding','playing'].includes(s.phase))break;const seat=s.phase==='bidding'?s.bidSeat:s.turnSeat,p=s.seats[seat];if(!p?.isBot)break;const a=botAction(s,seat);if(!a)break;applyDoudizhuAction(s,p.userId,a)}}
export function addDoudizhuBot(s,seat=null){if(s.phase!=='waiting')throw Error('只能在等待阶段添加 AI');const i=Number.isInteger(seat)?seat:s.seats.findIndex(x=>!x);if(i<0||i>=3||s.seats[i])throw Error('没有空位');const id=botId();s.seats[i]={userId:id,isBot:true,ready:true,hand:[],result:''};return id}
export function removeDoudizhuBot(s,seat=null){if(s.phase!=='waiting')throw Error('对局进行中不能移除 AI');const i=Number.isInteger(seat)?seat:s.seats.findIndex(x=>x?.isBot);if(i>=0&&s.seats[i]?.isBot){s.seats[i]=null;return true}return false}
export function doudizhuHasBot(s){return s?.seats?.some(x=>x?.isBot)||false}
export function publicDoudizhuState(s,viewerId){const x=clone(s),me=seatIndex(s,viewerId);x.serverNow=Date.now();x.mySeat=me;for(let i=0;i<3;i++){const p=x.seats[i];if(!p)continue;p.handCount=p.hand?.length||0;if(p.userId!==viewerId)p.hand=(p.hand||[]).map(()=>({hidden:true}))}if(x.phase!=='result'&&me!==x.landlordSeat)x.bottom=(x.bottom||[]).map(()=>({hidden:true}));return x}
export function tickDoudizhu(s,now=Date.now()){let changed=false;if(['bidding','playing'].includes(s.phase)&&s.turnStartedAt&&now-s.turnStartedAt>=(s.turnTimeoutMs||30000)){const seat=s.phase==='bidding'?s.bidSeat:s.turnSeat,p=s.seats[seat];if(p&&!p.isBot){try{applyDoudizhuAction(s,p.userId,s.phase==='bidding'?{type:'bid',score:0}:(s.lastPlay&&s.lastPlaySeat!==seat?{type:'pass'}:{type:'play',cardIds:[p.hand[0]?.id].filter(Boolean)}));changed=true}catch{}}}return {changed,forceLeaveUsers:[],autoReset:!!(s.finishedAt&&now-s.finishedAt>=90000)}}
