import {createDoudizhu,applyDoudizhuAction,addDoudizhuBot,removeDoudizhuBot,doudizhuHasBot,advanceDoudizhuBots,publicDoudizhuState,tickDoudizhu} from './doudizhu.js';
import {createRiichiState,riichiStartHand,applyRiichiAction,riichiBotTurn,riichiBotReaction,tickRiichi,publicRiichiState,mahjongTileName} from './riichi.js';
// SlimeLounge v0.2.2 extra games.
// This module intentionally stays independent from games.js so new rule engines do not destabilize the original five games.

export const EXTRA_ROOM_DEFS=[
  {id:'tetris-1',category:'game',game:'tetris',single:true,mode:'single',label:'经典',name:'俄罗斯方块 · 经典',description:'10×20 · 键盘 / 触屏 · 逐级加速',capacity:1,difficulty:'classic'},
  {id:'sudoku-1',category:'game',game:'sudoku',single:true,mode:'single',label:'简单',name:'数独 · 简单',description:'单机数独，约 40 个空格',capacity:1,difficulty:'easy'},
  {id:'sudoku-2',category:'game',game:'sudoku',single:true,mode:'single',label:'中等',name:'数独 · 中等',description:'单机数独，约 50 个空格',capacity:1,difficulty:'medium'},
  {id:'sudoku-3',category:'game',game:'sudoku',single:true,mode:'single',label:'困难',name:'数独 · 困难',description:'单机数独，约 56 个空格',capacity:1,difficulty:'hard'},
  {id:'minesweeper-1',category:'game',game:'minesweeper',single:true,mode:'single',label:'初级',name:'扫雷 · 初级',description:'9×9 / 10 雷',capacity:1,difficulty:'beginner',board:{w:9,h:9,mines:10}},
  {id:'minesweeper-2',category:'game',game:'minesweeper',single:true,mode:'single',label:'标准',name:'扫雷 · 标准',description:'12×12 / 22 雷',capacity:1,difficulty:'normal',board:{w:12,h:12,mines:22}},
  {id:'minesweeper-3',category:'game',game:'minesweeper',single:true,mode:'single',label:'中级',name:'扫雷 · 中级',description:'16×16 / 40 雷',capacity:1,difficulty:'intermediate',board:{w:16,h:16,mines:40}},
  {id:'minesweeper-4',category:'game',game:'minesweeper',single:true,mode:'single',label:'高级',name:'扫雷 · 高级',description:'20×16 / 60 雷',capacity:1,difficulty:'expert',board:{w:20,h:16,mines:60}},
  {id:'minesweeper-5',category:'game',game:'minesweeper',single:true,mode:'single',label:'地狱',name:'扫雷 · 地狱',description:'24×18 / 90 雷',capacity:1,difficulty:'hell',board:{w:24,h:18,mines:90}},
  ...Array.from({length:3},(_,i)=>({id:`go-${i+1}`,category:'game',game:'go',mode:'multi',name:`围棋 ${i+1}号房`,label:`${i+1}号房`,description:'19路标准围棋 · 提子 / 禁入点 / 全局同形 / 数目',capacity:2})),
  ...Array.from({length:2},(_,i)=>({id:`mahjong-${i+1}`,category:'game',game:'mahjong',mode:'multi',name:`日麻 ${i+1}号房`,label:`${i+1}号房`,description:'四人立直麻将 · 番符 / 吃碰杠 / 宝牌 / 振听',capacity:4,minPlayers:1})),
  ...Array.from({length:2},(_,i)=>({id:`uno-${i+1}`,category:'game',game:'uno',mode:'multi',name:`UNO ${i+1}号房`,label:`${i+1}号房`,description:'2~4 人 UNO · +2 / +4 / 跳过 / 反转',capacity:4,minPlayers:1})),
  ...Array.from({length:3},(_,i)=>({id:`doudizhu-${i+1}`,category:'game',game:'doudizhu',mode:'multi',name:`斗地主 ${i+1}号房`,label:`${i+1}号房`,description:'三人斗地主 · 叫分 / 地主底牌 / 顺子连对飞机 / 炸弹火箭 / 春天',capacity:3,minPlayers:1})),
];

const BOT_PREFIX='BOT:';
export const EXTRA_KINDS=new Set(['go','mahjong','uno','doudizhu']);
export const isExtraKind=k=>EXTRA_KINDS.has(k);
const isBot=v=>typeof v==='string'&&v.startsWith(BOT_PREFIX);
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-5);
const botId=k=>`${BOT_PREFIX}${k}:${uid()}`;
const clone=v=>JSON.parse(JSON.stringify(v));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function nextOccupied(seats,from){for(let n=1;n<=seats.length;n++){const i=(from+n)%seats.length;if(seats[i])return i}return -1}
function occupiedCount(seats){return seats.filter(Boolean).length}

// ---------------- Generic ready / seat helpers ----------------
function twoCreate(kind,extra={}){return {kind,players:[null,null],ready:[false,false],started:false,turn:0,winner:null,result:null,last:null,round:1,turnStartedAt:0,turnTimeoutMs:60000,finishedAt:0,...extra}}
function twoJoin(s,u,seat=null){if(s.players.includes(u))return;const i=Number.isInteger(seat)?seat:s.players.findIndex(x=>!x);if(i<0||i>1||s.players[i])throw Error('座位不可用');s.players[i]=u;s.ready[i]=isBot(u);twoMaybeStart(s)}
function twoLeave(s,u){const i=s.players.indexOf(u);if(i>=0){if(s.started&&!s.winner&&!s.result&&s.players[1-i]){s.winner=s.players[1-i];s.result='forfeit';s.finishedAt=Date.now()}s.players[i]=null;s.ready[i]=false;s.started=false;s.turnStartedAt=0}}
function twoReady(s,u){const i=s.players.indexOf(u);if(i<0)throw Error('请先入座');if(isBot(u))return;s.ready[i]=!s.ready[i];twoMaybeStart(s)}
function twoMaybeStart(s){const was=s.started;for(let i=0;i<2;i++)if(isBot(s.players[i]))s.ready[i]=true;s.started=s.players.every(Boolean)&&s.players.every((p,i)=>isBot(p)||s.ready[i]);if(s.started&&!was)s.turnStartedAt=Date.now();return s.started}

function seatCreate(kind,n,extra={}){return {kind,seats:Array(n).fill(null),phase:'waiting',turnSeat:null,turnStartedAt:0,turnTimeoutMs:30000,finishedAt:0,winnerTeam:null,winner:null,message:'等待玩家入座',round:1,...extra}}
function seatJoin(s,u,seat=null){let i=s.seats.findIndex(x=>x?.userId===u);if(i>=0)return i;i=Number.isInteger(seat)?seat:s.seats.findIndex(x=>!x);if(i<0||i>=s.seats.length||s.seats[i])throw Error('座位不可用');s.seats[i]={userId:u,isBot:isBot(u),ready:isBot(u),hand:[]};return i}
function seatLeave(s,u){const i=s.seats.findIndex(x=>x?.userId===u);if(i<0)return;const active=['playing','reaction'].includes(s.phase);if(active){const old=s.seats[i];s.seats[i]={...old,userId:botId(s.kind),isBot:true,ready:true,forfeitUserId:old.forfeitUserId||old.userId,forfeited:true};s.message='有玩家离开，已由高级 AI 托管该座位';return}s.seats[i]=null}
function seatReady(s,u){const i=s.seats.findIndex(x=>x?.userId===u);if(i<0)throw Error('请先入座');if(s.seats[i].isBot)return;s.seats[i].ready=!s.seats[i].ready}
function allReady(s,min=2){const occ=s.seats.filter(Boolean);return occ.length>=min&&occ.every(x=>x.isBot||x.ready)}
function autoFillBots(s,target){while(occupiedCount(s.seats)<target){const i=s.seats.findIndex(x=>!x);if(i<0)break;s.seats[i]={userId:botId(s.kind),isBot:true,ready:true,hand:[]}}}

// ---------------- Go / 围棋 (19x19) ----------------
const GO_N=19,goDirs=[[1,0],[-1,0],[0,1],[0,-1]];
function goBoard(){return Array.from({length:GO_N},()=>Array(GO_N).fill(null))}
export function createGo(){const board=goBoard();return twoCreate('go',{size:GO_N,board,turn:0,captures:[0,0],passes:0,previousHash:'',history:[goHash(board)],komi:6.5,scores:null})}
const goHash=b=>b.map(r=>r.map(x=>x==null?'.':x).join('')).join('/');
function goGroup(board,x,y){const c=board[y]?.[x];if(c==null)return {stones:[],libs:new Set};const stack=[[x,y]],seen=new Set([`${x},${y}`]),stones=[],libs=new Set;while(stack.length){const [cx,cy]=stack.pop();stones.push([cx,cy]);for(const [dx,dy] of goDirs){const nx=cx+dx,ny=cy+dy;if(nx<0||ny<0||nx>=GO_N||ny>=GO_N)continue;const v=board[ny][nx],k=`${nx},${ny}`;if(v==null)libs.add(k);else if(v===c&&!seen.has(k)){seen.add(k);stack.push([nx,ny])}}}return {stones,libs}}
function goTry(board,x,y,c,previousHash='',history=[]){if(x<0||y<0||x>=GO_N||y>=GO_N||board[y][x]!=null)return null;const b=clone(board),before=goHash(board);b[y][x]=c;let captured=[];for(const [dx,dy] of goDirs){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=GO_N||ny>=GO_N||b[ny][nx]!==1-c)continue;const g=goGroup(b,nx,ny);if(g.libs.size===0){captured.push(...g.stones);for(const [sx,sy] of g.stones)b[sy][sx]=null}}const own=goGroup(b,x,y);if(own.libs.size===0)return null;const h=goHash(b);if(previousHash&&h===previousHash)return null;if(history?.includes(h))return null;return {board:b,captured,hash:h,before,libs:own.libs.size,group:own.stones.length}}
function goScore(board,komi=6.5){const score=[0,komi],seen=new Set;for(let y=0;y<GO_N;y++)for(let x=0;x<GO_N;x++){const v=board[y][x];if(v!=null){score[v]++;continue}const k=`${x},${y}`;if(seen.has(k))continue;const stack=[[x,y]],region=[],border=new Set;seen.add(k);while(stack.length){const [cx,cy]=stack.pop();region.push([cx,cy]);for(const [dx,dy] of goDirs){const nx=cx+dx,ny=cy+dy;if(nx<0||ny<0||nx>=GO_N||ny>=GO_N)continue;const nv=board[ny][nx],nk=`${nx},${ny}`;if(nv==null&&!seen.has(nk)){seen.add(nk);stack.push([nx,ny])}else if(nv!=null)border.add(nv)}}if(border.size===1)score[[...border][0]]+=region.length}return score}
function goEnd(s){s.scores=goScore(s.board,s.komi);s.winner=s.players[s.scores[0]>s.scores[1]?0:1]||null;s.result='two_passes';s.started=false}
function goAction(s,u,a){if(a.type==='join')return twoJoin(s,u,a.seat);if(a.type==='leave')return twoLeave(s,u);if(a.type==='ready')return twoReady(s,u);if(a.type==='reset'){if(!s.players.includes(u))throw Error('只有本桌玩家可以重开');Object.assign(s,createGo(),{players:s.players.slice(),ready:s.players.map(isBot)});twoMaybeStart(s);return}const pi=s.players.indexOf(u);if(pi<0)throw Error('请先入座');if(!s.started)throw Error('双方准备后才能开始');if(s.turn!==pi)throw Error('还没轮到你');if(a.type==='resign'){s.winner=s.players[1-pi];s.result='resign';s.started=false;s.finishedAt=Date.now();s.turnStartedAt=0;return}if(a.type==='pass'){s.passes++;s.last={pass:true,side:pi};if(s.passes>=2){goEnd(s);s.finishedAt=Date.now();s.turnStartedAt=0;return}s.turn=1-s.turn;s.turnStartedAt=Date.now();return}if(a.type==='place'){const x=+a.x,y=+a.y,r=goTry(s.board,x,y,pi,s.previousHash,s.history||[]);if(!r)throw Error('这里不能落子（占用 / 自杀 / 全局同形重复）');s.previousHash=r.before;s.board=r.board;s.history=[...(s.history||[]),r.hash];s.captures[pi]+=r.captured.length;s.last={x,y,side:pi,captured:r.captured.length};s.passes=0;s.turn=1-s.turn;s.turnStartedAt=Date.now();return}throw Error('未知围棋操作')}
function goCandidates(s,side){const out=[];let stones=0;for(let y=0;y<GO_N;y++)for(let x=0;x<GO_N;x++)if(s.board[y][x]!=null)stones++;for(let y=0;y<GO_N;y++)for(let x=0;x<GO_N;x++){if(s.board[y][x]!=null)continue;const r=goTry(s.board,x,y,side,s.previousHash,s.history||[]);if(!r)continue;let adjOpp=0,adjMine=0,oppAtari=0,rescue=0,cut=0;const seenOwn=new Set,seenOpp=new Set;for(const [dx,dy] of goDirs){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=GO_N||ny>=GO_N)continue;if(s.board[ny][nx]===1-side){adjOpp++;const g=goGroup(s.board,nx,ny),key=g.stones.map(z=>z.join(',')).sort().join('|');if(!seenOpp.has(key)){seenOpp.add(key);if(g.libs.size===1)oppAtari+=g.stones.length;if(g.libs.size===2)cut+=g.stones.length*.35}}else if(s.board[ny][nx]===side){adjMine++;const g=goGroup(s.board,nx,ny),key=g.stones.map(z=>z.join(',')).sort().join('|');if(!seenOwn.has(key)){seenOwn.add(key);if(g.libs.size===1)rescue+=g.stones.length}}}const mid=(GO_N-1)/2,center=mid*2-(Math.abs(x-mid)+Math.abs(y-mid)),edge=Math.min(x,y,GO_N-1-x,GO_N-1-y);let score=r.captured.length*120+oppAtari*34+rescue*42+cut*8+r.libs*5+adjMine*6+adjOpp*3+center*(stones<45?.75:.18)+edge*(stones<35?.75:0);if(r.libs===1&&r.captured.length===0)score-=70;if(x===0||y===0||x===GO_N-1||y===GO_N-1)score-=stones<40?16:3;out.push({x,y,score,r})}return out.sort((a,b)=>b.score-a.score)}
function goBotMove(s){const side=s.turn,cands=goCandidates(s,side);if(!cands.length)return {type:'pass'};let best=cands[0],bv=-Infinity;for(const c of cands.slice(0,18)){const ns={...s,board:c.r.board,previousHash:c.r.before,history:[...(s.history||[]),c.r.hash],turn:1-side,captures:s.captures.slice()},opps=goCandidates(ns,1-side).slice(0,10);let worst=0;if(opps.length){worst=Infinity;for(const o of opps){const os={...ns,board:o.r.board,previousHash:o.r.before,history:[...(ns.history||[]),o.r.hash],turn:side},reply=goCandidates(os,side)[0],line=c.score-o.score*.78+(reply?.score||0)*.34;worst=Math.min(worst,line)}}else worst=c.score+30;const territory=goScore(c.r.board,s.komi),territoryEdge=(territory[side]-territory[1-side])*.4,v=worst+territoryEdge;if(v>bv){bv=v;best=c}}const occupied=s.board.flat().filter(x=>x!=null).length;if(best.score<-20&&occupied>220)return {type:'pass'};return {type:'place',x:best.x,y:best.y}}

// ---------------- UNO (classic 108-card rules + placement finish) ----------------
const UNO_COLORS=['R','Y','G','B'];
function unoDeck(){const d=[];for(const c of UNO_COLORS){d.push({c,v:'0'});for(let n=1;n<=9;n++)for(let k=0;k<2;k++)d.push({c,v:String(n)});for(const v of ['skip','reverse','draw2'])for(let k=0;k<2;k++)d.push({c,v})}for(let k=0;k<4;k++){d.push({c:'W',v:'wild'});d.push({c:'W',v:'wild4'})}return d.map((x,i)=>({...x,id:`${x.c}${x.v}-${i}`}))}
export function createUno(){return seatCreate('uno',4,{deck:[],discard:[],currentColor:'R',direction:1,message:'等待 2~4 位玩家',roundNo:1,drawnSeat:null,drawnIndex:null,unoVulnerableSeat:null,pendingWild4:null,pendingWinner:null,matchWinner:null,finishOrder:[],placements:[],participantCount:0,lastPlaySeat:null,lastChosenColor:null})}
function unoRefill(s){if(s.deck.length)return;if(s.discard.length<=1)return;const top=s.discard.pop();s.deck=shuffle(s.discard.splice(0));s.discard=[top]}
function unoDraw(s,n=1){const out=[];for(let i=0;i<n;i++){unoRefill(s);if(s.deck.length)out.push(s.deck.pop())}return out}
function unoPlayable(card,s){const top=s.discard.at(-1);return card.c==='W'||card.c===s.currentColor||card.v===top?.v}
function unoActive(p){return !!(p&&!p.finished)}
function unoActiveCount(s){return s.seats.filter(unoActive).length}
function unoStep(s,from,steps=1){let i=from;for(let k=0;k<steps;k++){let found=false;for(let n=1;n<=s.seats.length;n++){const j=(i+s.direction*n+s.seats.length*10)%s.seats.length;if(unoActive(s.seats[j])){i=j;found=true;break}}if(!found)return -1}return i}
function unoCompletePlacements(s){const remain=[];for(let i=0;i<s.seats.length;i++)if(unoActive(s.seats[i]))remain.push(i);for(const i of remain){const p=s.seats[i];p.finished=true;p.result=`第 ${s.finishOrder.length+1} 名`;s.finishOrder.push(i)}s.placements=s.finishOrder.slice();s.matchWinner=s.finishOrder[0]??null;s.winner=s.matchWinner!=null?s.seats[s.matchWinner]?.userId||s.seats[s.matchWinner]?.forfeitUserId||null:null;s.phase='result';s.turnSeat=null;s.turnStartedAt=0;s.finishedAt=Date.now();s.message=`UNO 结束 · ${s.finishOrder.map((i,n)=>`${n+1}位：${i+1}号`).join(' · ')}`}
function unoFinishSeat(s,i){const p=s.seats[i];if(!p||p.finished)return;p.finished=true;p.result=`第 ${s.finishOrder.length+1} 名`;s.finishOrder.push(i);p.uno=false;s.unoVulnerableSeat=null;s.message=`${i+1}号位第 ${s.finishOrder.length} 个出完，可以自由退出；其余玩家继续争夺名次`;if(unoActiveCount(s)<=1)return unoCompletePlacements(s);s.turnSeat=unoStep(s,i);s.turnStartedAt=Date.now()}
function unoApplyInitial(s){const top=s.discard.at(-1),first=s.seats.findIndex(unoActive);s.turnSeat=first;if(!top)return;if(top.v==='reverse'){s.direction=-1;s.turnSeat=unoActiveCount(s)===2?unoStep(s,first,1):first}else if(top.v==='skip')s.turnSeat=unoStep(s,first,1);else if(top.v==='draw2'){s.seats[first].hand.push(...unoDraw(s,2));s.turnSeat=unoStep(s,first,1)}}
function unoStart(s){if(occupiedCount(s.seats)===1)autoFillBots(s,4);if(!allReady(s,2))throw Error('至少 2 位玩家且所有真人准备后才能开始');s.matchWinner=null;s.winner=null;s.finishOrder=[];s.placements=[];s.pendingWinner=null;s.pendingWild4=null;s.unoVulnerableSeat=null;s.drawnSeat=null;s.drawnIndex=null;s.lastPlaySeat=null;s.lastChosenColor=null;s.deck=shuffle(unoDeck());s.discard=[];s.participantCount=occupiedCount(s.seats);for(const p of s.seats)if(p){p.hand=unoDraw(s,7);p.result='';p.uno=false;p.finished=false;p.departed=false;p.forfeited=!!p.forfeited}let top;do{top=s.deck.pop()}while(top?.c==='W');s.discard=[top];s.currentColor=top.c;s.direction=1;s.phase='playing';unoApplyInitial(s);s.turnStartedAt=Date.now();s.finishedAt=0;s.message='UNO 排名赛开始：先出完者先获得名次，其余玩家继续'}
function unoAdvance(s,from,steps=1){s.drawnSeat=null;s.drawnIndex=null;s.unoVulnerableSeat=null;s.turnSeat=unoStep(s,from,steps);s.turnStartedAt=Date.now()}
function unoResolveWild4(s,challenger,challenge){const w=s.pendingWild4;if(!w||challenger!==w.target)throw Error('当前没有可处理的 +4');if(challenge){if(w.hadColor){s.seats[w.offender].hand.push(...unoDraw(s,4));s.message='+4 质疑成功：出牌者摸 4，质疑者继续出牌';s.turnSeat=w.target}else{s.seats[w.target].hand.push(...unoDraw(s,6));s.message='+4 质疑失败：质疑者摸 6 并跳过';s.turnSeat=unoStep(s,w.target)}}else{s.seats[w.target].hand.push(...unoDraw(s,4));s.message='接受 +4：摸 4 并跳过';s.turnSeat=unoStep(s,w.target)}s.pendingWild4=null;s.turnStartedAt=Date.now();if(s.pendingWinner!=null){const win=s.pendingWinner;s.pendingWinner=null;unoFinishSeat(s,win)}}
function unoAction(s,u,a){
  if(a.type==='join')return seatJoin(s,u,a.seat);
  if(a.type==='leave'){const i=s.seats.findIndex(x=>x?.userId===u);if(i<0)return;const p=s.seats[i];if(s.phase==='playing'&&p.finished){p.departed=true;s.message=`${i+1}号位已取得第 ${s.finishOrder.indexOf(i)+1} 名并退出，剩余玩家继续`;return}return seatLeave(s,u)}
  if(a.type==='ready')return seatReady(s,u);if(a.type==='start')return unoStart(s);
  const i=s.seats.findIndex(x=>x?.userId===u);if(i<0)throw Error('请先入座');const p=s.seats[i];if(p.finished)throw Error('你已经取得名次，可以自由退出并等待本局结束');
  if(a.type==='uno'&&s.unoVulnerableSeat===i){s.unoVulnerableSeat=null;p.uno=true;s.message=`${i+1}号位喊 UNO!`;return}
  if(a.type==='catch_uno'){const v=s.unoVulnerableSeat;if(v==null||v===i)throw Error('当前没有可抓的 UNO');s.seats[v].hand.push(...unoDraw(s,2));s.unoVulnerableSeat=null;s.message=`抓到 ${v+1}号位漏喊 UNO：罚摸 2 张`;return}
  if(s.pendingWild4){if(i!==s.pendingWild4.target)throw Error('等待下一位处理 +4');if(a.type==='challenge_wild4')return unoResolveWild4(s,i,true);if(a.type==='accept_wild4')return unoResolveWild4(s,i,false);throw Error('请先接受或质疑 +4')}
  if(s.phase!=='playing'||s.turnSeat!==i)throw Error('还没轮到你');if(s.unoVulnerableSeat!=null)s.unoVulnerableSeat=null;
  if(a.type==='timeout'){if(s.drawnSeat===i)return unoAdvance(s,i);p.hand.push(...unoDraw(s,1));return unoAdvance(s,i)}
  if(a.type==='draw'){if(s.drawnSeat===i)throw Error('本回合已经摸过牌');const cards=unoDraw(s,1);p.hand.push(...cards);const idx=p.hand.length-1;if(cards[0]&&unoPlayable(cards[0],s)){s.drawnSeat=i;s.drawnIndex=idx;s.message='摸到可出的牌：可以打这张牌或选择过牌';s.turnStartedAt=Date.now()}else unoAdvance(s,i);return}
  if(a.type==='pass_draw'){if(s.drawnSeat!==i)throw Error('当前没有摸牌后的过牌操作');return unoAdvance(s,i)}
  if(a.type==='play'){
    const idx=Number(a.index);if(!Number.isInteger(idx)||!p.hand[idx])throw Error('牌不存在');if(s.drawnSeat===i&&idx!==s.drawnIndex)throw Error('摸牌后只能打刚摸到的那张牌');const card=p.hand[idx];if(!unoPlayable(card,s))throw Error('这张牌不能出');const previousColor=s.currentColor,hadColor=card.v==='wild4'&&p.hand.some((x,j)=>j!==idx&&x.c===previousColor);p.hand.splice(idx,1);s.discard.push(card);s.lastPlaySeat=i;s.lastChosenColor=card.c==='W'?(UNO_COLORS.includes(a.color)?a.color:null):card.c;s.drawnSeat=null;s.drawnIndex=null;if(card.c==='W'){const color=UNO_COLORS.includes(a.color)?a.color:UNO_COLORS.slice().sort((x,y)=>p.hand.filter(c=>c.c===y).length-p.hand.filter(c=>c.c===x).length)[0];s.currentColor=color;s.lastChosenColor=color}else{s.currentColor=card.c;s.lastChosenColor=card.c};
    const declared=!!a.uno;if(p.hand.length===1){p.uno=declared;s.unoVulnerableSeat=declared?null:i}else{p.uno=false;s.unoVulnerableSeat=null}
    const empty=!p.hand.length;if(card.v==='wild4'){const target=unoStep(s,i);s.pendingWild4={offender:i,target,hadColor,previousColor};s.pendingWinner=empty?i:null;s.turnSeat=target;s.turnStartedAt=Date.now();s.message='Wild Draw Four：下一位可接受或质疑';return}
    if(card.v==='draw2'){const n=unoStep(s,i);if(n>=0)s.seats[n].hand.push(...unoDraw(s,2));if(empty)return unoFinishSeat(s,i);return unoAdvance(s,n)}
    if(empty)return unoFinishSeat(s,i);
    if(card.v==='reverse'){s.direction*=-1;return unoAdvance(s,i,unoActiveCount(s)===2?2:1)}if(card.v==='skip')return unoAdvance(s,i,2);return unoAdvance(s,i)
  }
  throw Error('未知 UNO 操作')
}
function unoBotAction(s,p){const me=s.turnSeat;if(s.pendingWild4&&s.pendingWild4.target===me)return {type:Math.random()<.35?'challenge_wild4':'accept_wild4'};if(s.drawnSeat===me){const c=p.hand[s.drawnIndex];if(c&&unoPlayable(c,s))return {type:'play',index:s.drawnIndex,color:UNO_COLORS[Math.floor(Math.random()*4)],uno:p.hand.length===2};return {type:'pass_draw'}}const playable=p.hand.map((c,i)=>({c,i})).filter(x=>unoPlayable(x.c,s));if(!playable.length)return {type:'draw'};const colorCounts=Object.fromEntries(UNO_COLORS.map(c=>[c,p.hand.filter(x=>x.c===c).length])),next=s.seats[unoStep(s,me)],danger=(next?.hand?.length||next?.handCount||99)<=2;const value=x=>{const c=x.c;let v=Number(c.v)||0;if(c.v==='reverse')v=18;if(c.v==='skip')v=danger?72:30;if(c.v==='draw2')v=danger?90:45;if(c.v==='wild')v=danger?58:26;if(c.v==='wild4')v=danger?110:52;v+=(c.c!=='W'?colorCounts[c.c]*4:0);if(!danger&&c.c==='W'&&p.hand.length>3)v-=28;return v};playable.sort((a,b)=>value(b)-value(a));const pick=playable[0],color=UNO_COLORS.slice().sort((a,b)=>colorCounts[b]-colorCounts[a])[0];return {type:'play',index:pick.i,color,uno:p.hand.length===2}}

// ---------------- 四人立直日麻（独立规则引擎） ----------------
export {mahjongTileName};
export function createMahjong(){return createRiichiState()}
function mjStart(s){if(occupiedCount(s.seats)===1)autoFillBots(s,4);if(occupiedCount(s.seats)<4)throw Error('日麻需要 4 位玩家，可添加 AI 补位');if(!allReady(s,4))throw Error('所有真人准备后才能开始');riichiStartHand(s)}
function mahjongAction(s,u,a){if(a.type==='join')return seatJoin(s,u,a.seat);if(a.type==='leave')return seatLeave(s,u);if(a.type==='ready')return seatReady(s,u);if(a.type==='start')return mjStart(s);return applyRiichiAction(s,u,a)}
function mahjongBotAction(s,p){const i=s.seats.indexOf(p);return riichiBotTurn(s,i)}

// ---------------- Public interface ----------------
export function createExtraGame(kind){if(kind==='go')return createGo();if(kind==='uno')return createUno();if(kind==='mahjong')return createMahjong();if(kind==='doudizhu')return createDoudizhu();return null}
export function applyExtraGameAction(s,u,a){if(s.kind==='go')return goAction(s,u,a);if(s.kind==='uno')return unoAction(s,u,a);if(s.kind==='mahjong')return mahjongAction(s,u,a);if(s.kind==='doudizhu')return applyDoudizhuAction(s,u,a);throw Error('未知扩展游戏')}
export function addExtraBot(s,seat=null){if(!isExtraKind(s?.kind))return null;const humans=s.kind==='go'?s.players.filter(x=>x&&!isBot(x)).length:(s.seats||[]).filter(x=>x&&!x.isBot&&!isBot(x.userId)).length;if(humans<1)throw Error('至少先有一位真人入座后才能添加 AI');if(s.kind==='doudizhu')return addDoudizhuBot(s,seat);const id=botId(s.kind);if(s.kind==='go'){twoJoin(s,id,seat);return id}const i=Number.isInteger(seat)?seat:s.seats.findIndex(x=>!x);if(i<0||i>=s.seats.length||s.seats[i])throw Error('没有空位');s.seats[i]={userId:id,isBot:true,ready:true,hand:[]};return id}
export function removeExtraBot(s,seat=null){if(!isExtraKind(s?.kind))return false;if(s.kind==='doudizhu')return removeDoudizhuBot(s,seat);if(s.kind==='go'){const i=Number.isInteger(seat)?seat:s.players.findIndex(isBot);if(i>=0&&isBot(s.players[i])){s.players[i]=null;s.ready[i]=false;s.started=false;return true}return false}if(s.phase==='playing')throw Error('对局进行中不能移除 AI');const i=Number.isInteger(seat)?seat:s.seats.findIndex(x=>x?.isBot||isBot(x?.userId));if(i>=0&&s.seats[i]?.isBot){s.seats[i]=null;return true}return false}
export function extraHasBot(s){if(!s)return false;if(s.kind==='doudizhu')return doudizhuHasBot(s);if(s.kind==='go')return s.players.some(isBot);return s.seats?.some(x=>x&&(x.isBot||isBot(x.userId)))||false}
export function advanceExtraBots(s,max=120){const humans=!s?0:s.kind==='go'?s.players.filter(x=>x&&!isBot(x)).length:(s.seats||[]).filter(x=>x&&!x.isBot&&!isBot(x.userId)).length;if(humans<1)return;for(let step=0;step<max;step++){if(!s)break;if(s.kind==='go'){const id=s.players[s.turn];if(!s.started||s.winner||!isBot(id))break;const a=goBotMove(s);if(!a)break;goAction(s,id,a);continue}if(s.kind==='uno'){if(s.phase!=='playing')break;const p=s.seats[s.turnSeat];if(!p?.isBot)break;unoAction(s,p.userId,unoBotAction(s,p));continue}if(s.kind==='doudizhu'){advanceDoudizhuBots(s,1);continue}if(s.kind==='mahjong'){if(s.phase==='reaction'&&s.pending){let acted=false;for(const k of Object.keys(s.pending.eligible||{})){const i=+k,p=s.seats[i];if(!p?.isBot||s.pending.responses?.[i])continue;const a=riichiBotReaction(s,i);if(a){mahjongAction(s,p.userId,a);acted=true;if(s.phase!=='reaction')break}}if(acted)continue;break}if(s.phase!=='playing')break;const p=s.seats[s.turnSeat];if(!p?.isBot)break;const a=mahjongBotAction(s,p);if(!a)break;mahjongAction(s,p.userId,a);continue}break}}
export function publicExtraGameState(s,viewerId){if(s?.kind==='mahjong')return publicRiichiState(s,viewerId);if(s?.kind==='doudizhu')return publicDoudizhuState(s,viewerId);const x=clone(s);x.serverNow=Date.now();if(x.kind==='uno'){for(const p of x.seats||[])if(p&&p.userId!==viewerId){p.handCount=p.hand?.length||0;p.hand=(p.hand||[]).map(()=>({hidden:true}))}}if(x.kind==='uno'&&x.pendingWild4)delete x.pendingWild4.hadColor;return x}
export function tickExtraGame(s,now=Date.now()){if(s?.kind==='mahjong')return tickRiichi(s,now);if(s?.kind==='doudizhu')return tickDoudizhu(s,now);let changed=false;if(s?.kind==='go'&&s.started&&s.turnStartedAt&&now-s.turnStartedAt>=(s.turnTimeoutMs||60000)){const side=s.turn;s.winner=s.players[1-side]||null;s.result='time_forfeit';s.started=false;s.finishedAt=now;s.turnStartedAt=0;changed=true}else if(s?.kind==='uno'&&s.phase==='playing'&&s.turnSeat!=null&&s.turnStartedAt&&now-s.turnStartedAt>=(s.turnTimeoutMs||30000)){const p=s.seats[s.turnSeat];if(p&&!p.isBot){try{unoAction(s,p.userId,{type:'timeout'});changed=true}catch{}}}return {changed,forceLeaveUsers:[],autoReset:!!(s?.finishedAt&&now-s.finishedAt>=60000)}}
