// SlimeLounge v0.2.2 - four-player riichi mahjong core.
// Rule profile follows common Mahjong Soul four-player ranked defaults where practical:
// 25,000 start, open tanyao, aka-dora x3, double/triple ron, abortive draws, dealer repeats on win/tenpai.

const BOT_PREFIX='BOT:';
const isBot=v=>typeof v==='string'&&v.startsWith(BOT_PREFIX);
const clone=v=>JSON.parse(JSON.stringify(v));
const ceil100=n=>Math.ceil(n/100)*100;
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
export const MJ_NAMES=['1m','2m','3m','4m','5m','6m','7m','8m','9m','1p','2p','3p','4p','5p','6p','7p','8p','9p','1s','2s','3s','4s','5s','6s','7s','8s','9s','东','南','西','北','白','发','中','赤5m','赤5p','赤5s'];
export const MJ_UNICODE=['🀇','🀈','🀉','🀊','🀋','🀌','🀍','🀎','🀏','🀙','🀚','🀛','🀜','🀝','🀞','🀟','🀠','🀡','🀐','🀑','🀒','🀓','🀔','🀕','🀖','🀗','🀘','🀀','🀁','🀂','🀃','🀆','🀅','🀄','🀋','🀝','🀔'];
export const mahjongTileName=t=>MJ_NAMES[t]||'?';
export const mahjongTileGlyph=t=>MJ_UNICODE[t]||'🀫';
export const RIICHI_RULE_PROFILE={name:'四人半庄 · SlimeLounge 标准',startPoints:25000,returnPoints:30000,akaDora:3,openTanyao:true,atozuke:true,kuikae:false,multipleRon:true,tripleRonAbort:false,abortiveDraws:['九种九牌','四风连打','四杠散了','四家立直'],features:['立直','双立直','一发','振听','立直振听','吃','碰','明杠','暗杠','加杠','抢杠','岭上开花','海底摸月','河底捞鱼','宝牌','里宝牌','赤宝牌','流局听牌罚符','流局满贯','本场','供托','庄家连庄','番符计分','满贯','跳满','倍满','三倍满','役满','双倍役满','立直宣言牌放铳不收供托','南四不足30000西入','加时赛突然死亡','责任払い（大三元 / 大四喜包牌）']};
const RED_MAP={34:4,35:13,36:22};
const norm=t=>RED_MAP[t]??t;
const suit=t=>{t=norm(t);return t<9?0:t<18?1:t<27?2:3};
const num=t=>{t=norm(t);return t<27?t%9+1:0};
const honor=t=>norm(t)>=27;
const terminal=t=>!honor(t)&&(num(t)===1||num(t)===9);
const yaochu=t=>honor(t)||terminal(t);
const green=t=>[19,20,21,23,25,32].includes(norm(t)); // 2s3s4s6s8s + green dragon
const same=t=>norm(t);
const seatIndex=(s,u)=>s.seats.findIndex(x=>x?.userId===u);
const nextSeat=i=>(i+1)%4;
const roundWindTile=s=>27+(s.roundWind||0);
const seatWindTile=(s,i)=>27+((i-(s.dealer||0)+4)%4);
const allMelds=p=>Array.isArray(p?.melds)?p.melds:[];
const isClosed=p=>allMelds(p).every(m=>m.type==='ankan');
const kans=p=>allMelds(p).filter(m=>m.type==='kan'||m.type==='ankan').length;
const allTilesForPlayer=p=>[...(p.hand||[]),...allMelds(p).flatMap(m=>m.tiles||[])];
function counts(tiles){const c=Array(34).fill(0);for(const x of tiles){const t=norm(x);if(t>=0&&t<34)c[t]++}return c}
function makeWall(){const w=[];for(let t=0;t<34;t++){if([4,13,22].includes(t)){for(let k=0;k<3;k++)w.push(t);w.push(t===4?34:t===13?35:36)}else for(let k=0;k<4;k++)w.push(t)}return shuffle(w)}
function doraNext(ind){ind=norm(ind);if(ind<27)return Math.floor(ind/9)*9+(ind%9+1)%9;if(ind>=27&&ind<=30)return 27+(ind-27+1)%4;return 31+(ind-31+1)%3}
function doraTiles(s,ura=false){const src=ura?s.uraIndicators:s.doraIndicators;return (src||[]).map(doraNext)}
function doraCount(tiles,s,ura=false){const ds=doraTiles(s,ura);let n=0;for(const t of tiles)for(const d of ds)if(norm(t)===d)n++;return n}
const akaCount=tiles=>tiles.filter(t=>t>=34&&t<=36).length;

function meldRec(c,need,start=0,path=[],out=[]){if(out.length>128)return out;let i=start;while(i<34&&!c[i])i++;if(i>=34){if(path.length===need)out.push(path.map(x=>({...x})));return out}if(path.length>=need)return out;if(c[i]>=3){c[i]-=3;meldRec(c,need,i,[...path,{type:'triplet',tile:i,open:false}],out);c[i]+=3}if(i<27&&i%9<=6&&c[i+1]&&c[i+2]){c[i]--;c[i+1]--;c[i+2]--;meldRec(c,need,i,[...path,{type:'sequence',tile:i,open:false}],out);c[i]++;c[i+1]++;c[i+2]++}return out}
function standardDecompositions(tiles,openMelds=[]){const need=4-openMelds.length,c=counts(tiles),out=[];if(tiles.length!==need*3+2)return out;for(let p=0;p<34;p++)if(c[p]>=2){c[p]-=2;const melds=meldRec(c,need);c[p]+=2;for(const m of melds)out.push({pair:p,melds:[...openMelds.map(x=>({type:x.type==='chi'?'sequence':'triplet',tile:norm(x.tiles?.[0]??0),open:x.type!=='ankan',kan:x.type==='kan'||x.type==='ankan',raw:x})),...m]})}return out}
function isChiitoi(tiles,openMelds=[]){if(openMelds.length||tiles.length!==14)return false;const c=counts(tiles);return c.filter(x=>x===2).length===7}
function isKokushi(tiles,openMelds=[]){if(openMelds.length||tiles.length!==14)return false;const c=counts(tiles),req=[0,8,9,17,18,26,27,28,29,30,31,32,33];return req.every(i=>c[i])&&req.some(i=>c[i]>=2)}
function kokushiTenpai(tiles){const c=counts(tiles),req=[0,8,9,17,18,26,27,28,29,30,31,32,33];let miss=0,pair=0;for(const i of req){if(!c[i])miss++;if(c[i]>=2)pair++}return miss-(pair?1:0)}
function normalShanten(tiles,openCount=0){const base=counts(tiles);let best=8-openCount*2;function dfs(c,i,m,t,p){while(i<34&&!c[i])i++;if(i>=34){const mm=m+openCount,tt=Math.min(t,4-mm);best=Math.min(best,8-mm*2-tt-p);return}if(m+openCount>4)return;const n=c[i];if(n>=3){c[i]-=3;dfs(c,i,m+1,t,p);c[i]+=3}if(i<27&&i%9<=6&&c[i+1]&&c[i+2]){c[i]--;c[i+1]--;c[i+2]--;dfs(c,i,m+1,t,p);c[i]++;c[i+1]++;c[i+2]++}if(!p&&n>=2){c[i]-=2;dfs(c,i,m,t,1);c[i]+=2}if(t<4&&n>=2){c[i]-=2;dfs(c,i,m,t+1,p);c[i]+=2}if(t<4&&i<27&&i%9<=7&&c[i+1]){c[i]--;c[i+1]--;dfs(c,i,m,t+1,p);c[i]++;c[i+1]++}if(t<4&&i<27&&i%9<=6&&c[i+2]){c[i]--;c[i+2]--;dfs(c,i,m,t+1,p);c[i]++;c[i+2]++}c[i]--;dfs(c,i,m,t,p);c[i]++}dfs(base.slice(),0,0,0,0);return best}
export function riichiShanten(hand,melds=[]){const h=hand.map(norm),open=melds.length;let best=normalShanten(h,open);if(!open){const c=counts(h),pairs=c.filter(n=>n>=2).length,uniq=c.filter(Boolean).length;best=Math.min(best,6-pairs+Math.max(0,7-uniq),kokushiTenpai(h))}return best}
function waitsFor(hand,melds=[]){const out=[];const known=counts([...hand,...melds.flatMap(m=>m.tiles||[])]);for(let t=0;t<34;t++)if(known[t]<4&&isAgari([...hand,t],melds))out.push(t);return out}
function isAgari(hand,melds=[]){return isKokushi(hand,melds)||isChiitoi(hand,melds)||standardDecompositions(hand,melds).length>0}

function sequenceStarts(melds){return melds.filter(m=>m.type==='sequence').map(m=>m.tile).sort((a,b)=>a-b)}
function tripletTiles(melds){return melds.filter(m=>m.type==='triplet').map(m=>m.tile)}
function groupContainsTerminal(m){if(m.type==='triplet')return yaochu(m.tile);const n=num(m.tile);return n===1||n===7}
function allGroupsYaochu(dec){return dec.melds.every(groupContainsTerminal)&&yaochu(dec.pair)}
function noHonorsInGroups(dec){return dec.melds.every(m=>!honor(m.tile))&&!honor(dec.pair)}
function pairValueFu(s,seat,pair){let fu=0;if([31,32,33].includes(pair))fu+=2;if(pair===seatWindTile(s,seat))fu+=2;if(pair===roundWindTile(s))fu+=2;return fu}
function waitFu(dec,winTile){winTile=norm(winTile);if(dec.pair===winTile)return 2;for(const m of dec.melds){if(m.type!=='sequence')continue;const a=m.tile,b=a+1,c=a+2;if(![a,b,c].includes(winTile))continue;const n=num(a);if(winTile===b)return 2;if(n===1&&winTile===c)return 2;if(n===7&&winTile===a)return 2}return 0}
function preWinClosedTiles(tiles,winTile){const a=tiles.map(norm),w=norm(winTile);const i=a.lastIndexOf(w);if(i>=0)a.splice(i,1);return a}
function isKokushi13Wait(tiles,winTile,open=[]){if(open.length)return false;const pre=preWinClosedTiles(tiles,winTile),req=[0,8,9,17,18,26,27,28,29,30,31,32,33],c=counts(pre);return pre.length===13&&req.every(i=>c[i]===1)}
function isPureChuurenWait(tiles,winTile,p){if(!isClosed(p)||allMelds(p).length)return false;const pre=preWinClosedTiles(tiles,winTile);if(pre.length!==13||pre.some(honor))return false;const ss=new Set(pre.map(suit));if(ss.size!==1)return false;const base=[...ss][0]*9,c=counts(pre).slice(base,base+9);return c[0]===3&&c[8]===3&&c.slice(1,8).every(x=>x===1)}
function limitNameFor(han,fu,yakuman=0){if(yakuman)return yakuman===1?'役满':`${yakuman}倍役满`;if(han>=13)return'累计役满';if(han>=11)return'三倍满';if(han>=8)return'倍满';if(han>=6)return'跳满';const raw=fu*Math.pow(2,han+2);if(han>=5||raw>=2000)return'满贯';return''}
function yakumanList(s,seat,p,tiles,dec,ctx){const y=[],all=[...tiles,...allMelds(p).flatMap(m=>m.tiles||[])];if(isKokushi(tiles,allMelds(p)))y.push([isKokushi13Wait(tiles,ctx.winTile,allMelds(p))?'国士无双十三面':'国士无双',isKokushi13Wait(tiles,ctx.winTile,allMelds(p))?2:1]);if(dec){const trips=tripletTiles(dec.melds);if([31,32,33].every(x=>trips.includes(x)))y.push(['大三元',1]);const winds=[27,28,29,30].filter(x=>trips.includes(x));if(winds.length===4)y.push(['大四喜',2]);else if(winds.length===3&&[27,28,29,30].includes(dec.pair))y.push(['小四喜',1]);const allConcealed=dec.melds.every(m=>m.type==='triplet'&&!m.open);if(allConcealed&&(ctx.tsumo||norm(dec.pair)===norm(ctx.winTile)))y.push([norm(dec.pair)===norm(ctx.winTile)?'四暗刻单骑':'四暗刻',norm(dec.pair)===norm(ctx.winTile)?2:1]);if(dec.melds.filter(m=>m.kan).length===4)y.push(['四杠子',1]);}
  if(all.every(honor))y.push(['字一色',1]);if(all.every(terminal))y.push(['清老头',1]);if(all.every(green))y.push(['绿一色',1]);if(isClosed(p)&&tiles.length===14&&allMelds(p).length===0){const suits=new Set(tiles.filter(t=>!honor(t)).map(suit));if(suits.size===1&&!tiles.some(honor)){const cc=counts(tiles),base=[0,9,18].find(x=>cc.slice(x,x+9).some(Boolean));if(base!=null&&base<27){const v=cc.slice(base,base+9);if(v[0]>=3&&v[8]>=3&&v.slice(1,8).every(n=>n>=1)){const pure=isPureChuurenWait(tiles,ctx.winTile,p);y.push([pure?'纯正九莲宝灯':'九莲宝灯',pure?2:1])}}}}
  if(ctx.firstDraw&&ctx.tsumo)y.push([seat===s.dealer?'天和':'地和',1]);return y}
function yakuForDec(s,seat,p,tiles,dec,ctx){const closed=isClosed(p),y=[];const melds=dec?.melds||[];const trips=tripletTiles(melds),seq=sequenceStarts(melds),pair=dec?.pair;const all=[...tiles,...allMelds(p).flatMap(m=>m.tiles||[])].map(norm);const hasHonor=all.some(honor),suits=new Set(all.filter(t=>!honor(t)).map(suit));
  if(closed&&p.riichi)y.push([p.doubleRiichi?'双立直':'立直',p.doubleRiichi?2:1]);if(closed&&p.riichi&&p.ippatsu) y.push(['一发',1]);if(closed&&ctx.tsumo)y.push(['门前清自摸和',1]);if(all.every(t=>!yaochu(t)))y.push(['断幺九',1]);if(ctx.haitei)y.push([ctx.tsumo?'海底摸月':'河底捞鱼',1]);if(ctx.rinshan)y.push(['岭上开花',1]);if(ctx.chankan)y.push(['抢杠',1]);
  for(const d of [31,32,33])if(trips.includes(d))y.push([[31,32,33].indexOf(d)===0?'役牌 白':[31,32,33].indexOf(d)===1?'役牌 发':'役牌 中',1]);if(trips.includes(seatWindTile(s,seat)))y.push(['自风牌',1]);if(trips.includes(roundWindTile(s)))y.push(['场风牌',1]);
  if(dec){const onlySeq=melds.every(m=>m.type==='sequence'),wv=pairValueFu(s,seat,pair),wf=waitFu(dec,ctx.winTile);if(closed&&onlySeq&&!wv&&!wf)y.push(['平和',1]);if(closed){const cnt=new Map;for(const x of seq)cnt.set(x,(cnt.get(x)||0)+1);const pairs=[...cnt.values()].filter(n=>n>=2).length;if(pairs>=2)y.push(['二杯口',3]);else if(pairs===1)y.push(['一杯口',1])}
    const seqSet=new Set(seq);for(let n=0;n<=6;n++)if(seqSet.has(n)&&seqSet.has(9+n)&&seqSet.has(18+n)){y.push(['三色同顺',closed?2:1]);break}for(const b of [0,9,18])if(seqSet.has(b)&&seqSet.has(b+3)&&seqSet.has(b+6)){y.push(['一气通贯',closed?2:1]);break}
    for(let n=0;n<9;n++)if(trips.includes(n)&&trips.includes(9+n)&&trips.includes(18+n)){y.push(['三色同刻',2]);break}
    if(melds.every(m=>m.type==='triplet'))y.push(['对对和',2]);
    // 荣和完成的刻子不算暗刻；若该和牌张也能组成顺子/雀头，则按更有利的合法解释保留暗刻。
    const win=norm(ctx.winTile),ronTripletMustOpen=!ctx.tsumo&&pair!==win&&melds.some(m=>m.type==='triplet'&&!m.open&&norm(m.tile)===win)&&!melds.some(m=>m.type==='sequence'&&[m.tile,m.tile+1,m.tile+2].includes(win));
    let concealedTrips=melds.filter(m=>m.type==='triplet'&&!m.open).length;if(ronTripletMustOpen)concealedTrips=Math.max(0,concealedTrips-1);if(concealedTrips>=3)y.push(['三暗刻',2]);if(melds.filter(m=>m.kan).length>=3)y.push(['三杠子',2]);const dragonTrips=[31,32,33].filter(x=>trips.includes(x));if(dragonTrips.length===2&&[31,32,33].includes(pair))y.push(['小三元',2]);
    const allY=allGroupsYaochu(dec);if(allY){if(noHonorsInGroups(dec))y.push(['纯全带幺九',closed?3:2]);else y.push(['混全带幺九',closed?2:1])}
  }
  if(all.every(yaochu))y.push(['混老头',2]);if(suits.size===1){if(hasHonor)y.push(['混一色',closed?3:2]);else y.push(['清一色',closed?6:5])}return y}
function fuFor(s,seat,p,dec,ctx,yakuNames){if(yakuNames.includes('七对子'))return 25;let fu=20,closed=isClosed(p);if(closed&&!ctx.tsumo)fu+=10;if(ctx.tsumo&&!yakuNames.includes('平和'))fu+=2;if(dec){fu+=pairValueFu(s,seat,dec.pair)+waitFu(dec,ctx.winTile);const win=norm(ctx.winTile),ronTripletMustOpen=!ctx.tsumo&&dec.pair!==win&&dec.melds.some(m=>m.type==='triplet'&&!m.open&&norm(m.tile)===win)&&!dec.melds.some(m=>m.type==='sequence'&&[m.tile,m.tile+1,m.tile+2].includes(win));let openedRonTriplet=false;for(const m of dec.melds){if(m.type!=='triplet')continue;let isOpen=m.open;if(!openedRonTriplet&&ronTripletMustOpen&&!m.open&&norm(m.tile)===win){isOpen=true;openedRonTriplet=true}let f=isOpen?2:4;if(yaochu(m.tile))f*=2;if(m.kan)f*=4;fu+=f}}if(!closed&&fu===20)fu=30;return Math.ceil(fu/10)*10}
function scoreBase(han,fu,yakuman=0){if(yakuman)return 8000*yakuman;if(han>=13)return 8000;if(han>=11)return 6000;if(han>=8)return 4000;if(han>=6)return 3000;let b=fu*Math.pow(2,han+2);if(han>=5||b>=2000)b=2000;return b}
function handScore(s,seat,{tsumo=false,winTile=null,fromSeat=null,rinshan=false,chankan=false,haitei=false,firstDraw=false}={}){const p=s.seats[seat],melds=allMelds(p),tiles=p.hand.slice();if(!tsumo&&winTile!=null)tiles.push(winTile);if(!isAgari(tiles,melds))return null;const ctx={tsumo,winTile:winTile??p.lastDraw,fromSeat,rinshan,chankan,haitei,firstDraw};const decs=standardDecompositions(tiles,melds);if(isChiitoi(tiles,melds))decs.push(null);if(isKokushi(tiles,melds))decs.push(null);let best=null;for(const dec of decs.length?decs:[null]){const yak=yakumanList(s,seat,p,tiles,dec,ctx);let yakuman=yak.reduce((a,x)=>a+x[1],0);let yaku=[];if(!yakuman){if(isChiitoi(tiles,melds))yaku.push(['七对子',2]);yaku.push(...yakuForDec(s,seat,p,tiles,dec,ctx));}
    const all=[...tiles,...melds.flatMap(m=>m.tiles||[])],baseHan=yaku.reduce((a,x)=>a+x[1],0);if(!yakuman&&baseHan<=0)continue;const d=doraCount(all,s,false),aka=akaCount(all),ura=p.riichi?doraCount(all,s,true):0,han=yakuman?0:baseHan+d+aka+ura,fu=yakuman?0:fuFor(s,seat,p,dec,ctx,yaku.map(x=>x[0])),bp=scoreBase(han,fu,yakuman),value=yakuman*1000000+han*10000+fu;if(!best||value>best.value)best={yaku:[...yak,...yaku],yakuman,han,fu,basePoints:bp,dora:d,aka,ura,limitName:limitNameFor(han,fu,yakuman),value,dec}}
  return best}
export function riichiEvaluateHand(s,seat,opts={}){const x=handScore(s,seat,opts);return x?clone(x):null}
function canRon(s,seat,tile,from){const p=s.seats[seat];if(!p||p.temporaryFuriten||p.riichiFuriten)return false;const waits=waitsFor(p.hand,allMelds(p));if(!waits.includes(norm(tile)))return false;if((s.discards[seat]||[]).some(x=>waits.includes(norm(x.tile??x))))return false;return !!handScore(s,seat,{tsumo:false,winTile:tile,fromSeat:from,haitei:s.wall.length===0})}
function canKokushiRobAnkan(s,seat,tile,from){const p=s.seats[seat];if(!p||p.temporaryFuriten||p.riichiFuriten||allMelds(p).length)return false;const waits=waitsFor(p.hand,[]);if(!waits.includes(norm(tile)))return false;if((s.discards[seat]||[]).some(x=>waits.includes(norm(x.tile??x))))return false;return isKokushi([...p.hand,tile],[])}
function callOptions(s,seat,discarder,tile){const p=s.seats[seat],opts=[];if(!p||p.riichi)return canRon(s,seat,tile,discarder)?[{kind:'ron'}]:[];if(canRon(s,seat,tile,discarder))opts.push({kind:'ron'});const t=norm(tile),ids=p.hand.map((x,i)=>norm(x)===t?i:-1).filter(i=>i>=0);if(ids.length>=3)opts.push({kind:'kan',indices:ids.slice(0,3)});if(ids.length>=2)opts.push({kind:'pon',indices:ids.slice(0,2)});if(seat===nextSeat(discarder)&&t<27){const n=t%9;for(const off of [-2,-1,0]){const a=t+off;if(a<0||Math.floor(a/9)!==Math.floor(t/9)||a%9>6)continue;const need=[a,a+1,a+2].filter(x=>x!==t),idx=[];let ok=true,used=new Set;for(const q of need){const z=p.hand.findIndex((x,i)=>norm(x)===q&&!used.has(i));if(z<0){ok=false;break}idx.push(z);used.add(z)}if(ok)opts.push({kind:'chi',indices:idx,tiles:[a,a+1,a+2]})}}
  return opts}
function visibleTiles(s){return [...s.discards.flat().map(x=>x.tile??x),...s.seats.flatMap(p=>allMelds(p).flatMap(m=>m.tiles||[])),...(s.doraIndicators||[])]}
function ukeire(hand,melds,s){const sh=riichiShanten(hand,melds),known=counts([...hand,...visibleTiles(s)]);let n=0;for(let t=0;t<34;t++)if(known[t]<4&&riichiShanten([...hand,t],melds)<sh)n+=4-known[t];return n}
function danger(tile,s,seat){tile=norm(tile);let d=0;for(let r=0;r<4;r++){if(r===seat||!s.seats[r]?.riichi)continue;const river=(s.discards[r]||[]).map(x=>norm(x.tile??x));if(river.includes(tile))continue;if(tile>=27){d+=Math.max(2,20-river.filter(x=>x===tile).length*5);continue}const n=tile%9+1;let x=(n===1||n===9)?7:(n===2||n===8)?12:18;if([n-3,n+3].some(k=>k>=1&&k<=9&&river.includes(Math.floor(tile/9)*9+k-1)))x-=6;d+=x}return d}
function bestDiscard(s,seat){const p=s.seats[seat],vis=visibleTiles(s);let best=null;for(let i=0;i<p.hand.length;i++){if(p.riichi&&p.lastDraw!=null&&i!==p.hand.lastIndexOf(p.lastDraw))continue;const h=p.hand.slice(),tile=h.splice(i,1)[0];if(p.forbiddenDiscards?.includes(norm(tile)))continue;const sh=riichiShanten(h,allMelds(p)),uk=ukeire(h,allMelds(p),s),dg=danger(tile,s,seat),def=s.seats.some((x,j)=>j!==seat&&x?.riichi)?dg*3.5:0,val=-sh*130+uk*3-def+(yaochu(tile)?2:0);if(!best||val>best.val)best={index:i,tile,sh,uk,dg,val}}return best}

function createSeatState(p){p.hand=[];p.melds=[];p.result='';p.pao={};p.riichi=false;p.doubleRiichi=false;p.ippatsu=false;p.temporaryFuriten=false;p.riichiFuriten=false;p.lastDraw=null;p.lastDrawSource=null;p.firstTurn=true;p.discardCount=0;p.kans=0;p.ready=p.isBot||isBot(p.userId)||!!p.ready}
export function createRiichiState(){return {kind:'mahjong',seats:Array(4).fill(null),phase:'waiting',wall:[],deadWall:[],discards:[[],[],[],[]],points:[25000,25000,25000,25000],dealer:0,roundWind:0,handNo:1,honba:0,kyotaku:0,doraIndicators:[],uraIndicators:[],turnSeat:null,turnStartedAt:0,turnTimeoutMs:30000,lastDiscard:null,pending:null,callOccurred:false,totalKans:0,winner:null,winners:[],message:'等待四人入座（可 AI 补位）',resultDetail:null,matchEnded:false,allLastRepeats:0,startedAt:0,finishedAt:0}}
export function riichiStartHand(s){const w=makeWall();s.deadWall=w.splice(-14);s.wall=w;s.discards=[[],[],[],[]];s.doraIndicators=[s.deadWall[4]];s.uraIndicators=[s.deadWall[5]];s.pending=null;s.lastDiscard=null;s.callOccurred=false;s.totalKans=0;s.winner=null;s.winners=[];s.resultDetail=null;s.matchEnded=false;for(const p of s.seats)if(p)createSeatState(p);for(let r=0;r<13;r++)for(let i=0;i<4;i++)s.seats[i].hand.push(s.wall.pop());for(const p of s.seats)p.hand.sort((a,b)=>norm(a)-norm(b)||a-b);s.turnSeat=s.dealer;s.phase='playing';s.startedAt=Date.now();s.finishedAt=0;drawTile(s,s.dealer,true);s.message=`${s.roundWind===0?'东':'南'}${s.handNo}局 ${s.honba}本场 · 牌局开始`}
function drawTile(s,seat,first=false,rinshan=false){const p=s.seats[seat];if(!p)return;if(!s.wall.length&&!rinshan)return exhaustiveDraw(s);const tile=rinshan?s.deadWall.pop():s.wall.pop();p.hand.push(tile);p.hand.sort((a,b)=>norm(a)-norm(b)||a-b);p.lastDraw=tile;p.lastDrawSource=rinshan?'rinshan':'wall';p.temporaryFuriten=false;s.turnSeat=seat;s.turnStartedAt=Date.now();s.phase='playing';s.message=`${seat+1}号位摸牌`;if(first)p.firstDraw=true}
function cancelIppatsu(s){for(const p of s.seats)if(p)p.ippatsu=false}
function makePending(s,discarder,tile,abortReason=''){const eligible={};for(let n=1;n<4;n++){const j=(discarder+n)%4,o=callOptions(s,j,discarder,tile);if(o.length)eligible[j]=o}if(!Object.keys(eligible).length){if(abortReason)return abortiveDraw(s,abortReason);drawTile(s,nextSeat(discarder));return}s.pending={discarder,tile,eligible,responses:{},expiresAt:Date.now()+8500,abortReason};s.phase='reaction';s.message=abortReason?'等待荣和 / 鸣牌响应 · 若无人响应则途中流局':'等待鸣牌 / 荣和响应'}
function allPendingDone(s){return s.pending&&Object.keys(s.pending.eligible).every(k=>s.pending.responses[k])}
function resolvePending(s){const p=s.pending;if(!p)return;for(const [k,o] of Object.entries(p.eligible)){const seat=+k,r=p.responses[k];if(!r&&o.some(x=>x.kind==='ron'))s.seats[seat].temporaryFuriten=true;if(r?.kind==='pass'&&o.some(x=>x.kind==='ron')){s.seats[seat].temporaryFuriten=true;if(s.seats[seat].riichi)s.seats[seat].riichiFuriten=true}}
  const baseSeat=['kakan','ankan'].includes(p.kind)?p.actor:p.discarder;const rons=Object.entries(p.responses).filter(([,r])=>r?.kind==='ron').map(([k])=>+k).sort((a,b)=>(a-baseSeat+4)%4-(b-baseSeat+4)%4);if(rons.length){s.pending=null;return settleRon(s,rons,baseSeat,p.tile,['kakan','ankan'].includes(p.kind)?{chankan:true}: {})}
  if(p.kind==='kakan'){s.pending=null;return finalizeKakan(s,p.actor,p.meldIndex,p.tile)}if(p.kind==='ankan'){s.pending=null;return finalizeAnkan(s,p.actor,p.tile)}
  const calls=Object.entries(p.responses).filter(([,r])=>['kan','pon','chi'].includes(r?.kind)).map(([k,r])=>({seat:+k,...r}));calls.sort((a,b)=>{const pri={kan:2,pon:2,chi:1};return pri[b.kind]-pri[a.kind]||((a.seat-p.discarder+4)%4)-((b.seat-p.discarder+4)%4)});if(calls.length){const c=calls[0];s.pending=null;return executeCall(s,c.seat,p.discarder,p.tile,c)}s.pending=null;if(p.abortReason)return abortiveDraw(s,p.abortReason);drawTile(s,nextSeat(p.discarder))}
function markPaoAfterOpenCall(p,from,type,tile){if(!['pon','kan'].includes(type)||from==null)return;p.pao||={};const openTripTiles=(p.melds||[]).filter(m=>['pon','kan'].includes(m.type)).map(m=>norm(m.called??m.tiles?.[0]));const t=norm(tile);if([31,32,33].includes(t)&&[31,32,33].every(x=>openTripTiles.includes(x))&&p.pao.daisangen==null)p.pao.daisangen=from;if([27,28,29,30].includes(t)&&[27,28,29,30].every(x=>openTripTiles.includes(x))&&p.pao.daisuushi==null)p.pao.daisuushi=from}
function executeCall(s,seat,from,tile,c){const p=s.seats[seat],idx=(c.indices||[]).slice().sort((a,b)=>b-a),picked=[];for(const i of idx){if(!p.hand[i]&&p.hand[i]!==0)throw Error('鸣牌索引失效');picked.push(p.hand.splice(i,1)[0])}const type=c.kind==='kan'?'kan':c.kind==='pon'?'pon':'chi',tiles=[tile,...picked].sort((a,b)=>norm(a)-norm(b));p.melds.push({type,tiles,from,called:tile});markPaoAfterOpenCall(p,from,type,tile);s.callOccurred=true;cancelIppatsu(s);const river=s.discards[from];if(river?.length)river[river.length-1].called=true;if(type==='kan'){p.kans++;s.totalKans++;revealKanDora(s);if(s.totalKans>=4&&s.seats.filter(x=>x?.kans).length>1)return abortiveDraw(s,'四杠散了');drawTile(s,seat,false,true)}else{const t=norm(tile),forbid=new Set([t]);if(type==='chi'){const a=Math.min(...tiles.map(norm)),z=Math.max(...tiles.map(norm));if(t===a&&z+1<27&&Math.floor((z+1)/9)===Math.floor(a/9))forbid.add(z+1);if(t===z&&a-1>=0&&Math.floor((a-1)/9)===Math.floor(z/9))forbid.add(a-1)}p.forbiddenDiscards=[...forbid];s.turnSeat=seat;s.phase='playing';p.lastDraw=null;s.turnStartedAt=Date.now();s.message=`${seat+1}号位 ${type==='pon'?'碰':'吃'} · 请打牌（禁止食替）`}}
function finalizeAnkan(s,seat,tile){const p=s.seats[seat],t=norm(tile),ids=p.hand.map((x,i)=>norm(x)===t?i:-1).filter(i=>i>=0);if(ids.length!==4)throw Error('暗杠状态失效');const actual=[];for(const i of ids.sort((a,b)=>b-a))actual.push(p.hand.splice(i,1)[0]);p.melds.push({type:'ankan',tiles:actual.reverse(),from:seat,called:t});p.kans++;s.totalKans++;s.callOccurred=true;cancelIppatsu(s);revealKanDora(s);if(s.totalKans>=4&&s.seats.filter(x=>x?.kans).length>1)return abortiveDraw(s,'四杠散了');drawTile(s,seat,false,true);s.message=`${seat+1}号位 暗杠 · 岭上摸牌`}
function finalizeKakan(s,seat,meldIndex,tile){const p=s.seats[seat],m=p.melds?.[meldIndex];if(!m||m.type!=='pon'||norm(m.called??m.tiles?.[0])!==norm(tile))throw Error('加杠状态失效');const i=p.hand.findIndex(x=>norm(x)===norm(tile));if(i<0)throw Error('没有可加杠的第四张牌');const actual=p.hand.splice(i,1)[0];m.type='kan';m.added=true;m.tiles=[...(m.tiles||[]),actual];p.kans++;s.totalKans++;s.callOccurred=true;cancelIppatsu(s);revealKanDora(s);if(s.totalKans>=4&&s.seats.filter(x=>x?.kans).length>1)return abortiveDraw(s,'四杠散了');drawTile(s,seat,false,true);s.message=`${seat+1}号位 加杠 · 岭上摸牌`}
function revealKanDora(s){const idx=4+s.doraIndicators.length*2;if(s.deadWall[idx]!=null)s.doraIndicators.push(s.deadWall[idx]);if(s.deadWall[idx+1]!=null)s.uraIndicators.push(s.deadWall[idx+1])}
function checkFourWinds(s){if(s.callOccurred)return false;if(s.discards.some(x=>x.length!==1))return false;const t=s.discards[0][0]?.tile;if(![27,28,29,30].includes(norm(t)))return false;return s.discards.every(r=>norm(r[0]?.tile)===norm(t))}
function checkFourRiichi(s){return s.seats.every(p=>p?.riichi)}
function discard(s,seat,index,declareRiichi=false){const p=s.seats[seat];if(s.phase!=='playing'||s.turnSeat!==seat)throw Error('还没轮到你');if(!Number.isInteger(index)||index<0||index>=p.hand.length)throw Error('牌不存在');if(p.riichi&&p.lastDraw!=null&&index!==p.hand.lastIndexOf(p.lastDraw))throw Error('立直后只能摸切（暗杠除外）');const h=p.hand.slice(),tile=h.splice(index,1)[0];if(p.forbiddenDiscards?.includes(norm(tile)))throw Error('食替禁止：本巡不能打出这张牌');if(declareRiichi){if(p.riichi)throw Error('已经立直');if(!isClosed(p))throw Error('副露后不能立直');if(s.points[seat]<1000)throw Error('点数不足');if(s.wall.length<4)throw Error('牌山不足，不能立直');if(riichiShanten(h,allMelds(p))!==0)throw Error('这张牌打出后不是听牌');p.riichi=true;p.doubleRiichi=p.firstTurn&&!s.callOccurred;p.ippatsu=true;s.points[seat]-=1000;s.kyotaku++;}
  p.hand=h;p.lastDraw=null;p.lastDrawSource=null;p.discardCount++;p.firstTurn=false;p.forbiddenDiscards=[];s.discards[seat].push({tile,riichi:declareRiichi,called:false});s.lastDiscard={seat,tile,riichi:declareRiichi};if(p.riichi&&!declareRiichi)p.ippatsu=false;const abortReason=checkFourWinds(s)?'四风连打':checkFourRiichi(s)?'四家立直':'';makePending(s,seat,tile,abortReason)}
function canTsumo(s,seat){const p=s.seats[seat],rinshan=p.lastDrawSource==='rinshan';return !!handScore(s,seat,{tsumo:true,winTile:p.lastDraw,rinshan,haitei:!rinshan&&s.wall.length===0,firstDraw:p.firstTurn&&p.discardCount===0})}
function transferPoints(s,from,to,amount){amount=Math.max(0,Math.round(amount));if(!amount||from===to)return;s.points[from]-=amount;s.points[to]+=amount}
function regularPaymentBase(s,seat,b,ctx,withHonba=true){const dealer=seat===s.dealer;if(ctx.tsumo){if(dealer){const pay=ceil100(b*2)+(withHonba?s.honba*100:0);for(let i=0;i<4;i++)if(i!==seat)transferPoints(s,i,seat,pay)}else{for(let i=0;i<4;i++)if(i!==seat){const pay=ceil100(b*(i===s.dealer?2:1))+(withHonba?s.honba*100:0);transferPoints(s,i,seat,pay)}}}else{const pay=ceil100(b*(dealer?6:4))+(withHonba?s.honba*300:0);transferPoints(s,ctx.fromSeat,seat,pay)}}
function paoForScore(s,seat,score){if(!score?.yakuman)return null;const p=s.seats[seat],names=new Set((score.yaku||[]).map(x=>x[0]));if(names.has('大三元')&&p?.pao?.daisangen!=null)return {seat:p.pao.daisangen,units:1,reason:'大三元'};if(names.has('大四喜')&&p?.pao?.daisuushi!=null)return {seat:p.pao.daisuushi,units:2,reason:'大四喜'};return null}
function settlePayment(s,seat,score,ctx){const pao=paoForScore(s,seat,score);if(!pao){regularPaymentBase(s,seat,score.basePoints,ctx,true);return null}const paoBase=Math.min(score.basePoints,8000*pao.units),normalBase=Math.max(0,score.basePoints-paoBase),dealer=seat===s.dealer;if(normalBase>0)regularPaymentBase(s,seat,normalBase,ctx,false);const full=ceil100(paoBase*(dealer?6:4));if(ctx.tsumo){transferPoints(s,pao.seat,seat,full+s.honba*300)}else if(ctx.fromSeat===pao.seat){transferPoints(s,pao.seat,seat,full+s.honba*300)}else{const half=ceil100(full/2);transferPoints(s,pao.seat,seat,half);transferPoints(s,ctx.fromSeat,seat,full-half+s.honba*300)}return pao}
function awardKyotaku(s,seat){if(s.kyotaku){s.points[seat]+=s.kyotaku*1000;s.kyotaku=0}}
function settleTsumo(s,seat,flags={}){const p=s.seats[seat],rinshan=flags.rinshan??p.lastDrawSource==='rinshan';const sc=handScore(s,seat,{tsumo:true,winTile:p.lastDraw,rinshan,haitei:!rinshan&&s.wall.length===0,firstDraw:p.firstTurn&&p.discardCount===0,...flags});if(!sc)throw Error('当前牌型没有役，不能自摸');const pao=settlePayment(s,seat,sc,{tsumo:true});awardKyotaku(s,seat);s.winner=s.seats[seat].userId;s.winners=[s.winner];s.seats[seat].result=`自摸 ${scoreText(sc)}`;s.resultDetail={type:'tsumo',seat,score:sc,pao:pao||null};finishHand(s,[seat])}
function cancelRiichiDeclarationOnRon(s,from,flags={}){if(flags.chankan)return;const d=s.lastDiscard,p=s.seats[from];if(!d?.riichi||d.seat!==from||!p?.riichi)return;p.riichi=false;p.doubleRiichi=false;p.ippatsu=false;s.points[from]+=1000;s.kyotaku=Math.max(0,(s.kyotaku||0)-1)}
function settleRon(s,winners,from,tile,flags={}){cancelRiichiDeclarationOnRon(s,from,flags);const details=[];for(const seat of winners){const sc=handScore(s,seat,{tsumo:false,winTile:tile,fromSeat:from,haitei:!flags.chankan&&s.wall.length===0,...flags});if(!sc)continue;const pao=settlePayment(s,seat,sc,{tsumo:false,fromSeat:from});details.push({seat,score:sc,pao:pao||null});s.seats[seat].result=`荣和 ${scoreText(sc)}`}if(!details.length){drawTile(s,nextSeat(from));return}awardKyotaku(s,details[0].seat);s.winners=details.map(x=>s.seats[x.seat].userId);s.winner=s.winners[0];s.resultDetail={type:'ron',from,tile,winners:details};finishHand(s,details.map(x=>x.seat))}
function scoreText(sc){if(sc.yakuman)return `${sc.limitName||`${sc.yakuman}倍役满`} · ${sc.yaku.map(x=>x[0]).join(' / ')}`;return `${sc.han}番 ${sc.fu}符${sc.limitName?` · ${sc.limitName}`:''} · ${sc.yaku.map(x=>`${x[0]}${x[1]}番`).join(' / ')}${sc.dora?` · 宝牌${sc.dora}`:''}${sc.aka?` · 赤${sc.aka}`:''}${sc.ura?` · 里宝${sc.ura}`:''}`}
function tenpaiSeats(s){const out=[];for(let i=0;i<4;i++)if(riichiShanten(s.seats[i].hand,allMelds(s.seats[i]))===0)out.push(i);return out}
function nagashiSeats(s){const out=[];for(let i=0;i<4;i++){const r=s.discards[i]||[];if(r.length&&r.every(x=>yaochu(x.tile)&&!x.called))out.push(i)}return out}
function exhaustiveDraw(s){const nag=nagashiSeats(s),ten=tenpaiSeats(s);if(nag.length){for(const i of nag){const sc={basePoints:2000};settlePayment(s,i,sc,{tsumo:true});s.seats[i].result='流局满贯'}s.resultDetail={type:'nagashi',seats:nag,tenpai:ten};return finishHand(s,nag,true,ten.includes(s.dealer))}const n=ten.length;if(n>0&&n<4){const gain=3000/n,loss=3000/(4-n);for(let i=0;i<4;i++)s.points[i]+=ten.includes(i)?gain:-loss}for(let i=0;i<4;i++)s.seats[i].result=ten.includes(i)?'流局听牌':'流局未听';s.resultDetail={type:'exhaustive',tenpai:ten};finishHand(s,ten,true,ten.includes(s.dealer))}
function abortiveDraw(s,reason){s.resultDetail={type:'abortive',reason};s.message=`途中流局 · ${reason}`;s.honba++;s.phase='result';s.turnSeat=null;s.turnStartedAt=0;s.pending=null;s.finishedAt=Date.now()}
function topSeatIndex(s){let best=0;for(let i=1;i<4;i++)if(s.points[i]>s.points[best])best=i;return best}
function finishMatch(s){if(s.kyotaku){const top=topSeatIndex(s);s.points[top]+=s.kyotaku*1000;s.kyotaku=0}s.matchEnded=true;s.message=`半庄结束 · ${s.points.map((x,i)=>`${i+1}家 ${Math.round(x)}`).join(' / ')}`}
function advanceDealer(s){s.honba=0;s.allLastRepeats=0;s.dealer=(s.dealer+1)%4;s.handNo++;if(s.handNo>4){s.handNo=1;s.roundWind++}}
function finishHand(s,winnerSeats=[],draw=false,dealerDrawTenpai=null){const dealerContinues=draw?(dealerDrawTenpai??winnerSeats.includes(s.dealer)):winnerSeats.includes(s.dealer),round=s.roundWind,hand=s.handNo,top=topSeatIndex(s),target=(RIICHI_RULE_PROFILE.returnPoints||30000),reached=s.points[top]>=target,busted=s.points.some(x=>x<0);s.phase='result';s.turnSeat=null;s.turnStartedAt=0;s.pending=null;s.finishedAt=Date.now();if(busted)return finishMatch(s);if(round>=1&&hand===4&&dealerContinues){s.allLastRepeats=(s.allLastRepeats||0)+1;if(s.allLastRepeats>=4)return finishMatch(s)}
  // 雀魂式半庄：南四无人达到返还点则西入；西入后达到目标点进入突然死亡，最多进行到西四。
  if(round===1&&hand===4){if(dealerContinues){if(top===s.dealer&&reached)return finishMatch(s);s.honba++}else{if(reached)return finishMatch(s);advanceDealer(s)}}
  else if(round===2){if(hand===4)return finishMatch(s);if(dealerContinues){if(top===s.dealer&&reached)return finishMatch(s);s.honba++}else{if(reached)return finishMatch(s);advanceDealer(s)}}
  else{if(dealerContinues)s.honba++;else advanceDealer(s)}
  s.message=`本局结束 · ${s.resultDetail?.type||''} · 下一局 ${s.roundWind===0?'东':s.roundWind===1?'南':'西'}${s.handNo}局 ${s.honba}本场`}
export function riichiNextHand(s){if(s.phase!=='result')throw Error('本局尚未结束');if(s.matchEnded){const fresh=createRiichiState(),seats=s.seats;Object.assign(s,fresh,{seats,points:[25000,25000,25000,25000]});for(const p of s.seats)if(p){p.ready=p.isBot||isBot(p.userId);p.hand=[];p.melds=[]}return}s.phase='waiting';for(const p of s.seats)if(p){p.ready=p.isBot||isBot(p.userId);p.hand=[];p.melds=[];p.result=''}s.message='等待所有真人准备下一局'}
function ankanOptions(p){const c=counts(p.hand),out=[];for(let t=0;t<34;t++)if(c[t]===4){if(!p.riichi){out.push(t);continue}if(p.lastDraw==null||norm(p.lastDraw)!==t)continue;const base=p.hand.slice(),drawIndex=base.lastIndexOf(p.lastDraw);if(drawIndex<0)continue;base.splice(drawIndex,1);const before=waitsFor(base,allMelds(p)).join(',');const afterHand=p.hand.slice();for(let n=0;n<4;n++){const i=afterHand.findIndex(x=>norm(x)===t);if(i>=0)afterHand.splice(i,1)}const afterMelds=[...allMelds(p),{type:'ankan',tiles:[t,t,t,t],from:null,called:t}],after=waitsFor(afterHand,afterMelds).join(',');if(before&&before===after)out.push(t)}return out}
function kakanOptions(p){const out=[];for(let i=0;i<(p.melds||[]).length;i++){const m=p.melds[i];if(m.type!=='pon')continue;const t=norm(m.called??m.tiles?.[0]);if(p.hand.some(x=>norm(x)===t))out.push({meldIndex:i,tile:t})}return out}
function kyuushuAvailable(s,seat){const p=s.seats[seat];if(!p.firstTurn||s.callOccurred)return false;return new Set(p.hand.filter(yaochu).map(norm)).size>=9}
export function riichiTurnOptions(s,seat){const p=s.seats[seat];if(!p||s.phase!=='playing'||s.turnSeat!==seat)return {};const tsumo=canTsumo(s,seat),ankan=ankanOptions(p),kakan=p.riichi?[]:kakanOptions(p),kyuushu=kyuushuAvailable(s,seat),riichiDiscards=[];if(!p.riichi&&isClosed(p)&&s.points[seat]>=1000&&s.wall.length>=4){for(let i=0;i<p.hand.length;i++){const h=p.hand.slice();h.splice(i,1);if(riichiShanten(h,allMelds(p))===0)riichiDiscards.push(i)}}return {tsumo,ankan,kakan,kyuushu,riichiDiscards}}
export function riichiReactionOptions(s,seat){if(s.phase!=='reaction'||!s.pending)return[];return clone(s.pending.eligible[seat]||[])}
export function applyRiichiAction(s,u,a){const seat=seatIndex(s,u);if(seat<0)throw Error('请先入座');const p=s.seats[seat];if(a.type==='tsumo'){if(s.turnSeat!==seat||s.phase!=='playing')throw Error('现在不能自摸');return settleTsumo(s,seat)}if(a.type==='discard'||a.type==='riichi_discard')return discard(s,seat,Number(a.index),a.type==='riichi_discard');if(a.type==='claim'){if(s.phase!=='reaction'||!s.pending?.eligible?.[seat])throw Error('现在没有可响应的鸣牌');const opt=(s.pending.eligible[seat]||[]).find((x,i)=>x.kind===a.kind&&(a.optionIndex==null||i===Number(a.optionIndex)));if(a.kind!=='pass'&&!opt)throw Error('该鸣牌当前不可用');s.pending.responses[seat]=a.kind==='pass'?{kind:'pass'}:{...opt};if(allPendingDone(s))resolvePending(s);return}if(a.type==='ankan'){if(s.phase!=='playing'||s.turnSeat!==seat)throw Error('现在不能杠');const t=norm(Number(a.tile)),ids=p.hand.map((x,i)=>norm(x)===t?i:-1).filter(i=>i>=0);if(ids.length!==4)throw Error('没有四张相同牌');if(p.riichi&&!ankanOptions(p).includes(t))throw Error('立直后暗杠必须包含本巡摸牌且不能改变听牌');const eligible={};for(let j=0;j<4;j++)if(j!==seat&&canKokushiRobAnkan(s,j,t,seat))eligible[j]=[{kind:'ron'}];if(!Object.keys(eligible).length)return finalizeAnkan(s,seat,t);s.pending={kind:'ankan',actor:seat,tile:t,eligible,responses:{},expiresAt:Date.now()+8500};s.phase='reaction';s.message='暗杠宣言 · 仅国士无双可抢杠';return}if(a.type==='kakan'){if(s.phase!=='playing'||s.turnSeat!==seat||p.riichi)throw Error('现在不能加杠');const opt=kakanOptions(p).find(x=>x.meldIndex===Number(a.meldIndex));if(!opt)throw Error('没有可加杠的刻子');const eligible={};for(let j=0;j<4;j++)if(j!==seat&&canRon(s,j,opt.tile,seat))eligible[j]=[{kind:'ron'}];if(!Object.keys(eligible).length)return finalizeKakan(s,seat,opt.meldIndex,opt.tile);s.pending={kind:'kakan',actor:seat,tile:opt.tile,meldIndex:opt.meldIndex,eligible,responses:{},expiresAt:Date.now()+8500};s.phase='reaction';s.message='等待抢杠响应';return}if(a.type==='kyuushu'){if(!kyuushuAvailable(s,seat))throw Error('当前不能九种九牌');return abortiveDraw(s,'九种九牌')}if(a.type==='next_hand')return riichiNextHand(s);throw Error('未知日麻操作')}
export function riichiBotTurn(s,seat){const p=s.seats[seat];if(!p)return null;if(canTsumo(s,seat))return {type:'tsumo'};const ks=ankanOptions(p);if(ks.length&&Math.random()<.7)return {type:'ankan',tile:ks[0]};const adds=p.riichi?[]:kakanOptions(p);if(adds.length&&Math.random()<.7)return {type:'kakan',meldIndex:adds[0].meldIndex};const b=bestDiscard(s,seat);if(!b)return null;const opts=riichiTurnOptions(s,seat);if(!p.riichi&&opts.riichiDiscards.includes(b.index)&&s.points[seat]>=1000)return {type:'riichi_discard',index:b.index};return {type:'discard',index:b.index}}
export function riichiBotReaction(s,seat){const opts=riichiReactionOptions(s,seat);if(!opts.length)return null;const ron=opts.find(x=>x.kind==='ron');if(ron)return {type:'claim',kind:'ron'};const p=s.seats[seat],dangerOpp=s.seats.some((x,j)=>j!==seat&&x?.riichi);if(dangerOpp)return {type:'claim',kind:'pass'};const call=opts.find(x=>x.kind==='kan')||opts.find(x=>x.kind==='pon')||opts.find(x=>x.kind==='chi');return call&&riichiShanten(p.hand,allMelds(p))>0?{type:'claim',kind:call.kind}:{type:'claim',kind:'pass'}}
export function tickRiichi(s,now=Date.now()){let changed=false;if(s.phase==='reaction'&&s.pending&&now>=s.pending.expiresAt){for(const k of Object.keys(s.pending.eligible))if(!s.pending.responses[k])s.pending.responses[k]={kind:'pass'};resolvePending(s);changed=true}else if(s.phase==='playing'&&s.turnSeat!=null&&s.turnStartedAt&&now-s.turnStartedAt>=(s.turnTimeoutMs||30000)){const p=s.seats[s.turnSeat];if(p&&!p.isBot&&!isBot(p.userId)){let index=p.lastDraw!=null?p.hand.lastIndexOf(p.lastDraw):-1;if(index<0)index=bestDiscard(s,s.turnSeat)?.index??p.hand.length-1;try{discard(s,s.turnSeat,index,false);changed=true}catch{}}}return {changed,forceLeaveUsers:[],autoReset:!!(s.finishedAt&&now-s.finishedAt>=60000)}}
export function publicRiichiState(s,viewerId){const x=clone(s),seat=seatIndex(s,viewerId);x.serverNow=Date.now();x.mySeat=seat;x.myTurnOptions=seat>=0?riichiTurnOptions(s,seat):{};x.myReactionOptions=seat>=0?riichiReactionOptions(s,seat):[];
  if(s.phase==='result'&&x.resultDetail){const ids=[];if(x.resultDetail.type==='tsumo')ids.push(x.resultDetail.seat);else if(x.resultDetail.type==='ron')ids.push(...(x.resultDetail.winners||[]).map(v=>v.seat));else if(['exhaustive','nagashi'].includes(x.resultDetail.type))ids.push(...(x.resultDetail.tenpai||[]));x.resultDetail.reveals=[...new Set(ids)].map(i=>{const p=s.seats[i];if(!p)return null;const ron=x.resultDetail.type==='ron',winTile=ron?x.resultDetail.tile:p.lastDraw;return {seat:i,hand:clone(p.hand||[]),melds:clone(p.melds||[]),winTile:winTile??null,waits:['exhaustive','nagashi'].includes(x.resultDetail.type)?waitsFor(p.hand||[],allMelds(p)):[]}}).filter(Boolean)}
  for(let i=0;i<4;i++){const p=x.seats[i];if(!p)continue;p.handCount=p.hand?.length||0;if(p.userId!==viewerId)p.hand=(p.hand||[]).map(()=>({hidden:true}));}if(x.pending){x.pending={kind:x.pending.kind||'discard',discarder:x.pending.discarder,actor:x.pending.actor,tile:x.pending.tile,expiresAt:x.pending.expiresAt,waiting:Object.keys(x.pending.eligible).map(Number)}}return x}
