import {DurableObject} from 'cloudflare:workers';
import {ROOM_DEFS,ROOM_MAP,roomInitialState,applyGameAction,publicGameState,addBotToGame,removeBotFromGame,advanceBots,hasBot,isBotId} from '../shared/games.js';
import {DEFAULT_GAME_CHIP_RULES,boundedInt,normalizeEconomy,migrateEconomyV029} from '../server/economy.js';

const COLORS=new Set(['mint','sky','peach','lemon','lilac','milk','cocoa','rose','aqua','lime']);
const clean=(v,n=32)=>String(v??'').replace(/[\r\n\t]/g,' ').replace(/\s+/g,' ').trim().slice(0,n);
const cleanChat=(v,n=3000)=>String(v??'').replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').replace(/\n{4,}/g,'\n\n\n').trim().slice(0,n);
const normalizeEmployee=v=>clean(v,24).replace(/\s+/g,'').toUpperCase();
const validEmployee=v=>/^[A-Z0-9]{6,9}$/.test(v);
const maskEmployee=v=>v.length<=4?'*'.repeat(v.length):'*'.repeat(Math.max(2,v.length-4))+v.slice(-4);
const hex=buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');
async function sha(v){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v))))}
const tok=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
const CHIP_FLOOR=2000,CHIP_RECOVER_MS=7200000,CHIP_DAILY_REWARD=1000;
const RANKED_KINDS=['dice','gomoku','xiangqi','chess','blackjack','poker','go','mahjong','uno'];
const emptyRank=()=>({games:0,wins:0,losses:0,draws:0,updatedAt:0});
function gameActive(s){if(!s)return false;if(['gomoku','xiangqi','chess','go'].includes(s.kind))return !!s.started&&!s.winner&&!s.result;if(s.kind==='blackjack')return ['playing','dealer'].includes(s.phase);if(s.kind==='poker')return ['preflop','flop','turn','river','run_choice'].includes(s.phase);if(s.kind==='dice')return s.phase==='playing';return ['uno','mahjong'].includes(s.kind)&&['playing','reaction'].includes(s.phase)}
function gameHumanIds(s){const out=new Set;if(Array.isArray(s?.players))for(const x of s.players)if(x&&!isBotId(x))out.add(x);if(Array.isArray(s?.seats))for(const p of s.seats||[])if(p&&!p.isBot&&!isBotId(p.userId))out.add(p.userId);return [...out]}
function applyEconomyState(s,economy){if(!s)return;const r=economy?.gameRules?.[s.kind]||DEFAULT_GAME_CHIP_RULES[s.kind]||{};s.entryFee=Math.max(0,Number(r.entryFee)||0);s.aiEntryFee=Math.max(0,Number(r.aiEntryFee)||0);if(s.kind==='blackjack'){s.defaultStack=CHIP_FLOOR;s.betMin=r.minBet;s.betMax=r.maxBet;s.defaultBet=r.defaultBet}else if(s.kind==='poker'){s.defaultStack=CHIP_FLOOR;s.smallBlind=r.smallBlind;s.bigBlind=r.bigBlind;s.minRaiseBase=r.bigBlind;if(!gameActive(s))s.minRaise=r.bigBlind}}
function refreshWallet(u,now=Date.now()){if(!u)return 0;u.chips=Number.isFinite(u.chips)?Math.max(0,u.chips):CHIP_FLOOR;u.chipsUpdatedAt=u.chipsUpdatedAt||now;const elapsed=Math.max(0,now-u.chipsUpdatedAt);if(u.chips<CHIP_FLOOR&&elapsed>0)u.chips=Math.min(CHIP_FLOOR,u.chips+CHIP_FLOOR*elapsed/CHIP_RECOVER_MS);u.chipsUpdatedAt=now;return Math.floor(u.chips)}
function dailyKey(now=Date.now(),timeZone='Asia/Shanghai'){const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(now));const pick=t=>parts.find(x=>x.type===t)?.value||'';return `${pick('year')}-${pick('month')}-${pick('day')}`}
function publicUser(u,timeZone='Asia/Shanghai'){const chips=refreshWallet(u);return {userId:u.userId,loungeId:u.loungeId,name:u.name,slimeColor:u.slimeColor,bio:u.bio||'',role:u.role||'member',presenceStatus:u.presenceStatus||'online',statusMessage:u.statusMessage||'',employeeStatus:u.employeeStatus||'pending',chips,chipsUpdatedAt:u.chipsUpdatedAt||Date.now(),chipFloor:CHIP_FLOOR,chipRecoverMs:CHIP_RECOVER_MS,dailyChipReward:CHIP_DAILY_REWARD,lastChipCheckinDay:u.lastChipCheckinDay||'',canChipCheckin:(u.lastChipCheckinDay||'')!==dailyKey(Date.now(),timeZone),createdAt:u.createdAt}}
function normalizeRankRecord(raw){if(raw&&('human' in raw||'ai' in raw||'legacy' in raw)){raw.human={...emptyRank(),...(raw.human||{})};raw.ai={...emptyRank(),...(raw.ai||{})};return raw}const legacy=raw&&typeof raw==='object'?{...emptyRank(),...raw}:emptyRank();return {human:emptyRank(),ai:emptyRank(),legacy}}
function json(obj,status=200){return new Response(JSON.stringify(obj),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer'}})}
async function reqJson(req){try{return await req.json()}catch{return {}}}
function gameResultForRanking(before,after){if(!after||!RANKED_KINDS.includes(after.kind))return null;const humanIds=after?.players?(after.players||[]).filter(x=>x&&!isBotId(x)):(after?.seats||[]).filter(p=>p&&!p.isBot&&!isBotId(p.userId));const mode=humanIds.length>=2?'human':'ai';if(['gomoku','xiangqi','chess','go'].includes(after.kind)){const ended=!!after.winner||!!after.result;if(!ended||(before?.winner===after.winner&&before?.result===after.result))return null;return {kind:after.kind,mode,ranked:true,players:(after.players||[]).filter(x=>x&&!isBotId(x)).map(uid=>({userId:uid,outcome:after.winner?(after.winner===uid?'win':'loss'):'draw'}))}}if(['blackjack','poker'].includes(after.kind)&&after.handNo>(before?.handNo||after.handNo)){return {kind:after.kind,mode,ranked:true,players:(after.seats||[]).filter(p=>p&&!p.isBot&&!isBotId(p.userId)&&p.result).map(p=>{const x=String(p.result||'');let outcome='loss';if(after.kind==='blackjack'){if(x.includes('平'))outcome='draw';else if(x==='胜'||x.startsWith('Blackjack · 3:2'))outcome='win'}else outcome=(Number(p.payout)||0)>0?'win':'loss';return {userId:p.userId,outcome}})}}if(after.kind==='uno'&&after.matchWinner!=null&&before?.matchWinner==null){const winnerId=after.seats?.[after.matchWinner]?.userId;return {kind:after.kind,mode,ranked:true,players:(after.seats||[]).filter(p=>p&&!p.isBot&&!isBotId(p.userId)).map(p=>({userId:p.userId,outcome:p.userId===winnerId?'win':'loss'}))}}if(after.kind==='mahjong'&&after.matchEnded&&!before?.matchEnded){const order=(after.points||[]).map((points,i)=>({i,points})).sort((a,b)=>b.points-a.points),top=order[0]?.i;return {kind:after.kind,mode,ranked:true,players:(after.seats||[]).map((p,i)=>p&&!p.isBot&&!isBotId(p.userId)?{userId:p.userId,outcome:i===top?'win':'loss'}:null).filter(Boolean)}}return null}

export class AccountStore extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.data=null;ctx.blockConcurrencyWhile(async()=>{this.data=await ctx.storage.get('data')||{schemaVersion:5,ownerUserId:null,users:{},devices:{},employeeIndex:{},employeeHistory:[],employeeChangeRequests:[],friendships:[],tickets:{},presence:{},rankings:{}};const oldSchema=Number(this.data.schemaVersion||1);this.data.schemaVersion=5;this.data.employeeChangeRequests||=[];this.data.rankings||={};this.data.economy=oldSchema<5?migrateEconomyV029(this.data.economy||{}):normalizeEconomy(this.data.economy||{});this.data.chipLedger=Array.isArray(this.data.chipLedger)?this.data.chipLedger:[];for(const kind of RANKED_KINDS){const src=this.data.rankings[kind]||={};for(const [uid,raw] of Object.entries(src))src[uid]=normalizeRankRecord(raw)}const configured=normalizeEmployee(this.env.OWNER_EMPLOYEE_ID||'');let owner=null;if(configured&&validEmployee(configured)){const h=await this.employeeHash(configured);owner=Object.values(this.data.users||{}).find(u=>u.employeeHash===h)||null}else owner=Object.values(this.data.users||{}).find(u=>u.role==='owner')||Object.values(this.data.users||{}).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0))[0]||null;for(const u of Object.values(this.data.users||{}))if(u.role==='owner'&&u.userId!==owner?.userId)u.role='member';if(owner){owner.role='owner';owner.employeeStatus='verified';this.data.ownerUserId=owner.userId}else this.data.ownerUserId=null;for(const u of Object.values(this.data.users||{})){u.presenceStatus=u.presenceStatus||'online';u.statusMessage=u.statusMessage||'';u.employeeStatus=u.employeeStatus||(u.userId===this.data.ownerUserId?'verified':'pending');u.lastSeenAt=u.lastSeenAt||0;u.currentSection=u.currentSection||'';u.currentRoomId=u.currentRoomId||'';u.chips=Number.isFinite(u.chips)?Math.max(0,u.chips):CHIP_FLOOR;u.chipsUpdatedAt=u.chipsUpdatedAt||Date.now();u.lastChipCheckinDay=u.lastChipCheckinDay||'';}await this.ctx.storage.put('data',this.data)})}
  async persist(){await this.ctx.storage.put('data',this.data)}
  employeeHash(emp){return sha(`${this.env.EMPLOYEE_HASH_SECRET||'CHANGE-ME-IN-CLOUDFLARE'}:${emp}`)}
  makeId(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let id;do{id='SL-';for(let i=0;i<7;i++)id+=chars[Math.floor(Math.random()*chars.length)]}while(Object.values(this.data.users).some(u=>u.loungeId===id));return id}
  async auth(b){const u=this.data.users[String(b.userId||'')],d=this.data.devices[String(b.deviceId||'')];if(!u||!d||d.userId!==u.userId||d.tokenHash!==await sha(b.deviceToken||''))return null;const now=Date.now();d.lastSeenAt=now;u.lastSeenAt=now;return {u,d}}
  relation(a,b){return this.data.friendships.find(f=>((f.a===a&&f.b===b)||(f.a===b&&f.b===a))&&f.state!=='removed')}
  onlineInfo(u){const p=this.data.presence[u.userId],last=Math.max(u.lastSeenAt||0,p?.updatedAt||0),online=Date.now()-last<45000;return {online,lastSeenAt:last,currentSection:online?(u.currentSection||''):null,currentRoomId:online?(p?.roomId||u.currentRoomId||''):null}}
  social(userId){const friends=[],incoming=[],outgoing=[];for(const f of this.data.friendships){if(f.state==='removed'||(f.a!==userId&&f.b!==userId))continue;const other=f.a===userId?f.b:f.a,u=this.data.users[other];if(!u)continue;const e={...publicUser(u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai'),...this.onlineInfo(u)};if(f.state==='accepted')friends.push(e);else if(f.b===userId)incoming.push(e);else outgoing.push(e)}return {friends,incoming,outgoing}}
  isStaff(u){return u&&['owner','admin'].includes(u.role)}
  rankStat(kind,userId,mode='human'){if(!RANKED_KINDS.includes(kind))throw Error('未知排行榜游戏');this.data.rankings||={};const src=this.data.rankings[kind]||=( {} ),rec=src[userId]=normalizeRankRecord(src[userId]);return rec[mode==='ai'?'ai':'human']}
  settleClaims(claims,reason='游戏结算'){const entries=Object.entries(claims||{}).filter(([uid,v])=>this.data.users[uid]&&Number.isFinite(Number(v))&&Math.trunc(Number(v))!==0).map(([uid,v])=>[uid,Math.trunc(Number(v))]);const neg=entries.filter(x=>x[1]<0),pos=entries.filter(x=>x[1]>0);if(!neg.length||!pos.length)return {};let pool=0;const paid={};for(const [uid,v] of neg){const u=this.data.users[uid],available=refreshWallet(u),amt=Math.min(-v,available);u.chips=Math.max(0,Number(u.chips)||0)-amt;u.chipsUpdatedAt=Date.now();paid[uid]=-amt;pool+=amt}const weight=pos.reduce((a,x)=>a+x[1],0);let left=pool;for(let i=0;i<pos.length;i++){const [uid,v]=pos[i],amt=i===pos.length-1?left:Math.min(left,Math.floor(pool*v/weight));const u=this.data.users[uid];refreshWallet(u);u.chips=Math.max(0,Number(u.chips)||0)+amt;u.chipsUpdatedAt=Date.now();paid[uid]=(paid[uid]||0)+amt;left-=amt}this.data.chipLedger.push({id:crypto.randomUUID(),kind:'game',reason,at:Date.now(),deltas:paid});if(this.data.chipLedger.length>5000)this.data.chipLedger.splice(0,this.data.chipLedger.length-5000);return paid}
  roundFee(kind,mode,userIds,preview=false){const ids=[...new Set((userIds||[]).map(String))].filter(uid=>this.data.users[uid]),r=this.data.economy?.gameRules?.[kind]||DEFAULT_GAME_CHIP_RULES[kind]||{},fee=Math.max(0,Math.floor(Number(mode==='ai'?r.aiEntryFee:r.entryFee)||0));const wallets={};for(const uid of ids){const u=this.data.users[uid];wallets[uid]=refreshWallet(u);if(wallets[uid]<fee)return {ok:false,error:`${u.name||'玩家'} 筹码不足：${mode==='ai'?'AI练习':'真人对局'}每局费用为 ${fee}`,fee,mode}}if(preview||!fee)return {ok:true,fee,mode,wallets};const deltas={};for(const uid of ids){const u=this.data.users[uid];u.chips=Math.max(0,wallets[uid]-fee);u.chipsUpdatedAt=Date.now();deltas[uid]=-fee}this.data.chipLedger.push({id:crypto.randomUUID(),kind:'entry_fee',game:kind,mode,reason:`${mode==='ai'?'AI练习':'真人对局'}每局入场费 -${fee}`,at:Date.now(),deltas});if(this.data.chipLedger.length>5000)this.data.chipLedger.splice(0,this.data.chipLedger.length-5000);return {ok:true,fee,mode,wallets,deltas}}
  leaders(){const games={};for(const kind of RANKED_KINDS){games[kind]={};for(const mode of ['human','ai'])games[kind][mode]=Object.entries(this.data.rankings?.[kind]||{}).map(([userId,raw])=>{const u=this.data.users[userId],st=normalizeRankRecord(raw)[mode]||emptyRank();return {...st,userId,name:u?.name||'已离开用户',slimeColor:u?.slimeColor||'mint',loungeId:u?.loungeId||''}}).filter(x=>x.games>0).sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.games-a.games||b.updatedAt-a.updatedAt).slice(0,50)}const chips=Object.values(this.data.users).map(u=>{const p=publicUser(u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai');return {userId:p.userId,name:p.name,slimeColor:p.slimeColor,loungeId:p.loungeId,chips:p.chips}}).sort((a,b)=>b.chips-a.chips||String(a.name).localeCompare(String(b.name),'zh-CN')).slice(0,100);return {chips,games}}
  async fetch(req){const url=new URL(req.url),b=req.method==='POST'?await reqJson(req):{};
    if(url.pathname==='/register'){
      const name=clean(b.name,16),emp=normalizeEmployee(b.employeeId),slimeColor=COLORS.has(b.slimeColor)?b.slimeColor:'mint';if(!name)return json({ok:false,error:'请输入昵称'},400);if(!validEmployee(emp))return json({ok:false,error:'工号格式仅接受 6~9 位英文字母或数字'},400);const eh=await this.employeeHash(emp);if(this.data.employeeIndex[eh])return json({ok:false,error:'该工号已被占用，不能自行覆盖。请联系 Owner 核验并释放冲突工号'},409);const now=Date.now(),userId=crypto.randomUUID(),deviceId=crypto.randomUUID(),deviceToken=tok(),isFirst=Object.keys(this.data.users).length===0,configuredOwner=normalizeEmployee(this.env.OWNER_EMPLOYEE_ID||''),ownerClaim=!this.data.ownerUserId&&(configuredOwner?emp===configuredOwner:isFirst),u={userId,loungeId:this.makeId(),name,slimeColor,bio:'',role:ownerClaim?'owner':'member',employeeHash:eh,employeeMasked:maskEmployee(emp),employeeStatus:ownerClaim?'verified':'pending',presenceStatus:'online',statusMessage:'',lastSeenAt:now,currentSection:'chat',currentRoomId:'',chips:CHIP_FLOOR,chipsUpdatedAt:now,lastChipCheckinDay:'',createdAt:now,updatedAt:now};this.data.users[userId]=u;if(ownerClaim)this.data.ownerUserId=userId;this.data.devices[deviceId]={deviceId,userId,label:clean(b.deviceLabel,32)||'当前设备',tokenHash:await sha(deviceToken),createdAt:now,lastSeenAt:now};this.data.employeeIndex[eh]=userId;await this.persist();return json({ok:true,userId,deviceId,deviceToken,profile:publicUser(u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai'),employeeMasked:u.employeeMasked},201)
    }
    if(url.pathname==='/auth'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);await this.persist();return json({ok:true,profile:publicUser(a.u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai'),employeeMasked:a.u.employeeMasked,deviceLabel:a.d.label,social:this.social(a.u.userId)})}
    if(url.pathname==='/presence/ping'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);a.u.lastSeenAt=Date.now();a.u.currentSection=clean(b.section,24);a.u.currentRoomId=clean(b.roomId,48);if(['online','busy','focus','meeting','away','gaming','listening'].includes(b.presenceStatus))a.u.presenceStatus=b.presenceStatus;await this.persist();return json({ok:true,profile:publicUser(a.u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai')})}
    if(url.pathname==='/profile'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const name=clean(b.name,16);if(!name)return json({ok:false,error:'昵称不能为空'},400);a.u.name=name;a.u.bio=clean(b.bio,80);a.u.statusMessage=clean(b.statusMessage,48);if(['online','busy','focus','meeting','away','gaming','listening'].includes(b.presenceStatus))a.u.presenceStatus=b.presenceStatus;if(COLORS.has(b.slimeColor))a.u.slimeColor=b.slimeColor;a.u.updatedAt=Date.now();a.u.lastSeenAt=Date.now();await this.persist();return json({ok:true,profile:publicUser(a.u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai')})}
    if(url.pathname==='/employee/change'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const emp=normalizeEmployee(b.employeeId);if(!validEmployee(emp))return json({ok:false,error:'工号格式仅接受 6~9 位英文字母或数字'},400);const nh=await this.employeeHash(emp),owner=this.data.employeeIndex[nh];if(owner&&owner!==a.u.userId)return json({ok:false,error:'该工号已被其他身份占用，请联系管理员处理冲突'},409);if(a.u.role==='owner'){const old=a.u.employeeHash;delete this.data.employeeIndex[old];this.data.employeeIndex[nh]=a.u.userId;a.u.employeeHash=nh;a.u.employeeMasked=maskEmployee(emp);a.u.employeeStatus='verified';this.data.employeeHistory.push({userId:a.u.userId,oldHash:old,newHash:nh,changedAt:Date.now(),approvedBy:a.u.userId});await this.persist();return json({ok:true,employeeMasked:a.u.employeeMasked,employeeStatus:'verified'})}const reqId=crypto.randomUUID();this.data.employeeChangeRequests=this.data.employeeChangeRequests.filter(x=>x.userId!==a.u.userId||x.state!=='pending');this.data.employeeChangeRequests.push({id:reqId,userId:a.u.userId,newHash:nh,newMasked:maskEmployee(emp),state:'pending',createdAt:Date.now()});await this.persist();return json({ok:true,pending:true,message:'工号变更已提交，等待管理员核验'},202)}
    if(url.pathname==='/ticket'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);if(!ROOM_MAP[b.roomId])return json({ok:false,error:'房间不存在'},404);const ticket=tok();this.data.tickets[await sha(ticket)]={userId:a.u.userId,roomId:b.roomId,exp:Date.now()+60000};await this.persist();return json({ok:true,ticket})}
    if(url.pathname==='/consume'){const h=await sha(b.ticket||''),t=this.data.tickets[h];delete this.data.tickets[h];if(!t||t.exp<Date.now()||t.roomId!==b.roomId){await this.persist();return json({ok:false,error:'ticket invalid'},401)}const u=this.data.users[t.userId];await this.persist();return json({ok:true,userId:t.userId,profile:publicUser(u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai')})}
    if(url.pathname==='/presence'){const {userId,roomId,online}=b;if(this.data.users[userId]){const now=Date.now();this.data.presence[userId]={roomId,online:!!online,updatedAt:now};this.data.users[userId].lastSeenAt=now;this.data.users[userId].currentRoomId=online?roomId:'';await this.persist()}return json({ok:true})}
    if(url.pathname==='/rooms'){const cnt={};for(const u of Object.values(this.data.users)){const info=this.onlineInfo(u);if(info.online&&info.currentRoomId)cnt[info.currentRoomId]=(cnt[info.currentRoomId]||0)+1}return json({ok:true,rooms:ROOM_DEFS.map(r=>({...r,online:cnt[r.id]||0}))})}
    if(url.pathname==='/users/presence'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const tz=this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai',users=Object.values(this.data.users).map(u=>({...publicUser(u,tz),...this.onlineInfo(u)}));await this.persist();return json({ok:true,users})}
    if(url.pathname==='/wallet/checkin'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const tz=this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai';refreshWallet(a.u);const day=dailyKey(Date.now(),tz);if(a.u.lastChipCheckinDay===day)return json({ok:false,error:'今天已经签到领取过筹码'},409);a.u.chips=Math.max(0,Number(a.u.chips)||0)+CHIP_DAILY_REWARD;a.u.lastChipCheckinDay=day;a.u.chipsUpdatedAt=Date.now();await this.persist();return json({ok:true,profile:publicUser(a.u,tz),reward:CHIP_DAILY_REWARD})}
    if(url.pathname==='/wallet/get'){const u=this.data.users[String(b.userId||'')];if(!u)return json({ok:false,error:'用户不存在'},404);const chips=refreshWallet(u);await this.persist();return json({ok:true,chips})}
    if(url.pathname==='/wallet/round-fee'){const x=this.roundFee(clean(b.kind,24),b.mode==='ai'?'ai':'human',b.userIds,!!b.preview);if(!x.ok)return json(x,400);if(!b.preview)await this.persist();return json(x)}
    if(url.pathname==='/wallet/single-entry'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const kind=clean(b.kind,24),x=this.roundFee(kind,'ai',[a.u.userId],false);if(!x.ok)return json(x,400);await this.persist();return json({ok:true,fee:x.fee,profile:publicUser(a.u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai')})}
    if(url.pathname==='/wallet/sync'){const u=this.data.users[String(b.userId||'')];if(!u)return json({ok:false,error:'用户不存在'},404);u.chips=Math.max(0,Number(b.chips)||0);u.chipsUpdatedAt=Date.now();await this.persist();return json({ok:true,chips:Math.floor(u.chips)})}
    if(url.pathname==='/leaderboards')return json({ok:true,leaderboards:this.leaders()})
    if(url.pathname==='/economy/get')return json({ok:true,economy:this.data.economy,defaults:{chipFloor:CHIP_FLOOR,chipRecoverMs:CHIP_RECOVER_MS,dailyReward:CHIP_DAILY_REWARD,recoverPerHour:1000}})
    if(url.pathname==='/wallet/settle'){this.settleClaims(b.claims,b.reason||'游戏结算');await this.persist();return json({ok:true})}
    if(url.pathname==='/admin/chips'){const a=await this.auth(b);if(!a||!this.isStaff(a.u))return json({ok:false,error:'无管理员权限'},403);const action=String(b.action||'get');if(action==='get')return json({ok:true,economy:this.data.economy,defaults:{chipFloor:CHIP_FLOOR,chipRecoverMs:CHIP_RECOVER_MS,dailyReward:CHIP_DAILY_REWARD,recoverPerHour:1000}});if(action==='set_rules'){this.data.economy=normalizeEconomy({chipFloor:b.chipFloor,recoverPerHour:b.recoverPerHour,dailyReward:b.dailyReward,gameRules:b.gameRules,updatedAt:Date.now(),updatedBy:a.u.userId});await this.persist();return json({ok:true,economy:this.data.economy})}if(action==='set_user'){const target=this.data.users[String(b.targetUserId||'')];if(!target)return json({ok:false,error:'用户不存在'},404);refreshWallet(target);const before=Math.floor(target.chips||0),next=boundedInt(b.chips,0,1000000000,before);target.chips=next;target.chipsUpdatedAt=Date.now();this.data.chipLedger.push({id:crypto.randomUUID(),kind:'admin',reason:`管理员手动修改筹码 ${before} → ${next}`,at:Date.now(),deltas:{[target.userId]:next-before},by:a.u.userId});if(this.data.chipLedger.length>5000)this.data.chipLedger.splice(0,this.data.chipLedger.length-5000);await this.persist();return json({ok:true,profile:publicUser(target,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai'),before,after:next})}return json({ok:false,error:'未知筹码管理操作'},400)}
    if(url.pathname==='/admin/users'){const a=await this.auth(b);if(!a||!this.isStaff(a.u))return json({ok:false,error:'无管理员权限'},403);const users=Object.values(this.data.users).map(u=>({...publicUser(u,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai'),...this.onlineInfo(u),employeeMasked:u.employeeMasked||'',deviceCount:Object.values(this.data.devices).filter(d=>d.userId===u.userId).length})).sort((x,y)=>(Number(y.online)-Number(x.online))||x.createdAt-y.createdAt);const employeeRequests=this.data.employeeChangeRequests.filter(x=>x.state==='pending').map(x=>({...x,user:publicUser(this.data.users[x.userId]||{},this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai')}));await this.persist();return json({ok:true,ownerUserId:this.data.ownerUserId,users,employeeRequests})}
    if(url.pathname==='/admin/role'){const a=await this.auth(b);if(!a||a.u.userId!==this.data.ownerUserId||a.u.role!=='owner')return json({ok:false,error:'只有唯一 Owner 可以调整管理员'},403);const target=this.data.users[String(b.targetUserId||'')];if(!target||target.userId===a.u.userId)return json({ok:false,error:'目标用户无效'},400);if(target.role==='owner'||target.userId===this.data.ownerUserId)return json({ok:false,error:'不能修改 Owner'},403);target.role=b.role==='admin'?'admin':'member';target.updatedAt=Date.now();await this.persist();return json({ok:true,profile:publicUser(target,this.env.SLIMELOUNGE_TIME_ZONE||'Asia/Shanghai')})}
    if(url.pathname==='/admin/employee'){const a=await this.auth(b);if(!a||!this.isStaff(a.u))return json({ok:false,error:'无管理员权限'},403);const action=String(b.action||'');if(action==='verify'){const target=this.data.users[String(b.targetUserId||'')];if(!target)return json({ok:false,error:'用户不存在'},404);target.employeeStatus='verified';target.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='reject'){const target=this.data.users[String(b.targetUserId||'')];if(!target||target.role==='owner')return json({ok:false,error:'目标无效'},400);if(target.employeeHash)delete this.data.employeeIndex[target.employeeHash];target.employeeHash=null;target.employeeMasked='未绑定';target.employeeStatus='rejected';target.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='approve_change'){const r=this.data.employeeChangeRequests.find(x=>x.id===b.requestId&&x.state==='pending');if(!r)return json({ok:false,error:'变更申请不存在'},404);const target=this.data.users[r.userId];if(!target)return json({ok:false,error:'用户不存在'},404);const conflict=this.data.employeeIndex[r.newHash];if(conflict&&conflict!==target.userId)return json({ok:false,error:'新工号已被其他身份占用'},409);if(target.employeeHash)delete this.data.employeeIndex[target.employeeHash];this.data.employeeIndex[r.newHash]=target.userId;target.employeeHash=r.newHash;target.employeeMasked=r.newMasked;target.employeeStatus='verified';r.state='approved';r.approvedBy=a.u.userId;r.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='reject_change'){const r=this.data.employeeChangeRequests.find(x=>x.id===b.requestId&&x.state==='pending');if(!r)return json({ok:false,error:'变更申请不存在'},404);r.state='rejected';r.approvedBy=a.u.userId;r.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='release_conflict'){const emp=normalizeEmployee(b.employeeId);if(!validEmployee(emp))return json({ok:false,error:'工号格式无效'},400);const h=await this.employeeHash(emp),uid=this.data.employeeIndex[h],target=this.data.users[uid];if(!target)return json({ok:false,error:'该工号当前未被占用'},404);if(target.role==='owner')return json({ok:false,error:'不能释放 Owner 工号'},403);delete this.data.employeeIndex[h];target.employeeHash=null;target.employeeMasked='未绑定';target.employeeStatus='rejected';target.updatedAt=Date.now();await this.persist();return json({ok:true,releasedUserId:uid})}return json({ok:false,error:'未知管理员工号操作'},400)}
    if(url.pathname==='/ranking/report'){const r=b.result;if(!r||!RANKED_KINDS.includes(r.kind)||r.ranked===false)return json({ok:true});for(const x of r.players||[]){if(!this.data.users[x.userId])continue;const st=this.rankStat(r.kind,x.userId,r.mode==='ai'?'ai':'human');st.games++;if(x.outcome==='win')st.wins++;else if(x.outcome==='draw')st.draws++;else st.losses++;st.updatedAt=Date.now()}if(r.chipClaims&&r.mode==='human')this.settleClaims(r.chipClaims,r.chipReason||`${r.kind} 真人局结算`);await this.persist();return json({ok:true})}
    if(url.pathname==='/social/list'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);return json({ok:true,social:this.social(a.u.userId)})}
    if(url.pathname==='/social/search'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const id=clean(b.loungeId,16).toUpperCase(),u=Object.values(this.data.users).find(x=>x.loungeId===id);if(!u)return json({ok:false,error:'没有找到该 Lounge ID'},404);return json({ok:true,profile:publicUser(u),relation:this.relation(a.u.userId,u.userId)?.state||'none'})}
    if(url.pathname==='/social/request'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const me=a.u.userId,other=String(b.otherUserId||'');if(!this.data.users[other]||other===me)return json({ok:false,error:'用户无效'},400);let f=this.relation(me,other);if(f){if(f.state==='pending'&&f.b===me){f.state='accepted';f.updatedAt=Date.now();await this.persist();return json({ok:true,social:this.social(me)})}return json({ok:false,error:'关系已存在'},409)}this.data.friendships.push({a:me,b:other,state:'pending',createdAt:Date.now(),updatedAt:Date.now()});await this.persist();return json({ok:true,social:this.social(me)})}
    if(url.pathname==='/social/respond'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const me=a.u.userId,other=String(b.otherUserId||''),f=this.relation(me,other);if(!f||f.state!=='pending'||f.b!==me)return json({ok:false,error:'申请不存在'},404);f.state=b.accept?'accepted':'removed';f.updatedAt=Date.now();await this.persist();return json({ok:true,social:this.social(me)})}
    if(url.pathname==='/social/remove'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const me=a.u.userId,other=String(b.otherUserId||''),f=this.relation(me,other);if(!f||f.state!=='accepted')return json({ok:false,error:'好友不存在'},404);f.state='removed';f.updatedAt=Date.now();await this.persist();return json({ok:true,social:this.social(me)})}
    return json({ok:false,error:'Not found'},404)
  }
}

export class RoomStore extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.state=null;this.roomId='';ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('state')||null})}
  accounts(){return this.env.ACCOUNTS.getByName('global')}
  async account(path,obj){return (await this.accounts().fetch(new Request('https://accounts'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(obj)}))).json()}
  sockets(){return this.ctx.getWebSockets()}
  attachment(ws){try{return ws.deserializeAttachment()}catch{return null}}
  users(){return this.sockets().map(ws=>{const a=this.attachment(ws);return a?.profile?{...a.profile,voiceOn:!!a.voiceOn,voiceSpeaking:!!a.voiceOn&&!!a.voiceSpeaking}:null}).filter(Boolean)}
  send(ws,obj){try{ws.send(JSON.stringify(obj))}catch{}}
  broadcast(obj){for(const ws of this.sockets())this.send(ws,obj)}
  async save(){await this.ctx.storage.put('state',this.state)}
  async gameBroadcast(){for(const ws of this.sockets()){const a=this.attachment(ws);this.send(ws,{type:'game_state',state:publicGameState(this.state.game,a?.userId)})}}
  async fetch(req){const url=new URL(req.url);if(req.headers.get('Upgrade')!=='websocket')return json({ok:false,error:'WebSocket required'},426);const roomId=req.headers.get('x-room-id')||url.searchParams.get('roomId')||'';const def=ROOM_MAP[roomId];if(!def)return json({ok:false,error:'房间不存在'},404);this.roomId=roomId;const staleGame=def.game&&(!this.state?.game||this.state.game.kind!==def.game||(['gomoku','xiangqi','chess'].includes(def.game)&&(!Array.isArray(this.state.game.ready)||typeof this.state.game.started!=='boolean')));if(!this.state||staleGame){this.state=roomInitialState(def);this.state.schemaVersion=2;await this.save()}else if(Number(this.state.schemaVersion||0)<2){if(roomId==='chat-changelog')this.state.messages=[];if(def.category==='music'){const ms=this.state.music||{};this.state.music={provider:ms.provider||'netease',trackId:ms.trackId||'',mediaId:ms.mediaId||'',title:ms.title||'',setBy:ms.setBy||'',cover:ms.cover||'',duration:Math.max(0,Number(ms.duration)||0),positionMs:Math.max(0,Number(ms.positionMs)||0),playing:!!ms.trackId,updatedAt:Date.now(),revision:1,queue:Array.isArray(ms.queue)?ms.queue:[]}}this.state.schemaVersion=2;await this.save()}const t=await this.account('/consume',{ticket:url.searchParams.get('ticket')||'',roomId});if(!t.ok)return json(t,401);const pair=new WebSocketPair(),[client,server]=Object.values(pair);server.serializeAttachment({userId:t.userId,profile:t.profile,roomId,voiceOn:false,voiceSpeaking:false});this.ctx.acceptWebSocket(server);await this.account('/presence',{userId:t.userId,roomId,online:true});this.send(server,{type:'init',room:def,profile:t.profile,users:this.users(),messages:(this.state.messages||[]).slice(-60),music:this.state.music||null,game:def.game?publicGameState(this.state.game,t.userId):null});this.broadcast({type:'presence',users:this.users()});return new Response(null,{status:101,webSocket:client})}
  async webSocketMessage(ws,message){let m;try{m=JSON.parse(String(message))}catch{return}const a=this.attachment(ws),def=ROOM_MAP[a?.roomId||this.roomId];if(!a||!def)return;try{
    if(m.type==='heartbeat'){await this.account('/presence',{userId:a.userId,roomId:a.roomId,online:true});this.send(ws,{type:'heartbeat_ack',at:Date.now()});return}
    if(['chat','chat_edit','chat_delete'].includes(m.type)){if(def.channelType==='voice')throw Error('语音频道不发送文字消息');const staff=['owner','admin'].includes(a.profile.role),arr=this.state.messages||(this.state.messages=[]);if(m.type==='chat'){const text=cleanChat(m.text,3000);if(!text)return;if(def.readOnly)throw Error('该频道为只读');if(def.adminOnlyPost&&!staff)throw Error('该讨论区仅 Owner / Admin 可以发言');const parent=arr.find(x=>x.id===String(m.replyTo||''));const reply=parent?{messageId:parent.id,userId:parent.userId,name:parent.name,text:String(parent.text||'').slice(0,500)}:null;const msg={id:crypto.randomUUID(),userId:a.userId,name:a.profile.name,slimeColor:a.profile.slimeColor,role:a.profile.role||'member',text,reply,at:Date.now(),editedAt:0};arr.push(msg);while(arr.length>100)arr.shift();await this.save();this.broadcast({type:'chat',message:msg});return}const idx=arr.findIndex(x=>x.id===String(m.messageId||'')),msg=arr[idx];if(!msg)throw Error('消息不存在或已经被删除');if(m.type==='chat_edit'){const allowed=def.adminOnlyPost?staff:msg.userId===a.userId;if(!allowed)throw Error(def.adminOnlyPost?'只有 Owner / Admin 可以编辑公告和更新日志':'只能编辑自己的消息');const text=cleanChat(m.text,3000);if(!text)throw Error('消息不能为空');msg.text=text;msg.editedAt=Date.now();msg.editedBy=a.userId;await this.save();this.broadcast({type:'chat_update',message:msg});return}const allowed=def.adminOnlyPost?staff:(msg.userId===a.userId||staff);if(!allowed)throw Error(def.adminOnlyPost?'只有 Owner / Admin 可以删除公告和更新日志':'只能删除自己的消息');arr.splice(idx,1);await this.save();this.broadcast({type:'chat_delete',messageId:msg.id});return}
    if((m.type==='music_set'||m.type==='music_add')&&def.category==='music'){const id=String(m.trackId||'').match(/\d{3,20}/)?.[0];if(!id)throw Error('请输入网易云歌曲 ID 或歌曲链接');const ms=this.state.music||=( {provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',duration:0,positionMs:0,playing:false,updatedAt:0,revision:0,queue:[]} );ms.queue=Array.isArray(ms.queue)?ms.queue:[];const item={provider:'netease',trackId:id,mediaId:'',title:clean(m.title,80)||`网易云歌曲 ${id}`,setBy:a.profile.name,cover:/^https?:\/\//i.test(String(m.cover||''))?clean(m.cover,300):'',duration:Math.max(0,Number(m.duration)||0),queuedAt:Date.now()};if(!ms.trackId)Object.assign(ms,item,{positionMs:0,playing:true,updatedAt:Date.now(),revision:(ms.revision||0)+1});else ms.queue.push(item);await this.save();this.broadcast({type:'music_state',music:ms});return}
    if(m.type==='music_control'&&def.category==='music'){const ms=this.state.music;if(!ms?.trackId||String(ms.trackId)!==String(m.trackId||ms.trackId))return;const now=Date.now(),current=Math.max(0,Number(ms.positionMs)||0)+(ms.playing?Math.max(0,now-(ms.updatedAt||now)):0),duration=Math.max(0,Number(ms.duration)||0),clamp=v=>Math.max(0,duration?Math.min(Number(v)||0,duration):Number(v)||0);if(m.action==='seek')ms.positionMs=clamp(m.positionMs);else ms.positionMs=clamp(current);if(m.action==='play')ms.playing=true;else if(m.action==='pause')ms.playing=false;else if(m.action!=='seek')return;ms.updatedAt=now;ms.revision=(ms.revision||0)+1;await this.save();this.broadcast({type:'music_state',music:ms});return}
    if(m.type==='music_ended'&&def.category==='music'){const ms=this.state.music;if(!ms||String(ms.trackId||'')!==String(m.trackId||''))return;const next=(ms.queue||[]).shift();if(next)Object.assign(ms,next,{positionMs:0,playing:true,updatedAt:Date.now(),revision:(ms.revision||0)+1});else Object.assign(ms,{provider:'netease',trackId:'',mediaId:'',title:'',setBy:'',cover:'',duration:0,positionMs:0,playing:false,updatedAt:Date.now(),revision:(ms.revision||0)+1});await this.save();this.broadcast({type:'music_state',music:ms});return}
    if(m.type==='voice_toggle'&&(def.category==='game'||def.voiceAllowed)){ws.serializeAttachment({...a,voiceOn:!!m.enabled,voiceSpeaking:m.enabled?!!a.voiceSpeaking:false});this.broadcast({type:'presence',users:this.users()});return}
    if(m.type==='voice_activity'&&(def.category==='game'||def.voiceAllowed)){const speaking=!!m.speaking&&!!a.voiceOn;if(!!a.voiceSpeaking!==speaking){ws.serializeAttachment({...a,voiceSpeaking:speaking});this.broadcast({type:'presence',users:this.users()})}return}
    if(m.type==='voice_signal'&&(def.category==='game'||def.voiceAllowed)){const target=String(m.target||'');if(!target||target===a.userId||!m.signal||typeof m.signal!=='object')return;for(const peer of this.sockets()){const pa=this.attachment(peer);if(pa?.userId===target)this.send(peer,{type:'voice_signal',from:a.userId,signal:m.signal})}return}
    if(m.type==='game_action'&&def.game){
      const before=JSON.parse(JSON.stringify(this.state.game)),act={...(m.action||{})},econ=await this.account('/economy/get',{}),activeBefore=gameActive(this.state.game);
      if(!activeBefore&&['join','ready','start','reset','bet'].includes(act.type))applyEconomyState(this.state.game,econ.economy);
      if(act.type==='join'&&['blackjack','poker'].includes(this.state.game.kind)){const wallet=await this.account('/wallet/get',{userId:a.userId});if(wallet.ok){act.chips=wallet.chips;if(this.state.game.kind==='poker')act.walletAtBuyIn=wallet.chips}}
      if(act.type==='add_bot')addBotToGame(this.state.game,Number.isInteger(act.seat)?act.seat:null);else if(act.type==='remove_bot')removeBotFromGame(this.state.game,Number.isInteger(act.seat)?act.seat:null);else applyGameAction(this.state.game,a.userId,act);
      if(!activeBefore&&gameActive(this.state.game)){const ids=gameHumanIds(this.state.game),mode=ids.length>=2?'human':'ai',preview=await this.account('/wallet/round-fee',{kind:this.state.game.kind,mode,userIds:ids,preview:true});if(!preview.ok){this.state.game=before;throw Error(preview.error||'筹码不足')}const paid=await this.account('/wallet/round-fee',{kind:this.state.game.kind,mode,userIds:ids,preview:false});if(!paid.ok){this.state.game=before;throw Error(paid.error||'扣除每局费用失败')}const fee=paid.fee||0;if(mode==='human'&&fee&&this.state.game.kind==='blackjack')for(const p of this.state.game.seats||[])if(p&&!p.isBot&&!isBotId(p.userId))p.chips=Math.max(0,(Number(p.chips)||0)-fee);if(mode==='human'&&fee&&this.state.game.kind==='poker')for(const p of this.state.game.seats||[])if(p&&!p.isBot&&!isBotId(p.userId))p.walletAtBuyIn=Math.max(0,(Number(p.walletAtBuyIn)||0)-fee)}
      advanceBots(this.state.game);const after=this.state.game;if(!hasBot(after)&&['blackjack','poker'].includes(after.kind)){for(const p of after.seats||[])if(p&&!p.isBot&&!isBotId(p.userId)){const chips=after.kind==='poker'&&Number.isFinite(Number(p.buyIn))&&Number.isFinite(Number(p.walletAtBuyIn))?Math.max(0,Number(p.walletAtBuyIn)+(Number(p.chips)||0)-Number(p.buyIn)):Math.max(0,Number(p.chips)||0);await this.account('/wallet/sync',{userId:p.userId,chips})}}
      const result=gameResultForRanking(before,after);if(result?.players?.length)await this.account('/ranking/report',{result});await this.save();await this.gameBroadcast();return
    }
  }catch(e){this.send(ws,{type:'error',error:e.message})}}
  async webSocketClose(ws){const a=this.attachment(ws);if(a)await this.account('/presence',{userId:a.userId,roomId:a.roomId,online:false});this.broadcast({type:'presence',users:this.users()})}
  async webSocketError(ws){await this.webSocketClose(ws)}
}

async function accountFetch(env,path,reqBody){const stub=env.ACCOUNTS.getByName('global');return stub.fetch(new Request('https://accounts'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(reqBody||{})}))}
const musicCache=new Map();
async function searchNetease(q,env){const query=clean(q,80);if(!query)return [];const key=query.toLowerCase(),hit=musicCache.get(key);if(hit&&Date.now()-hit.at<300000)return hit.results;let base=String(env?.NETEASE_SEARCH_BASE||'').trim().replace(/\/$/,'');if(base&&!/^https?:\/\//i.test(base))base='https://'+base;const directNetease=/^https?:\/\/(?:www\.)?music\.163\.com$/i.test(base);const urls=base&&!directNetease?[`${base}/search?keywords=${encodeURIComponent(query)}&limit=12`]:[`https://music.163.com/api/search/get/web?csrf_token=hlpretag=&hlposttag=&s=${encodeURIComponent(query)}&type=1&offset=0&total=true&limit=12`,`https://music.163.com/api/search/get?s=${encodeURIComponent(query)}&type=1&limit=12&offset=0`];const ctrl=new AbortController(),timer=setTimeout(()=>{if(!ctrl.signal.aborted)ctrl.abort(Object.assign(new Error('music search timeout'),{name:'TimeoutError'}))},2500);const attempt=async u=>{const r=await fetch(u,{signal:ctrl.signal,headers:{'user-agent':'Mozilla/5.0','referer':'https://music.163.com/','accept':'application/json,text/plain,*/*'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json(),songs=j?.result?.songs||[];if(!songs.length)throw Error('没有搜索结果');return songs.map(x=>({id:String(x.id),name:x.name||'未知歌曲',artists:(x.artists||x.ar||[]).map(a=>a.name).filter(Boolean),album:x.album?.name||x.al?.name||'',duration:x.duration||x.dt||0}))};try{const results=await Promise.any(urls.map(attempt));musicCache.set(key,{at:Date.now(),results});return results}catch(e){if(ctrl.signal.aborted)throw Error('网易云搜索超时（2.5 秒）：当前网络无法访问音乐搜索源');const first=e?.errors?.[0]||e;throw Error('网易云搜索失败：'+(first?.message||'网络不可达'))}finally{clearTimeout(timer)}}

export default{
  async fetch(request,env){const url=new URL(request.url);
    if(url.pathname==='/api/health')return json({ok:true,app:'SlimeLounge',version:'0.3.4'});
    if(url.pathname==='/api/rooms')return env.ACCOUNTS.getByName('global').fetch(new Request('https://accounts/rooms'));
    if(url.pathname==='/api/leaderboards')return env.ACCOUNTS.getByName('global').fetch(new Request('https://accounts/leaderboards',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}));
    if(url.pathname==='/api/music/search'&&request.method==='GET'){try{return json({ok:true,results:await searchNetease(url.searchParams.get('q')||'',env)})}catch(e){return json({ok:false,error:e.message},502)}}
    const routes={'/api/register':'/register','/api/auth':'/auth','/api/presence/ping':'/presence/ping','/api/users/presence':'/users/presence','/api/wallet/checkin':'/wallet/checkin','/api/game/entry':'/wallet/single-entry','/api/profile':'/profile','/api/employee/change':'/employee/change','/api/ticket':'/ticket','/api/social/list':'/social/list','/api/social/search':'/social/search','/api/social/request':'/social/request','/api/social/respond':'/social/respond','/api/social/remove':'/social/remove','/api/admin/users':'/admin/users','/api/admin/chips':'/admin/chips','/api/admin/role':'/admin/role','/api/admin/employee':'/admin/employee'};
    if(routes[url.pathname]&&request.method==='POST')return accountFetch(env,routes[url.pathname],await reqJson(request));
    if(url.pathname==='/api/ws'){
      const roomId=url.searchParams.get('roomId')||request.headers.get('x-room-id');if(!ROOM_MAP[roomId])return json({ok:false,error:'房间不存在'},404);const stub=env.ROOMS.getByName(roomId),h=new Headers(request.headers);h.set('x-room-id',roomId);return stub.fetch(new Request(request.url,{method:request.method,headers:h,body:request.body,redirect:'manual'}));
    }
    return env.ASSETS.fetch(request)
  }
}
