import {DurableObject} from 'cloudflare:workers';
import {ROOM_DEFS,ROOM_MAP,roomInitialState,applyGameAction,publicGameState,addBotToGame,removeBotFromGame,advanceBots,hasBot,isBotId} from '../shared/games.js';

const COLORS=new Set(['mint','sky','peach','lemon','lilac','milk','cocoa','rose','aqua','lime']);
const clean=(v,n=32)=>String(v??'').replace(/[\r\n\t]/g,' ').replace(/\s+/g,' ').trim().slice(0,n);
const normalizeEmployee=v=>clean(v,24).replace(/\s+/g,'').toUpperCase();
const validEmployee=v=>/^[A-Z0-9]{4,16}$/.test(v);
const maskEmployee=v=>v.length<=4?'*'.repeat(v.length):'*'.repeat(Math.max(2,v.length-4))+v.slice(-4);
const hex=buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');
async function sha(v){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v))))}
const tok=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
function publicUser(u){return {userId:u.userId,loungeId:u.loungeId,name:u.name,slimeColor:u.slimeColor,bio:u.bio||'',role:u.role||'member',presenceStatus:u.presenceStatus||'online',statusMessage:u.statusMessage||'',employeeStatus:u.employeeStatus||'pending',createdAt:u.createdAt}}
function json(obj,status=200){return new Response(JSON.stringify(obj),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function reqJson(req){try{return await req.json()}catch{return {}}}

export class AccountStore extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.data=null;ctx.blockConcurrencyWhile(async()=>{this.data=await ctx.storage.get('data')||{schemaVersion:3,ownerUserId:null,users:{},devices:{},employeeIndex:{},employeeHistory:[],employeeChangeRequests:[],friendships:[],tickets:{},presence:{},rankings:{gomoku:{},xiangqi:{},chess:{},blackjack:{},poker:{}}};this.data.schemaVersion=3;this.data.employeeChangeRequests||=[];this.data.rankings||={gomoku:{},xiangqi:{},chess:{},blackjack:{},poker:{}};const configured=normalizeEmployee(this.env.OWNER_EMPLOYEE_ID||'');let owner=null;if(configured&&validEmployee(configured)){const h=await this.employeeHash(configured);owner=Object.values(this.data.users||{}).find(u=>u.employeeHash===h)||null}else owner=Object.values(this.data.users||{}).find(u=>u.role==='owner')||Object.values(this.data.users||{}).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0))[0]||null;for(const u of Object.values(this.data.users||{}))if(u.role==='owner'&&u.userId!==owner?.userId)u.role='member';if(owner){owner.role='owner';owner.employeeStatus='verified';this.data.ownerUserId=owner.userId}else this.data.ownerUserId=null;for(const u of Object.values(this.data.users||{})){u.presenceStatus=u.presenceStatus||'online';u.statusMessage=u.statusMessage||'';u.employeeStatus=u.employeeStatus||(u.userId===this.data.ownerUserId?'verified':'pending');u.lastSeenAt=u.lastSeenAt||0;u.currentSection=u.currentSection||'';u.currentRoomId=u.currentRoomId||'';}await this.ctx.storage.put('data',this.data)})}
  async persist(){await this.ctx.storage.put('data',this.data)}
  employeeHash(emp){return sha(`${this.env.EMPLOYEE_HASH_SECRET||'CHANGE-ME-IN-CLOUDFLARE'}:${emp}`)}
  makeId(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let id;do{id='SL-';for(let i=0;i<7;i++)id+=chars[Math.floor(Math.random()*chars.length)]}while(Object.values(this.data.users).some(u=>u.loungeId===id));return id}
  async auth(b){const u=this.data.users[String(b.userId||'')],d=this.data.devices[String(b.deviceId||'')];if(!u||!d||d.userId!==u.userId||d.tokenHash!==await sha(b.deviceToken||''))return null;const now=Date.now();d.lastSeenAt=now;u.lastSeenAt=now;return {u,d}}
  relation(a,b){return this.data.friendships.find(f=>((f.a===a&&f.b===b)||(f.a===b&&f.b===a))&&f.state!=='removed')}
  onlineInfo(u){const p=this.data.presence[u.userId],last=Math.max(u.lastSeenAt||0,p?.updatedAt||0),online=Date.now()-last<45000;return {online,lastSeenAt:last,currentSection:online?(u.currentSection||''):null,currentRoomId:online?(p?.roomId||u.currentRoomId||''):null}}
  social(userId){const friends=[],incoming=[],outgoing=[];for(const f of this.data.friendships){if(f.state==='removed'||(f.a!==userId&&f.b!==userId))continue;const other=f.a===userId?f.b:f.a,u=this.data.users[other];if(!u)continue;const e={...publicUser(u),...this.onlineInfo(u)};if(f.state==='accepted')friends.push(e);else if(f.b===userId)incoming.push(e);else outgoing.push(e)}return {friends,incoming,outgoing}}
  isStaff(u){return u&&['owner','admin'].includes(u.role)}
  rankStat(kind,userId){this.data.rankings||=( {gomoku:{},xiangqi:{},chess:{},blackjack:{},poker:{}} );this.data.rankings[kind]||={};return this.data.rankings[kind][userId]||=( {games:0,wins:0,losses:0,draws:0,updatedAt:0} )}
  leaders(){const out={};for(const kind of ['gomoku','xiangqi','chess','blackjack','poker'])out[kind]=Object.entries(this.data.rankings?.[kind]||{}).map(([userId,st])=>{const u=this.data.users[userId];return {...st,userId,name:u?.name||'已离开用户',slimeColor:u?.slimeColor||'mint',loungeId:u?.loungeId||''}}).sort((a,b)=>b.wins-a.wins||b.games-a.games).slice(0,50);const all={};for(const kind of Object.keys(out))for(const r of out[kind]){const a=all[r.userId]||=( {userId:r.userId,name:r.name,slimeColor:r.slimeColor,loungeId:r.loungeId,games:0,wins:0,losses:0,draws:0} );a.games+=r.games;a.wins+=r.wins;a.losses+=r.losses;a.draws+=r.draws}out.overall=Object.values(all).sort((a,b)=>b.wins-a.wins||b.games-a.games).slice(0,50);return out}
  async fetch(req){const url=new URL(req.url),b=req.method==='POST'?await reqJson(req):{};
    if(url.pathname==='/register'){
      const name=clean(b.name,16),emp=normalizeEmployee(b.employeeId),slimeColor=COLORS.has(b.slimeColor)?b.slimeColor:'mint';if(!name)return json({ok:false,error:'请输入昵称'},400);if(!validEmployee(emp))return json({ok:false,error:'工号格式仅接受 4~16 位字母或数字'},400);const eh=await this.employeeHash(emp);if(this.data.employeeIndex[eh])return json({ok:false,error:'该工号已被占用，不能自行覆盖。请联系 Owner 核验并释放冲突工号'},409);const now=Date.now(),userId=crypto.randomUUID(),deviceId=crypto.randomUUID(),deviceToken=tok(),isFirst=Object.keys(this.data.users).length===0,configuredOwner=normalizeEmployee(this.env.OWNER_EMPLOYEE_ID||''),ownerClaim=!this.data.ownerUserId&&(configuredOwner?emp===configuredOwner:isFirst),u={userId,loungeId:this.makeId(),name,slimeColor,bio:'',role:ownerClaim?'owner':'member',employeeHash:eh,employeeMasked:maskEmployee(emp),employeeStatus:ownerClaim?'verified':'pending',presenceStatus:'online',statusMessage:'',lastSeenAt:now,currentSection:'chat',currentRoomId:'',createdAt:now,updatedAt:now};this.data.users[userId]=u;if(ownerClaim)this.data.ownerUserId=userId;this.data.devices[deviceId]={deviceId,userId,label:clean(b.deviceLabel,32)||'当前设备',tokenHash:await sha(deviceToken),createdAt:now,lastSeenAt:now};this.data.employeeIndex[eh]=userId;await this.persist();return json({ok:true,userId,deviceId,deviceToken,profile:publicUser(u),employeeMasked:u.employeeMasked},201)
    }
    if(url.pathname==='/auth'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);await this.persist();return json({ok:true,profile:publicUser(a.u),employeeMasked:a.u.employeeMasked,deviceLabel:a.d.label,social:this.social(a.u.userId)})}
    if(url.pathname==='/presence/ping'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);a.u.lastSeenAt=Date.now();a.u.currentSection=clean(b.section,24);a.u.currentRoomId=clean(b.roomId,48);if(['online','busy','focus','meeting','away','gaming','listening'].includes(b.presenceStatus))a.u.presenceStatus=b.presenceStatus;await this.persist();return json({ok:true,profile:publicUser(a.u)})}
    if(url.pathname==='/profile'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const name=clean(b.name,16);if(!name)return json({ok:false,error:'昵称不能为空'},400);a.u.name=name;a.u.bio=clean(b.bio,80);a.u.statusMessage=clean(b.statusMessage,48);if(['online','busy','focus','meeting','away','gaming','listening'].includes(b.presenceStatus))a.u.presenceStatus=b.presenceStatus;if(COLORS.has(b.slimeColor))a.u.slimeColor=b.slimeColor;a.u.updatedAt=Date.now();a.u.lastSeenAt=Date.now();await this.persist();return json({ok:true,profile:publicUser(a.u)})}
    if(url.pathname==='/employee/change'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const emp=normalizeEmployee(b.employeeId);if(!validEmployee(emp))return json({ok:false,error:'工号格式仅接受 4~16 位字母或数字'},400);const nh=await this.employeeHash(emp),owner=this.data.employeeIndex[nh];if(owner&&owner!==a.u.userId)return json({ok:false,error:'该工号已被其他身份占用，请联系管理员处理冲突'},409);if(a.u.role==='owner'){const old=a.u.employeeHash;delete this.data.employeeIndex[old];this.data.employeeIndex[nh]=a.u.userId;a.u.employeeHash=nh;a.u.employeeMasked=maskEmployee(emp);a.u.employeeStatus='verified';this.data.employeeHistory.push({userId:a.u.userId,oldHash:old,newHash:nh,changedAt:Date.now(),approvedBy:a.u.userId});await this.persist();return json({ok:true,employeeMasked:a.u.employeeMasked,employeeStatus:'verified'})}const reqId=crypto.randomUUID();this.data.employeeChangeRequests=this.data.employeeChangeRequests.filter(x=>x.userId!==a.u.userId||x.state!=='pending');this.data.employeeChangeRequests.push({id:reqId,userId:a.u.userId,newHash:nh,newMasked:maskEmployee(emp),state:'pending',createdAt:Date.now()});await this.persist();return json({ok:true,pending:true,message:'工号变更已提交，等待管理员核验'},202)}
    if(url.pathname==='/ticket'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);if(!ROOM_MAP[b.roomId])return json({ok:false,error:'房间不存在'},404);const ticket=tok();this.data.tickets[await sha(ticket)]={userId:a.u.userId,roomId:b.roomId,exp:Date.now()+60000};await this.persist();return json({ok:true,ticket})}
    if(url.pathname==='/consume'){const h=await sha(b.ticket||''),t=this.data.tickets[h];delete this.data.tickets[h];if(!t||t.exp<Date.now()||t.roomId!==b.roomId){await this.persist();return json({ok:false,error:'ticket invalid'},401)}const u=this.data.users[t.userId];await this.persist();return json({ok:true,userId:t.userId,profile:publicUser(u)})}
    if(url.pathname==='/presence'){const {userId,roomId,online}=b;if(this.data.users[userId]){const now=Date.now();this.data.presence[userId]={roomId,online:!!online,updatedAt:now};this.data.users[userId].lastSeenAt=now;this.data.users[userId].currentRoomId=online?roomId:'';await this.persist()}return json({ok:true})}
    if(url.pathname==='/rooms'){const cnt={};for(const u of Object.values(this.data.users)){const info=this.onlineInfo(u);if(info.online&&info.currentRoomId)cnt[info.currentRoomId]=(cnt[info.currentRoomId]||0)+1}return json({ok:true,rooms:ROOM_DEFS.map(r=>({...r,online:cnt[r.id]||0}))})}
    if(url.pathname==='/leaderboards')return json({ok:true,leaderboards:this.leaders()})
    if(url.pathname==='/admin/users'){const a=await this.auth(b);if(!a||!this.isStaff(a.u))return json({ok:false,error:'无管理员权限'},403);const users=Object.values(this.data.users).map(u=>({...publicUser(u),...this.onlineInfo(u),employeeMasked:u.employeeMasked||'',deviceCount:Object.values(this.data.devices).filter(d=>d.userId===u.userId).length})).sort((x,y)=>(Number(y.online)-Number(x.online))||x.createdAt-y.createdAt);const employeeRequests=this.data.employeeChangeRequests.filter(x=>x.state==='pending').map(x=>({...x,user:publicUser(this.data.users[x.userId]||{})}));await this.persist();return json({ok:true,ownerUserId:this.data.ownerUserId,users,employeeRequests})}
    if(url.pathname==='/admin/role'){const a=await this.auth(b);if(!a||a.u.userId!==this.data.ownerUserId||a.u.role!=='owner')return json({ok:false,error:'只有唯一 Owner 可以调整管理员'},403);const target=this.data.users[String(b.targetUserId||'')];if(!target||target.userId===a.u.userId)return json({ok:false,error:'目标用户无效'},400);if(target.role==='owner'||target.userId===this.data.ownerUserId)return json({ok:false,error:'不能修改 Owner'},403);target.role=b.role==='admin'?'admin':'member';target.updatedAt=Date.now();await this.persist();return json({ok:true,profile:publicUser(target)})}
    if(url.pathname==='/admin/employee'){const a=await this.auth(b);if(!a||!this.isStaff(a.u))return json({ok:false,error:'无管理员权限'},403);const action=String(b.action||'');if(action==='verify'){const target=this.data.users[String(b.targetUserId||'')];if(!target)return json({ok:false,error:'用户不存在'},404);target.employeeStatus='verified';target.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='reject'){const target=this.data.users[String(b.targetUserId||'')];if(!target||target.role==='owner')return json({ok:false,error:'目标无效'},400);if(target.employeeHash)delete this.data.employeeIndex[target.employeeHash];target.employeeHash=null;target.employeeMasked='未绑定';target.employeeStatus='rejected';target.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='approve_change'){const r=this.data.employeeChangeRequests.find(x=>x.id===b.requestId&&x.state==='pending');if(!r)return json({ok:false,error:'变更申请不存在'},404);const target=this.data.users[r.userId];if(!target)return json({ok:false,error:'用户不存在'},404);const conflict=this.data.employeeIndex[r.newHash];if(conflict&&conflict!==target.userId)return json({ok:false,error:'新工号已被其他身份占用'},409);if(target.employeeHash)delete this.data.employeeIndex[target.employeeHash];this.data.employeeIndex[r.newHash]=target.userId;target.employeeHash=r.newHash;target.employeeMasked=r.newMasked;target.employeeStatus='verified';r.state='approved';r.approvedBy=a.u.userId;r.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='reject_change'){const r=this.data.employeeChangeRequests.find(x=>x.id===b.requestId&&x.state==='pending');if(!r)return json({ok:false,error:'变更申请不存在'},404);r.state='rejected';r.approvedBy=a.u.userId;r.updatedAt=Date.now();await this.persist();return json({ok:true})}if(action==='release_conflict'){const emp=normalizeEmployee(b.employeeId);if(!validEmployee(emp))return json({ok:false,error:'工号格式无效'},400);const h=await this.employeeHash(emp),uid=this.data.employeeIndex[h],target=this.data.users[uid];if(!target)return json({ok:false,error:'该工号当前未被占用'},404);if(target.role==='owner')return json({ok:false,error:'不能释放 Owner 工号'},403);delete this.data.employeeIndex[h];target.employeeHash=null;target.employeeMasked='未绑定';target.employeeStatus='rejected';target.updatedAt=Date.now();await this.persist();return json({ok:true,releasedUserId:uid})}return json({ok:false,error:'未知管理员工号操作'},400)}
    if(url.pathname==='/ranking/report'){const r=b.result;if(!r||!r.kind||r.ranked===false)return json({ok:true});for(const x of r.players||[]){if(!this.data.users[x.userId])continue;const st=this.rankStat(r.kind,x.userId);st.games++;if(x.outcome==='win')st.wins++;else if(x.outcome==='draw')st.draws++;else st.losses++;st.updatedAt=Date.now()}await this.persist();return json({ok:true})}
    if(url.pathname==='/social/list'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);return json({ok:true,social:this.social(a.u.userId)})}
    if(url.pathname==='/social/search'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const id=clean(b.loungeId,16).toUpperCase(),u=Object.values(this.data.users).find(x=>x.loungeId===id);if(!u)return json({ok:false,error:'没有找到该 Lounge ID'},404);return json({ok:true,profile:publicUser(u),relation:this.relation(a.u.userId,u.userId)?.state||'none'})}
    if(url.pathname==='/social/request'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const me=a.u.userId,other=String(b.otherUserId||'');if(!this.data.users[other]||other===me)return json({ok:false,error:'用户无效'},400);let f=this.relation(me,other);if(f){if(f.state==='pending'&&f.b===me){f.state='accepted';f.updatedAt=Date.now();await this.persist();return json({ok:true,social:this.social(me)})}return json({ok:false,error:'关系已存在'},409)}this.data.friendships.push({a:me,b:other,state:'pending',createdAt:Date.now(),updatedAt:Date.now()});await this.persist();return json({ok:true,social:this.social(me)})}
    if(url.pathname==='/social/respond'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const me=a.u.userId,other=String(b.otherUserId||''),f=this.relation(me,other);if(!f||f.state!=='pending'||f.b!==me)return json({ok:false,error:'申请不存在'},404);f.state=b.accept?'accepted':'removed';f.updatedAt=Date.now();await this.persist();return json({ok:true,social:this.social(me)})}
    if(url.pathname==='/social/remove'){const a=await this.auth(b);if(!a)return json({ok:false,error:'设备身份无效'},401);const me=a.u.userId,other=String(b.otherUserId||''),f=this.relation(me,other);if(!f||f.state!=='accepted')return json({ok:false,error:'好友不存在'},404);f.state='removed';f.updatedAt=Date.now();await this.persist();return json({ok:true,social:this.social(me)})}
    return json({ok:false,error:'Not found'},404)
  }
}

export class RoomStore extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.state=null;this.roomId='';ctx.blockConcurrencyWhile(async()=>{this.state=await ctx.storage.get('state')||null})}
  accounts(){return this.env.ACCOUNTS.getByName('global')}
  async account(path,obj){return (await this.accounts().fetch(new Request('https://accounts'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(obj)}))).json()}
  sockets(){return this.ctx.getWebSockets()}
  attachment(ws){try{return ws.deserializeAttachment()}catch{return null}}
  users(){return this.sockets().map(ws=>this.attachment(ws)?.profile).filter(Boolean)}
  send(ws,obj){try{ws.send(JSON.stringify(obj))}catch{}}
  broadcast(obj){for(const ws of this.sockets())this.send(ws,obj)}
  async save(){await this.ctx.storage.put('state',this.state)}
  async gameBroadcast(){for(const ws of this.sockets()){const a=this.attachment(ws);this.send(ws,{type:'game_state',state:publicGameState(this.state.game,a?.userId)})}}
  async fetch(req){const url=new URL(req.url);if(req.headers.get('Upgrade')!=='websocket')return json({ok:false,error:'WebSocket required'},426);const roomId=req.headers.get('x-room-id')||url.searchParams.get('roomId')||'';const def=ROOM_MAP[roomId];if(!def)return json({ok:false,error:'房间不存在'},404);this.roomId=roomId;const staleGame=def.game&&(!this.state?.game||this.state.game.kind!==def.game||(['gomoku','xiangqi','chess'].includes(def.game)&&(!Array.isArray(this.state.game.ready)||typeof this.state.game.started!=='boolean')));if(!this.state||staleGame){this.state=roomInitialState(def);await this.save()}const t=await this.account('/consume',{ticket:url.searchParams.get('ticket')||'',roomId});if(!t.ok)return json(t,401);const pair=new WebSocketPair(),[client,server]=Object.values(pair);server.serializeAttachment({userId:t.userId,profile:t.profile,roomId});this.ctx.acceptWebSocket(server);await this.account('/presence',{userId:t.userId,roomId,online:true});this.send(server,{type:'init',room:def,profile:t.profile,users:this.users(),messages:(this.state.messages||[]).slice(-60),music:this.state.music||null,game:def.game?publicGameState(this.state.game,t.userId):null});this.broadcast({type:'presence',users:this.users()});return new Response(null,{status:101,webSocket:client})}
  async webSocketMessage(ws,message){let m;try{m=JSON.parse(String(message))}catch{return}const a=this.attachment(ws),def=ROOM_MAP[a?.roomId||this.roomId];if(!a||!def)return;try{
    if(m.type==='heartbeat'){await this.account('/presence',{userId:a.userId,roomId:a.roomId,online:true});this.send(ws,{type:'heartbeat_ack',at:Date.now()});return}
    if(m.type==='chat'){const text=clean(m.text,300);if(!text)return;if(def.adminOnlyPost&&!['owner','admin'].includes(a.profile.role))throw Error('该讨论区仅管理员可以发言');const msg={id:crypto.randomUUID(),userId:a.userId,name:a.profile.name,slimeColor:a.profile.slimeColor,role:a.profile.role||'member',text,at:Date.now()};this.state.messages=this.state.messages||[];this.state.messages.push(msg);while(this.state.messages.length>100)this.state.messages.shift();await this.save();this.broadcast({type:'chat',message:msg});return}
    if(m.type==='music_set'&&def.category==='music'){const id=String(m.trackId||'').match(/\d{3,20}/)?.[0];if(!id)throw Error('请输入网易云歌曲 ID 或歌曲链接');this.state.music={trackId:id,title:clean(m.title,80)||`网易云歌曲 ${id}`,setBy:a.profile.name,updatedAt:Date.now()};await this.save();this.broadcast({type:'music_state',music:this.state.music});return}
    if(m.type==='game_action'&&def.game){const before=JSON.parse(JSON.stringify(this.state.game)),act=m.action||{};if(act.type==='add_bot')addBotToGame(this.state.game,Number.isInteger(act.seat)?act.seat:null);else if(act.type==='remove_bot')removeBotFromGame(this.state.game,Number.isInteger(act.seat)?act.seat:null);else applyGameAction(this.state.game,a.userId,act);advanceBots(this.state.game);const after=this.state.game;let result=null;if(!hasBot(after)){if(['gomoku','xiangqi','chess'].includes(after.kind)&&((after.winner&&!before.winner)||(after.result&&!before.result))){result={kind:after.kind,ranked:true,players:after.players.filter(Boolean).map(uid=>({userId:uid,outcome:after.winner?after.winner===uid?'win':'loss':'draw'}))}}else if(['blackjack','poker'].includes(after.kind)&&after.handNo>(before.handNo||after.handNo)&&!after.practice){result={kind:after.kind,ranked:true,players:after.seats.filter(Boolean).filter(p=>!isBotId(p.userId)).map(p=>({userId:p.userId,outcome:String(p.result||'').includes('胜')?'win':String(p.result||'').includes('平')?'draw':'loss'}))}}}if(result)await this.account('/ranking/report',{result});await this.save();await this.gameBroadcast();return}
  }catch(e){this.send(ws,{type:'error',error:e.message})}}
  async webSocketClose(ws){const a=this.attachment(ws);if(a)await this.account('/presence',{userId:a.userId,roomId:a.roomId,online:false});this.broadcast({type:'presence',users:this.users()})}
  async webSocketError(ws){await this.webSocketClose(ws)}
}

async function accountFetch(env,path,reqBody){const stub=env.ACCOUNTS.getByName('global');return stub.fetch(new Request('https://accounts'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(reqBody||{})}))}
const musicCache=new Map();
async function searchNetease(q,env){const query=clean(q,80);if(!query)return [];const key=query.toLowerCase(),hit=musicCache.get(key);if(hit&&Date.now()-hit.at<300000)return hit.results;const base=String(env?.NETEASE_SEARCH_BASE||'').replace(/\/$/,'');const urls=base?[`${base}/search?keywords=${encodeURIComponent(query)}&limit=12`]:[`https://music.163.com/api/search/get/web?csrf_token=hlpretag=&hlposttag=&s=${encodeURIComponent(query)}&type=1&offset=0&total=true&limit=12`,`https://music.163.com/api/search/get?s=${encodeURIComponent(query)}&type=1&limit=12&offset=0`];const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),2500);const attempt=async u=>{const r=await fetch(u,{signal:ctrl.signal,headers:{'user-agent':'Mozilla/5.0','referer':'https://music.163.com/','accept':'application/json,text/plain,*/*'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json(),songs=j?.result?.songs||[];if(!songs.length)throw Error('没有搜索结果');return songs.map(x=>({id:String(x.id),name:x.name||'未知歌曲',artists:(x.artists||x.ar||[]).map(a=>a.name).filter(Boolean),album:x.album?.name||x.al?.name||'',duration:x.duration||x.dt||0}))};try{const results=await Promise.any(urls.map(attempt));musicCache.set(key,{at:Date.now(),results});return results}catch(e){if(ctrl.signal.aborted)throw Error('网易云搜索超时（2.5 秒）：当前网络无法访问音乐搜索源');const first=e?.errors?.[0]||e;throw Error('网易云搜索失败：'+(first?.message||'网络不可达'))}finally{clearTimeout(timer)}}

export default{
  async fetch(request,env){const url=new URL(request.url);
    if(url.pathname==='/api/health')return json({ok:true,app:'SlimeLounge',version:'0.0.3'});
    if(url.pathname==='/api/rooms')return env.ACCOUNTS.getByName('global').fetch(new Request('https://accounts/rooms'));
    if(url.pathname==='/api/leaderboards')return env.ACCOUNTS.getByName('global').fetch(new Request('https://accounts/leaderboards',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}));
    if(url.pathname==='/api/music/search'&&request.method==='GET'){try{return json({ok:true,results:await searchNetease(url.searchParams.get('q')||'',env)})}catch(e){return json({ok:false,error:e.message},502)}}
    const routes={'/api/register':'/register','/api/auth':'/auth','/api/presence/ping':'/presence/ping','/api/profile':'/profile','/api/employee/change':'/employee/change','/api/ticket':'/ticket','/api/social/list':'/social/list','/api/social/search':'/social/search','/api/social/request':'/social/request','/api/social/respond':'/social/respond','/api/social/remove':'/social/remove','/api/admin/users':'/admin/users','/api/admin/role':'/admin/role','/api/admin/employee':'/admin/employee'};
    if(routes[url.pathname]&&request.method==='POST')return accountFetch(env,routes[url.pathname],await reqJson(request));
    if(url.pathname==='/api/ws'){
      const roomId=url.searchParams.get('roomId')||request.headers.get('x-room-id');if(!ROOM_MAP[roomId])return json({ok:false,error:'房间不存在'},404);const stub=env.ROOMS.getByName(roomId),h=new Headers(request.headers);h.set('x-room-id',roomId);return stub.fetch(new Request(request.url,{method:request.method,headers:h,body:request.body,redirect:'manual'}));
    }
    return env.ASSETS.fetch(request)
  }
}
