import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {classifyDdz,beatsDdz,createDoudizhu,applyDoudizhuAction,publicDoudizhuState} from '../../shared/doudizhu.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const ok=(v,m)=>{if(!v)throw Error(m)};
const c=(r,s='S')=>({id:r+s,r,s,v:['3','4','5','6','7','8','9','10','J','Q','K','A','2'].indexOf(r)+3});
const sj={id:'SJ',joker:'small',r:'SJ',v:16},bj={id:'BJ',joker:'big',r:'BJ',v:17};
ok(classifyDdz([c('3')]).type==='single','ddz single');
ok(classifyDdz([c('4','S'),c('4','H')]).type==='pair','ddz pair');
ok(classifyDdz([c('3'),c('4'),c('5'),c('6'),c('7')]).type==='straight','ddz straight');
ok(classifyDdz([c('6','S'),c('6','H'),c('6','C'),c('6','D')]).type==='bomb','ddz bomb');
ok(classifyDdz([sj,bj]).type==='rocket','ddz rocket');
ok(beatsDdz([sj,bj],[c('2','S'),c('2','H'),c('2','C'),c('2','D')]),'rocket beats bomb');
const s=createDoudizhu();for(let i=0;i<3;i++){applyDoudizhuAction(s,'U'+i,{type:'join',seat:i});applyDoudizhuAction(s,'U'+i,{type:'ready'})}applyDoudizhuAction(s,'U0',{type:'start'});ok(s.phase==='bidding'&&s.seats.every(x=>x.hand.length===17),'ddz deal');const bidder=s.seats[s.bidSeat].userId;applyDoudizhuAction(s,bidder,{type:'bid',score:3});ok(s.phase==='playing'&&s.landlordSeat!=null&&s.seats[s.landlordSeat].hand.length===20,'ddz landlord/bottom');const pub=publicDoudizhuState(s,'U0');ok(pub.seats.filter(x=>x.userId!=='U0').every(x=>x.hand.every(c=>c.hidden)),'ddz opponent privacy');
const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8'),html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),ui=fs.readFileSync(path.join(root,'public/progression-ui.js'),'utf8'),mj=fs.readFileSync(path.join(root,'public/game-mahjong.js'),'utf8'),rj=fs.readFileSync(path.join(root,'shared/riichi.js'),'utf8'),diag=fs.readFileSync(path.join(root,'server/runtime_diagnostics.js'),'utf8'),admin=fs.readFileSync(path.join(root,'public/app-games.js'),'utf8'),prog=fs.readFileSync(path.join(root,'server/progression.js'),'utf8');
const order=['data-section="chat"','data-section="music"','data-section="games"','data-section="rankings"','data-section="shop"','data-section="pet"','data-section="friends"','data-section="me"','data-section="admin"'].map(x=>html.indexOf(x));ok(order.every((x,i)=>x>=0&&(i===0||x>order[i-1])),'main nav order');
ok(ui.includes('/api/profile-card')&&ui.includes('添加好友')&&ui.includes('user-card-modal'),'profile card/add friend');
ok(prog.includes('SHOP_CATALOG')&&prog.includes('ACHIEVEMENTS')&&prog.includes('/api/progression/admin-title')&&prog.includes('refreshPet'),'progression systems');
ok(admin.includes('头衔管理')&&admin.includes('data-title-grant'),'admin title management');
ok(mj.includes('relativeSeats(s,me)')&&mj.includes('mjEdgeRail')&&mj.includes('mj-own-rail')&&!mj.includes('mjResultRevealRows(s,d){return (d.reveals||[]).map(r=>{const p=s.seats?.[r.seat],hand='),'riichi seat-relative table reveal');
ok(rj.includes('allLastRepeats')&&rj.includes('round===2')&&rj.includes('if(hand===4)return finishMatch(s)'),'riichi match ending guard');
ok(diag.includes('const noteworthy=status>=500||status===429||ms>=1000'),'diagnostics filters fast expected 4xx');
ok(app.includes("doudizhu:'斗地主'")&&html.includes('progression-ui.js?v=0.3.4&build=034'),'ddz/progression client integration');
const note=JSON.parse(fs.readFileSync(path.join(root,'release_notes/v0.3.4.json'),'utf8'));ok(note.id==='v0.3.4'&&note.items.length>=10,'release note v0.3.4');
console.log('[OK] v0.3.4 profile card / Riichi perspective+ending / Dou Dizhu / pets+achievements+titles+shop / diagnostics');
