import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {DEFAULT_PROGRESSION_CONFIG,normalizeProgressionConfig} from '../../server/progression.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const ok=(v,m)=>{if(!v)throw Error(m)};
const prog=fs.readFileSync(path.join(root,'server/progression.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'public/progression-ui.js'),'utf8');
const admin=fs.readFileSync(path.join(root,'public/app-games.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public/styles-responsive.css'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const cfg=normalizeProgressionConfig(DEFAULT_PROGRESSION_CONFIG);
ok(cfg.account.levelXpBase>0&&cfg.pet.levelXpBase>0,'growth config missing');
ok(cfg.shop.accessories.every(x=>x.price>=1000&&x.asset&&x.slot),'accessory prices/visual config too weak');
ok(cfg.shop.titles.every(x=>x.price>=5000),'title defaults still too cheap');
ok(cfg.achievements.every(x=>!('title' in x)),'achievements must not grant titles');
ok(!JSON.stringify(cfg).includes('认识你很高兴'),'removed title still present');
ok(prog.includes('/api/progression/admin-config')&&prog.includes('/api/progression/admin-shop')&&prog.includes('/api/progression/admin-achievement')&&prog.includes('/api/progression/admin-user'),'progression admin APIs missing');
ok(prog.includes('头衔统一由后台创建商品并在商城购买')&&prog.includes('admin-title'),'legacy direct title endpoint is not retired');
ok(admin.includes('商城设置')&&admin.includes('成长与宠物')&&!admin.includes('data-admin-tab="achievements"')&&admin.includes('renderProgressionAdminSection')&&!admin.includes('data-title-grant'),'admin still directly grants titles');
ok(ui.includes('pet-acc-img')&&ui.includes('图片/样式资源')&&ui.includes('data-prog-core')&&ui.includes('用户成长数据'),'admin/real accessory UI missing');
ok(css.includes('.pet-acc-img')&&css.includes('.prog-admin-row'),'progression/accessory CSS missing');
for(const f of ['bow.svg','leaf.svg','star.svg','glasses.svg','scarf.svg'])ok(fs.existsSync(path.join(root,'public/accessories',f)),`accessory asset missing ${f}`);
ok(html.includes('progression-ui.js?v=0.4.1&build=041'),'v0.3.8 asset revision missing');
const note=JSON.parse(fs.readFileSync(path.join(root,'release_notes/v0.3.5.json'),'utf8'));ok(note.id==='v0.3.5'&&note.items.length>=8,'release note v0.3.5 missing');
const prev=JSON.parse(fs.readFileSync(path.join(root,'release_notes/v0.3.3.json'),'utf8'));ok(prev.id==='v0.3.3','v0.3.3 release-note metadata corrupted');
console.log('[OK] retained v0.3.5 configurable growth/shop/achievements/user data / purchasable titles / real pet accessories');
