import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {normalizeLeisureConfig} from '../../server/leisure_service.js';
import {normalizeProgressionConfig} from '../../server/progression.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const ok=(v,m)=>{if(!v)throw Error(m)};
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const leisure=fs.readFileSync(path.join(root,'server/leisure_service.js'),'utf8');
const leisureUi=fs.readFileSync(path.join(root,'public/leisure-ui.js'),'utf8');
const progression=fs.readFileSync(path.join(root,'server/progression.js'),'utf8');
const progressionUi=fs.readFileSync(path.join(root,'public/progression-ui.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
ok(pkg.version==='0.4.6','package version is not v0.4.6');
ok(html.includes('/icons/fishing-nav.svg?v=0.4.6')&&!html.includes('<span class="nav-icon">🎣</span><span class="nav-label">钓鱼</span>'),'pixel fishing nav icon missing');
ok(leisure.includes("baskets:['basket_starter']")&&leisure.includes("/api/leisure/fishing/basket")&&leisureUi.includes('fishingBasketsHtml'),'basket ownership/shop/API missing');
ok(leisure.includes("action==='rod-upsert'")&&leisure.includes("action==='basket-upsert'")&&leisureUi.includes('data-rod-save')&&leisureUi.includes('data-basket-save'),'rod/basket admin pricing missing');
ok(leisure.includes('Math.round(fish.basePrice*q[1]*sizeFactor*weightFactor)')&&!leisure.includes('sizeFactor*weightFactor/25)*25'),'final fish value still forced to multiples of 25');
ok(progression.includes('lowHungerChipCostPctPerHour')&&progression.includes('badMoodChipCostPctPerHour')&&!progression.includes('charge+=cfg.pet.lowHungerChipCostPerHour'),'pet chip penalty is not percentage-based');
ok(progressionUi.includes('玩家已购物品')&&progression.includes('purchasedSummary'),'admin purchased-item overview missing');
ok(leisure.includes('noise=((Math.random()+Math.random()+Math.random()+Math.random()+Math.random()+Math.random())-3)/3')&&leisure.includes('momentum=clamp(num(s.lastRet)*.16'),'market smoothing model missing');
const lc=normalizeLeisureConfig({version:5,fishing:{rods:[{id:'rod_training',name:'自定义训练竿',price:777,enabled:true}],fish:[{id:'carp',name:'自定义鲤鱼',basePrice:125,difficulty:15,rarity:1,minSize:30,maxSize:78,enabled:true}]}});
ok(lc.fishing.rods[0].price===777&&lc.fishing.fish[0].basePrice===125,'v0.4.6 migration overwrote existing rod/fish price');
ok(lc.fishing.baskets.length>=5&&lc.fishing.baskets.some(x=>x.id==='basket_starter'),'default baskets not added for legacy config');
const pc=normalizeProgressionConfig({version:9,pet:{lowHungerChipCostPerHour:40,badMoodChipCostPerHour:25},shop:{accessories:[{id:'acc_bowtie',name:'礼服领结',price:9999,slot:'neck',desc:'自定义说明',enabled:true,asset:'/accessories/bowtie.svg',x:44,y:77,w:55,rotate:3,z:7,color:'#cb5472'}]}});
const bow=pc.shop.accessories.find(x=>x.id==='acc_bowtie');
ok(bow.price===9999&&bow.x===44&&bow.y===77&&bow.color==='#11151b','accessory visual migration overwrote user price/position or missed bowtie black default');
ok(pc.pet.lowHungerChipCostPctPerHour===0.35&&pc.pet.badMoodChipCostPctPerHour===0.2,'legacy pet fixed chip cost did not migrate to balanced percentages');
console.log('[OK] v0.4.6 baskets / admin ownership / pixel assets / fish pricing / pet percentages / market realism');
