import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {normalizeLeisureConfig} from '../../server/leisure_service.js';
import {normalizeProgressionConfig} from '../../server/progression.js';
import {normalizeEconomy} from '../../server/economy.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const ok=(v,m)=>{if(!v)throw Error(m)};
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const leisure=fs.readFileSync(path.join(root,'server/leisure_service.js'),'utf8');
const leisureUi=fs.readFileSync(path.join(root,'public/leisure-ui.js'),'utf8');
const progression=fs.readFileSync(path.join(root,'server/progression.js'),'utf8');
const progressionUi=fs.readFileSync(path.join(root,'public/progression-ui.js'),'utf8');
const economy=fs.readFileSync(path.join(root,'server/economy.js'),'utf8');
const adminEconomy=fs.readFileSync(path.join(root,'public/admin-economy.js'),'utf8');
const pokerUi=fs.readFileSync(path.join(root,'public/game-poker.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const fishingNav=fs.readFileSync(path.join(root,'public/icons/fishing-nav.svg'),'utf8');
const star=fs.readFileSync(path.join(root,'public/accessories/star.svg'),'utf8');
const halo=fs.readFileSync(path.join(root,'public/accessories/halo.svg'),'utf8');
const monocle=fs.readFileSync(path.join(root,'public/accessories/monocle.svg'),'utf8');
ok(pkg.version==='0.4.6','package version is not v0.4.6');
ok(html.includes('/icons/fishing-nav.svg?v=0.4.6')&&!html.includes('<span class="nav-icon">🎣</span><span class="nav-label">钓鱼</span>'),'pixel fishing nav icon missing');
ok(/fill="#ffffff"/i.test(fishingNav)&&!/fill="#(?!ffffff)[0-9a-f]{6}/i.test(fishingNav),'fishing nav icon is not pure white');
ok(star.includes('viewBox="0 0 28 24"')&&halo.includes('viewBox="0 0 48 20"')&&monocle.includes('fill-opacity="0.18"'),'updated terraria-like accessory assets missing');
ok(progression.includes('version:11')&&progression.includes("acc_halo")&&progression.includes('migrateAccessoryV11'),'accessory v0.4.6 migration/version missing');
ok(progressionUi.includes('data-acc-preview'),'accessory preview UI missing');
ok(leisure.includes('minBaseRatio:0.1')&&leisure.includes('maxBaseRatio:10')&&leisure.includes('sessionStartHour:8')&&leisure.includes('sessionEndHour:21')&&leisure.includes('weekendClosed:true'),'market price band / schedule defaults missing');
ok(leisure.includes('marketIsOpen(cfg,now)')&&leisure.includes('当前为休市时间，仅工作日 08:00-21:00 开放交易'),'market closed-time trade guard missing');
ok(leisureUi.includes('market.minBaseRatio')&&leisureUi.includes('market.maxBaseRatio')&&leisureUi.includes('market.sessionStartHour')&&leisureUi.includes('market.weekendClosed'),'market admin controls missing');
ok(economy.includes('buyInCapBb:200')&&adminEconomy.includes('chipRulePokerCap')&&pokerUi.includes('上限 ${bounds.capBb}BB'),'poker buy-in cap admin/ui missing');
const lc=normalizeLeisureConfig({version:6,market:{minBaseRatio:0.05,maxBaseRatio:12,sessionStartHour:7,sessionEndHour:22,weekendClosed:false},fishing:{rods:[{id:'rod_training',name:'自定义训练竿',price:777,enabled:true}],fish:[{id:'carp',name:'自定义鲤鱼',basePrice:125,difficulty:15,rarity:1,minSize:30,maxSize:78,enabled:true}]}});
ok(lc.market.minBaseRatio===0.05&&lc.market.maxBaseRatio===12&&lc.market.sessionStartHour===7&&lc.market.sessionEndHour===22&&lc.market.weekendClosed===false,'market config normalization overwrote custom price-band/schedule');
ok(lc.fishing.rods[0].price===777&&lc.fishing.fish[0].basePrice===125,'v0.4.6 migration overwrote existing rod/fish price');
const pc=normalizeProgressionConfig({version:10,shop:{accessories:[{id:'acc_halo',name:'史莱姆光环',price:12800,slot:'effect',desc:'漂浮在头顶的柔光环',enabled:true,asset:'/accessories/halo.svg',x:50,y:-2,w:70,rotate:0,z:4,color:'#ffe77a'}]}});
const haloAcc=pc.shop.accessories.find(x=>x.id==='acc_halo');
ok(pc.version===11&&haloAcc&&haloAcc.y===4&&haloAcc.w===64,'accessory v11 migration did not refresh default halo placement');
const eco=normalizeEconomy({gameRules:{poker:{smallBlind:10,bigBlind:20,buyInCapBb:320}}});
ok(eco.gameRules.poker.buyInCapBb===320,'poker buy-in cap normalization missing');
console.log('[OK] v0.4.6 accessory refresh / market schedule+bands / poker buy-in cap / white fishing icon');
